### ISSUE TITLE
#load <script> does not work

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#1860] opened 2023-04-05 13:22 UTC
### Describe the bug
`#load "foo.fsx"` does not seem to work in the code editor: types and namespaces are not accessible in the IDE (type X is not defined etc.). However, send to interactive proves that the code is valid as it compiles and executes.

### Steps to reproduce
1. Create a script
2. Create a second script that references the first.
3. Try to reference a type from the first script.

### Expected behaviour
Types defined in the first script should show up.

## Machine info
 - OS: Windows
 - .NET SDK version: 7.0.202
 - Ionide version: 7.5.2

**Comment by isaacabraham** [comment] 2023-04-05 13:58
@baronfel Don't know - just using the default settings.

I've literally just tested with VS and seen the same thing though - I fixed it by changing the load to e.g. `#load "./foo.fsx" and then it works.

I'm pretty sure that this used to work in previous versions of F#?

**Comment by isaacabraham** [comment] 2023-04-05 14:00
Weirdly though, it now sort of seems to work without the leading `./`, although Ionide is a bit slowly to react when the path changes.

**Comment by TheAngryByrd** [comment] 2023-04-26 14:25
Closing since I can't reproduce with the adaptive LSP server enabled (which is now default)

**Closed by TheAngryByrd** 2023-04-26 14:25 UTC
