### ISSUE TITLE
Ionide-fsharp icon too small

### ISSUE THREAD

**Issue by mvperez** [ionide/ionide-vscode-fsharp#1192] opened 2019-08-09 04:20 UTC
Issue Type: <b>Bug</b>

The Ionide F# Icon is too small.

Extension version: 4.0.6
VS Code version: Code 1.37.0 (036a6b1d3ac84e5ca96a17a44e63a87971f8fcc8, 2019-08-08T02:33:50.993Z)
OS version: Windows_NT x64 10.0.18362
Remote OS version: Linux x64 4.9.125-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (3.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Attached Container ubuntudev (/ubuntudevcontainer_ubuntudev_1)|
|OS|Linux x64 4.9.125-linuxkit|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (2 x 2446)|
|Memory (System)|3.86GB (0.47GB free)|
|VM|0%|
</details>

**Comment by sergey-tihon** [comment] 2019-08-09 04:55
It is related to [New product icons](https://code.visualstudio.com/updates/v1_37#_new-product-icons) release 
<img width="507" alt="Release_Notes__1_37_0_—_fsharp-weekly_and_Ionide-fsharp_icon_too_small_·_Issue__1192_·_ionide_ionide-vscode-fsharp" src="https://user-images.githubusercontent.com/1197905/62755027-f7f02e00-ba7a-11e9-947b-3e1bdb18828b.png">

**Comment by Krzysztof-Cieslak** [comment] 2019-08-09 08:26
Duplicate of #1191

**Closed by Krzysztof-Cieslak** 2019-08-09 08:26 UTC
