### ISSUE TITLE
Extension doesn't work: ECONNREFUSED 127.0.0.1:8080 in developer console

### ISSUE THREAD

**Issue by eerohele** [ionide/ionide-vscode-fsharp#286] opened 2016-11-21 10:47 UTC
The extension worked fine for me earlier, but now I just get `ECONNREFUSED 127.0.0.1:8080` in developer console and none of the features work.

I suspect the issue may have been introduced by 23d624b7108226ed3bb3bc9790ebe7649942ac52, but I can't be sure since I don't know how to downgrade the extension to an earlier version.

Would it be possible to make the `fsacAction` URL configurable, for example?

I don't know if it matters, but I'm behind a corporate proxy. I have both localhost and 127.0.0.1 in my NO_PROXY environment variable, but I'm not sure whether that even should make a difference in this case.

**Comment by Krzysztof-Cieslak** [comment] 2016-11-24 12:38
Can you enable some additional logging (as described in https://github.com/ionide/ionide-vscode-fsharp#how-to-get-logs-for-debugging--issue-reporting) and post whole log from start of extension?

**Comment by eerohele** [comment] 2016-11-25 11:33
Here's the output from the F# Language Service window:

```
[13:22:04 DEBUG] got FSAC line, is it the started message? true
[13:22:04 DEBUG] FSAC stdout: [I] 2016-11-25T11:22:04.1457171Z: listener started in 36.026 ms with binding 127.0.0.1:8737 [Suave.Tcp.tcpIpServer]

[13:22:04 INFO ] REQ (001) -> {lint}, File = "Program.fs"
[13:22:04 INFO ] REQ (002) -> {project}, File = "MyProj.fsproj"
[13:22:04 INFO ] REQ (003) -> {parse}, File = "Program.fs"
[13:22:05 ERROR] RES (002) <- {project} ERROR in 1014 ms: Error: connect ECONNREFUSED 127.0.0.1:8080 Data=undefined
[13:22:05 ERROR] RES (001) <- {lint} ERROR in 1021 ms: Error: connect ECONNREFUSED 127.0.0.1:8080 Data=undefined
[13:22:05 ERROR] RES (003) <- {parse} ERROR in 1004 ms: Error: connect ECONNREFUSED 127.0.0.1:8080 Data=undefined
```

**Comment by Krzysztof-Cieslak** [comment] 2016-11-25 12:05
The problem is that we start server on `127.0.0.1:8737` and for some reason try to make requests at `127.0.0.1:8080`

**Comment by eerohele** [comment] 2016-11-25 12:07
Right; this is actually a duplicate of #272.

**Comment by Krzysztof-Cieslak** [comment] 2016-11-29 13:07
Closing this one, future discussion on #272

**Closed by Krzysztof-Cieslak** 2016-11-29 13:07 UTC
Labels: bug, duplicate

**Comment by subhajitmishra** [comment] 2018-11-26 09:49
Unhandled rejection StatusCodeError: 404 - "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot POST /parse</pre>\n</body>\n</html>\n"
    at new StatusCodeError (D:\RASA\botkit-starter-web-master\node_modules\request-promise-core\lib\errors.js:32:15)
    at Request.plumbing.callback (D:\RASA\botkit-starter-web-master\node_modules\request-promise-core\lib\plumbing.js:104:33)
    at Request.RP$callback [as _callback] (D:\RASA\botkit-starter-web-master\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at Request.self.callback (D:\RASA\botkit-starter-web-master\node_modules\request\request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (D:\RASA\botkit-starter-web-master\node_modules\request\request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (D:\RASA\botkit-starter-web-master\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by subhajitmishra** [comment] 2018-11-26 09:50
I am getting the above error. Please help.
