### ISSUE TITLE
recordStubGenerator creates unparsable output

### ISSUE THREAD

**Issue by forki** [ionide/ionide-vscode-fsharp#865] opened 2018-07-27 07:07 UTC
![image](https://user-images.githubusercontent.com/57396/43306713-563d3ae4-917c-11e8-931b-c593a9ce7701.png)

and this goes on forever. output is growing and growing

/cc @MangelMaxime

**Comment by forki** [comment] 2018-07-27 07:08
and that file `C:\\Program Files\\Microsoft VS Code\\extension-output-#1.fsx` doesn't even exist

**Comment by MangelMaxime** [comment] 2018-07-27 07:40
Duplicate of #864 

I didn't have this output in debug mode or didn't saw it. 

I don't know where the `extension-output-#1.fsx` is coming from..

**Comment by MangelMaxime** [comment] 2018-07-27 07:44
I have one question :) 

There is definitly a bug but why are you guys looking at `F#: Language Server` output channel ?

**Comment by forki** [comment] 2018-07-27 07:55
I look into this since @Krzysztof-Cieslak and myself try to resolve another issue where FSAC is sending messages all the time. Well @Krzysztof-Cieslak is trying to fix it and I'm just checking ;-)

**Comment by Krzysztof-Cieslak** [comment] 2018-07-27 10:56
Fixed in 3.24.1 - issue was caused by the fact that 1. there was no any throttling 2. record stub handler was not checking if the document was F# which caused infinite loop (i.e handler was executed when something was written to output channel, and handler itself was writing to output channel)

**Closed by Krzysztof-Cieslak** 2018-07-27 10:56 UTC

**Comment by forki** [comment] 2018-07-27 11:07
hugs. seems to work!

Am Fr., 27. Juli 2018 um 12:56 Uhr schrieb Krzysztof Cieślak <
notifications@github.com>:
