### ISSUE TITLE
Ionide extension activates for non-F# projects

### ISSUE THREAD

**Issue by smcl** [ionide/ionide-vscode-fsharp#1701] opened 2022-04-30 09:25 UTC
### Describe the bug

If you have created C# or D project with Visual Studio (I've tried 2019 and 2022) in Visual Studio Code with Ionide for F# installed, Ionide thinks it's an F# project so a few seconds after you open it the F# Solution Explorer opens up on the left. It's not the *worst* thing in the world but it is quite irritating and feels wrong.

Ionide is presumably looking for the existence of a .sln file or .csproj file, rather than trying to detect whether F# is used at all.

### Steps to reproduce

Prerequisites:
- Visual Studio should be installed
- Visual Studio Code should be installed
- Ionide F# extension for should be installed in Visual Studio Code

To reproduce the issue:
1. create a C# project in Visual Studio (or clone the linked repo)
2. switch to Visual Studio Code, open the folder containing the solution
3. notice that a couple of seconds after opening, the F# Solution Explorer pops up in the left pane (replacing the files list or whatever you were looking at)

### Link to sample reproduction

I have created a repo which contains two projects: https://github.com/smcl/ionide-issue

You can reproduce the issue by opening either of the folders with VS Code (note: if you open the top-level it *won't* reproduce, you need to drill down at least one level into either folder).

### Expected behaviour

Since there are no .fsproj or .fs files or anything to do with F#, I don't think Ionide should try to start up or do anything, and importantly it shouldn't raise the F# Solution Explorer.

### Screenshots

n/a

## Machine info

 - OS: Windows
 - .NET SDK version: 6.0.202
 - Ionide version: v6.0.1

### Additional context

n/a

**Comment by olivercoad** [comment] 2022-04-30 10:30
See #1041 for more info.

I still don't know why #1401 wasn't merged. @Krzysztof-Cieslak

**Comment by smcl** [comment] 2022-04-30 11:30
Ah you're right, sorry I didn't realise. It does indeed seem that this activation event can catch all sorts of non-F# projects:

		"workspaceContains:**/*.sln",

**Comment by Krzysztof-Cieslak** [comment] 2022-07-12 12:26
Duplicate of #1041

**Closed by Krzysztof-Cieslak** 2022-07-12 12:26 UTC

**Comment by smcl** [comment] 2022-07-12 12:31
@Krzysztof-Cieslak can you explain why you think this is a duplicate, and why Ionide shouldn’t behave as we have described it does?

because right now Ionide thinks EVERY Visual Studio solution is an F# project. It is quite an annoying issue with, apparently, a very easy fix that doesn’t seem to impact F# projects.

**Comment by olivercoad** [comment] 2022-07-18 08:55
This is not a duplicate of #1041. That issue addressed just one symptom. https://github.com/fsharp/FsAutoComplete/pull/668 was always just a band-aid fix and was never meant to be the only measure taken. I'm quite disapponted to see this issue and 1401 be closed without an explaination and would still like to see it merged.
