### ISSUE TITLE
New F# Project on Kubuntu: Project Parsing Failed

### ISSUE THREAD

**Issue by bytesource** [ionide/ionide-vscode-fsharp#1013] opened 2019-02-08 08:50 UTC
I installed F#, Mono, Net.Core on Kubuntu 18.04 using these instructions: https://atlemann.github.io/fsharp/2018/10/11/safe-stack-on-ubuntu-18.04.html

After that I restarted my computer, opened VS Code and added a new claslib project ('HelloWorld') via F#: New Project.

However, on opening the project folder inside VSCode, I was greeted with this "Project parsing failed" error:
![fsharp - vscode - project parsing failed](https://user-images.githubusercontent.com/610307/52466769-5ae13500-2bbe-11e9-8720-f7e02e9bdb4d.png)

**Clicking on "Show status" revealed this message**:

> Error:
> MSBuild failed with exitCode 1 Working Directory: '/home/bytesource/Downloads/fsharp testing/projects/HelloWorld' Exe Path: 'dotnet' Args: 'msbuild "/home/bytesource/Downloads/fsharp testing/projects/HelloWorld/HelloWorld.fsproj" /p:SkipCompilerExecution=true /p:ProvideCommandLineArgs=true /p:CopyBuildOutputToOutputDirectory=false /p:UseCommonOutputDirectory=true /t:_Inspect_FscArgs /p:_Inspect_FscArgs_OutFile=/tmp/tmptsoYDJ.tmp.FscArgs.txt /p:DesignTimeBuild=true /t:_Inspect_GetResolvedProjectReferences /p:_Inspect_GetResolvedProjectReferences_OutFile=/tmp/tmpSSqgxd.tmp.GetResolvedProjectReferences.txt /t:_Inspect_GetProperties /p:_Inspect_GetProperties_OutFile=/tmp/tmpJ9AAqH.tmp.GetProperties.txt /nologo /verbosity:quiet' Log: /home/bytesource/Downloads/fsharp testing/projects/HelloWorld/HelloWorld.fsproj(11,3): error MSB4019: The imported project "/home/bytesource/Downloads/fsharp testing/projects/Paket.Restore.targets" was not found. Confirm that the path in the declaration is correct, and that the file exists on disk.

**This is the output from the Developers Tools console**:

> [Extension Host] [IONIDE-FSAC] Project loading failed, MSBuild failed with exitCode 1 Working Directory: '/home/bytesource/Downloads/fsharp testing/projects/HelloWorld' Exe Path: 'dotnet' Args: 'msbuild "/home/bytesource/Downloads/fsharp testing/projects/HelloWorld/HelloWorld.fsproj" /p:SkipCompilerExecution=true /p:ProvideCommandLineArgs=true /p:CopyBuildOutputToOutputDirectory=false /p:UseCommonOutputDirectory=true /t:_Inspect_FscArgs /p:_Inspect_FscArgs_OutFile=/tmp/tmpID0a58.tmp.FscArgs.txt /p:DesignTimeBuild=true /t:_Inspect_GetResolvedProjectReferences /p:_Inspect_GetResolvedProjectReferences_OutFile=/tmp/tmpFw5d0R.tmp.GetResolvedProjectReferences.txt /t:_Inspect_GetProperties /p:_Inspect_GetProperties_OutFile=/tmp/tmpy3kjVA.tmp.GetProperties.txt /nologo /verbosity:quiet'
> Log: 
> /usr/share/dotnet/sdk/2.1.503/Microsoft.Common.CurrentVersion.targets(1179,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.6.1" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/bytesource/Downloads/fsharp testing/projects/HelloWorld/HelloWorld.fsproj]
> 
>  '/home/bytesource/Downloads/fsharp testing/projects/HelloWorld/HelloWorld.fsproj'
> t.log @ workbench.main.js:sourcemap:287
> workbench.main.js:sourcemap:2560 Project parsing failed: HelloWorld.fsproj
> t.onDidNotificationChange @ workbench.main.js:sourcemap:2560

`Paket.Restore.targets` was indeed missing from the root folder, but I found the file in the `.paket` folder instead. So I copied `Paket.Restore.targets` to the root folder, but this didn't work either:

**After moving `Paket.Restore.targets` from `.paket` to root folder**:

> Error:
> MSBuild failed with exitCode 1 Working Directory: '/home/bytesource/Downloads/fsharp testing/projects/HelloWorld' Exe Path: 'dotnet' Args: 'msbuild "/home/bytesource/Downloads/fsharp testing/projects/HelloWorld/HelloWorld.fsproj" /p:SkipCompilerExecution=true /p:ProvideCommandLineArgs=true /p:CopyBuildOutputToOutputDirectory=false /p:UseCommonOutputDirectory=true /t:_Inspect_FscArgs /p:_Inspect_FscArgs_OutFile=/tmp/tmpkPjyFV.tmp.FscArgs.txt /p:DesignTimeBuild=true /t:_Inspect_GetResolvedProjectReferences /p:_Inspect_GetResolvedProjectReferences_OutFile=/tmp/tmp1jvKQK.tmp.GetResolvedProjectReferences.txt /t:_Inspect_GetProperties /p:_Inspect_GetProperties_OutFile=/tmp/tmpveiZ1z.tmp.GetProperties.txt /nologo /verbosity:quiet' Log: /usr/share/dotnet/sdk/2.1.503/Microsoft.Common.CurrentVersion.targets(1179,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.6.1" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/bytesource/Downloads/fsharp testing/projects/HelloWorld/HelloWorld.fsproj]

**Again, the output of the Developer Tools console**:

> Project parsing failed: HelloWorld.fsproj
> t.onDidNotificationChange	@	workbench.main.js:sourcemap:2560
> workbench.main.js:sourcemap:287 [Extension Host] Startup took: 1912.000000 ms
> workbench.main.js:sourcemap:3362 Extension Host
> workbench.main.js:sourcemap:3362 [IONIDE-FSAC] WebSocket message: '{"Kind":"error","Data":{"Code":101,"Message":"MSBuild failed with exitCode 1 Working Directory: '/home/bytesource/Downloads/fsharp testing/projects/HelloWorld' Exe Path: 'dotnet' Args: 'msbuild \"/home/bytesource/Downloads/fsharp testing/projects/HelloWorld/HelloWorld.fsproj\" /p:SkipCompilerExecution=true /p:ProvideCommandLineArgs=true /p:CopyBuildOutputToOutputDirectory=false /p:UseCommonOutputDirectory=true /t:_Inspect_FscArgs /p:_Inspect_FscArgs_OutFile=/tmp/tmp7rZxKC.tmp.FscArgs.txt /p:DesignTimeBuild=true /t:_Inspect_GetResolvedProjectReferences /p:_Inspect_GetResolvedProjectReferences_OutFile=/tmp/tmpczN7Gd.tmp.GetResolvedProjectReferences.txt /t:_Inspect_GetProperties /p:_Inspect_GetProperties_OutFile=/tmp/tmpOrGgFO.tmp.GetProperties.txt /nologo /verbosity:quiet'\nLog: \n/usr/share/dotnet/sdk/2.1.503/Microsoft.Common.CurrentVersion.targets(1179,5): error MSB3644: The reference assemblies for framework \".NETFramework,Version=v4.6.1\" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/home/bytesource/Downloads/fsharp testing/projects/HelloWorld/HelloWorld.fsproj]\n\n","AdditionalData":{"Project":"/home/bytesource/Downloads/fsharp testing/projects/HelloWorld/HelloWorld.fsproj"}}}'
> [IONIDE-FSAC] WebSocket message: '{"Kind":"workspaceLoad","Data":{"Status":"finished"}}'
> [IONIDE-FSAC] RES (003) <- {workspaceLoad} in 918 ms: Kind={"workspaceLoad"}
> Data={ Status: 'finished' }

**Some more information**:

> bytesource@127:~$ dotnet --info
> .NET Core SDK (reflecting any global.json):
>  Version:   2.1.503
>  Commit:    4c506e0f35
> 
> Runtime Environment:
>  OS Name:     ubuntu
>  OS Version:  18.04
>  OS Platform: Linux
>  RID:         ubuntu.18.04-x64
>  Base Path:   /usr/share/dotnet/sdk/2.1.503/
> 
> Host (useful for support):
>   Version: 2.1.7
>   Commit:  cca5d72d48
> 
> .NET Core SDKs installed:
>   2.1.503 [/usr/share/dotnet/sdk]
> 
> .NET Core runtimes installed:
>   Microsoft.AspNetCore.All 2.1.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
>   Microsoft.AspNetCore.App 2.1.7 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 2.1.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
> 
> To install additional .NET Core runtimes or SDKs:
>   https://aka.ms/dotnet-download
> bytesource@127:~$ mono --version
> Mono JIT compiler version 5.18.0.240 (tarball Wed Jan 16 09:10:16 UTC 2019)
> Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
>         TLS:           __thread
>         SIGSEGV:       altstack
>         Notifications: epoll
>         Architecture:  amd64
>         Disabled:      none
>         Misc:          softdebug 
>         Interpreter:   yes
>         LLVM:          yes(600)
>         Suspend:       preemptive
>         GC:            sgen (concurrent by default)

I found other issues referencing the "Paket.Restore.targets" was not found" error, but no solutions, so I thought I'd rather describe my issue here again. 

Please note that I don't now anything about how a F# project is built on Linux (I'm just starting out). So if this issue is due to an obvious error on my site, I still hope you can find the time explaining it to me. 

Stefan

PS. I made the necessary settings to

**Comment by bytesource** [comment] 2019-02-08 08:52
I'd like to add that I also selected "netcore" in this setting:
![fsharp - vscode - netcore runtime chosen](https://user-images.githubusercontent.com/610307/52467846-c8db2b80-2bc1-11e9-8e67-e4e1c96aaf22.png)

**Comment by MangelMaxime** [comment] 2019-02-08 10:31
If you run `dotnet build [path/to/your/fsproj]` do you have an error?

Also, in general `paket` is adding the the correct path to `Paket.Restore.targets` itself. Can you try delete the lines about `Paket.Restore.targets` in your fsproj and removing you the `Paket.Restore.targets` you put in the root foolder and in the `.paket` folder.

Then run `mono .paket/paket.exe restore`. Paket should set up the files and path for you now.

**Comment by inosik** [comment] 2019-02-08 11:48
The second error is a duplicate of #1001.

The first error looks like Forge didn't generate the project file correctly. `Paket.Restore.targets` was in a `.paket/` directory, while the project tried to import it from the root directory.

**Comment by bytesource** [comment] 2019-02-08 13:59
Thanks for your replies. This is what I did:

1) Copied `Paket.Restore.targets` from `.paket/` to the root folder to get rid of the first error. Just moving the file from `.paket/` to root did not work because I then would get an error that `Paket.Restore.targets` was missing from `.paket/`.

2) Followed the instructions from [this comment](https://github.com/ionide/ionide-vscode-fsharp/issues/1001#issuecomment-460099633) from issue #1001:

- Downloaded the file [netfx.props](https://github.com/fsprojects/FSharp.TypeProviders.SDK/blob/master/netfx.props) and copied it to my project's root folder. 
- Added the following line to my project's `.fsproj` file:
`<Import Project="..\netfx.props" />`

After this change, the project loaded without any errors!

By the way, this is how my `.fsproj` file looks like now:
```
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net461</TargetFramework>
    <DebugType>portable</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="HelloWorld.fs" />
    <None Include="Script.fsx" />
  </ItemGroup>
  <Import Project="..\.paket\Paket.Restore.targets" />
  <Import Project="..\netfx.props" />
</Project>
```
I'm happy that everything is working now, but I'd still like to ask these questions:

1. `Paket.Restore.targets`: What is the issue here? Is the import statement incorrect (as it's looking for the file in root instead of `.paket/`) or does the file have to be in root but is missing?
2. From the comments in issue #1001 I got the impression that the issue with the missing `netfx.props` cannot be fixed (at least not on Linux), so that we have to include this file manually in every new project. Is that correct?

Thank you very much for your help!

Stefan

**Comment by inosik** [comment] 2019-02-08 15:08
1. `Paket.Restore.targets` is usually located in the `.paket/` directory at the repository root. Take a look at any F# project and you'll recognize the pattern. You have to import that file in your project in order to make `dotnet restore` work with Paket.

2. It depends on what framework you want to target: .NET Core (for apps) and .NET Standard (for libraries) or .NET Framework/Mono. If you're just starting or playing around, I'd recommend to start with .NET Core and the templates provided by `dotnet new`.

**Comment by bytesource** [comment] 2019-02-09 03:53
Thanks for your explanation!

Regarding your second answer, do you recommend running `dotnet new` from the terminal instead of using `F#: New Project` in VS Code?

**Comment by vilinski** [comment] 2019-02-09 08:41
nothing agains ionide, but it's templates are fast outdate. `dotnet new` is fully ok, and you can also install and update other dotnet templates separately. 
https://github.com/dotnet/templating/wiki/Available-templates-for-dotnet-new

**Comment by Krzysztof-Cieslak** [comment] 2019-02-09 09:58
In general, the plan is to replace current Forge scaffolding (`F#: New Project`) with the `dotnet new` templates anyway.

**Comment by bytesource** [comment] 2019-02-09 14:07
That's good to know. Thanks a lot for your help!

**Closed** 2019-03-15 10:58 UTC
Labels: forge
