### ISSUE TITLE
Untyped quotation operator autocompletion not working

### ISSUE THREAD

**Issue by PekkaLehtonen** [ionide/ionide-vscode-fsharp#1091] opened 2019-05-07 05:46 UTC
Steps to reproduce the behaviour:
When I type `<@@` while edititing a .fsx file

I expect to get `<@@@@>` with my cursor between the operators

Instead I get
<@@@@>@> 

Windows 10
VS code 1.33.1

Name: Ionide-fsharp
Id: ionide.ionide-fsharp
Description: F# Language Support
Version: 3.36.1
Publisher: Ionide
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=Ionide.Ionide-fsharp

**Comment by isaacabraham** [comment] 2019-05-13 19:20
This is the same for [{}] as well. I ended up turning off the auto complete for this stuff because it was too annoying.

**Comment by Krzysztof-Cieslak** [comment] 2019-05-13 19:52
I actually think it's a bug in VSCode - it seems their bracket autocomplete system was not build with mulitcharacter brackets in mind. 

I'll try to reproduce on simple extension, and investigate what's wrong in Code.

**Comment by drk-mtr** [comment] 2019-05-23 12:03
I found the same as Isaac and ended up hacking `language-configuration.json` on one PC to get around this. With the hacks it worked well for me, however I didn't want to submit a PR in case it breaks things for other people (I'm very new to dev generally).

**Comment by misterspeedy** [comment] 2020-06-15 14:38
Thanks for looking at the duplicate @Krzysztof-Cieslak - and sorry for the duplication!  Have we looked VS Code's issue list to see if it's on theirs?  If not I'm happy to do so.

**Comment by misterspeedy** [comment] 2020-06-15 15:27
Ah, there she blows:

https://github.com/microsoft/vscode/issues/72177

In short, it's on the VS Code feature backlog.

**Comment by olivercoad** [comment] 2020-11-17 01:19
The fix for this is merged and in the VS Code insiders build.

Previously:  
![autoClosingPairs vscode v1.51.1](https://user-images.githubusercontent.com/24837994/99327741-b467af00-28ce-11eb-9b71-1eadee5edfee.gif)

Now:  
![autoClosingPairs vscode v1.52.0-insider](https://user-images.githubusercontent.com/24837994/99327755-bb8ebd00-28ce-11eb-8259-0b35c5fe12e3.gif)

**Comment by baronfel** [comment] 2020-11-17 01:24
Thanks for reporting back, that's exciting news!

**Comment by Krzysztof-Cieslak** [comment] 2020-11-17 11:14
Well, I guess I can close it here.

**Closed by Krzysztof-Cieslak** 2020-11-17 11:14 UTC
Labels: bug, upstream - vscode issue
