### ISSUE TITLE
[experimental-sharp] First install (without open solution or folder)

### ISSUE THREAD

**Issue by sergey-tihon** [ionide/ionide-vscode-fsharp#1142] opened 2019-06-18 04:58 UTC
**Describe the bug**
error during first install of `experimental-sharp`

> System.UnauthorizedAccessException: Access to the path '/.ionide' is denied. ---> System.IO.IOException: Permission denied --- End of inner exception stack trace --- at System.IO.FileSystem.CreateDirectory(String fullPath) at System.IO.Directory.CreateDirectory(String path) at SymbolCache.PersistenCacheImpl.initializeCache(String dir) in D:\Programowanie\Projekty\Ionide\FsAutoComplete\src\FsAutoComplete.Core\SymbolCache.fs:line 89 at FsAutoComplete.Commands.StartBackgroundService(String workspaceDir) in D:\Programowanie\Projekty\Ionide\FsAutoComplete\src\FsAutoComplete.Core\Commands.fs:line 1101 at FsAutoComplete.Lsp.Initialize@262.Invoke(Unit unitVar) in D:\Programowanie\Projekty\Ionide\FsAutoComplete\src\FsAutoComplete\FsAutoComplete.Lsp.fs:line 265 at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)

**To Reproduce**
Steps to reproduce the behaviour:
1. Open VS Code (without solution or directory)
2. Disable `Ionide-fsharp`
3. Install `experimental-sharp`

**Expected behaviour**
Silent successful installation

**Screenshots**
<img width="478" alt="Extension__experimental-fsharp" src="https://user-images.githubusercontent.com/1197905/59654364-8abccc80-919e-11e9-8ae0-c544b792f320.png">

**Environment (please complete the following information):**
 - OS: macOS
 - Ionide version:  experimental-sharp 0.3.5
 - VSCode version: May 2019 (version 1.35)
 - dotnet SDK version: 2.2.103
 - mono / .Net Framework version: Mono 5.18.1.28

**Comment by Krzysztof-Cieslak** [comment] 2019-06-18 10:06
It seems it's duplicate of #1138

**Closed by Krzysztof-Cieslak** 2019-06-18 10:06 UTC
Labels: backer
