### ISSUE TITLE
Wrong .NET framework

### ISSUE THREAD

**Issue by banditpig** [ionide/ionide-vscode-fsharp#978] opened 2018-12-11 20:13 UTC
Create a new F# project using command palette -> F# new project -> classlib
The project gets created fine and it all works...

Close VSCode. Start VSCode again and select the project just created.
The project loads but everytime a change is made the following error appears:

Status: failed to load

Error:
MSBuild failed with exitCode 1 Working Directory: '/Users/mikehoughton/AoC2018F/AoC/AoC' Exe Path: 'dotnet' Args: 'msbuild /Users/mikehoughton/AoC2018F/AoC/AoC/AoC.fsproj /p:SkipCompilerExecution=true /p:ProvideCommandLineArgs=true /p:CopyBuildOutputToOutputDirectory=false /p:UseCommonOutputDirectory=true /t:_Inspect_FscArgs /p:_Inspect_FscArgs_OutFile=/var/folders/qs/fbd6k9mj60nbr6sv72pm1jpc0000gn/T/tmpkxVwqb.tmp.FscArgs.txt /p:DesignTimeBuild=true /t:_Inspect_GetResolvedProjectReferences /p:_Inspect_GetResolvedProjectReferences_OutFile=/var/folders/qs/fbd6k9mj60nbr6sv72pm1jpc0000gn/T/tmpp1VKTv.tmp.GetResolvedProjectReferences.txt /t:_Inspect_GetProperties /p:_Inspect_GetProperties_OutFile=/var/folders/qs/fbd6k9mj60nbr6sv72pm1jpc0000gn/T/tmpvSTSxS.tmp.GetProperties.txt /nologo /verbosity:quiet' Log: /usr/local/share/dotnet/sdk/2.2.100/Microsoft.Common.CurrentVersion.targets(1179,5): error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.6.1" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend. [/Users/mikehoughton/AoC2018F/AoC/AoC/AoC.fsproj]

I'm running MacOS Mojave 10.14.

Running dotnet --info gives 

.NET Core SDK (reflecting any global.json):
 Version:   2.2.100
 Commit:    51868761f2

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.100/

Host (useful for support):
  Version: 2.2.0
  Commit:  1249f08fed

.NET Core SDKs installed:
  2.0.0 [/usr/local/share/dotnet/sdk]
  2.1.4 [/usr/local/share/dotnet/sdk]
  2.1.302 [/usr/local/share/dotnet/sdk]
  2.1.500 [/usr/local/share/dotnet/sdk]
  2.2.100 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

**Comment by Krzysztof-Cieslak** [comment] 2019-03-15 11:13
Duplicate of #1001

**Closed by Krzysztof-Cieslak** 2019-03-15 11:13 UTC
