### ISSUE TITLE
F12 reference not working withing the same fsx file

### ISSUE THREAD

**Issue by vmendivil** [ionide/ionide-vscode-fsharp#1179] opened 2019-07-12 19:08 UTC
**Describe the bug**
F12 is not working if the reference is within the same fsx file.

**To Reproduce**
Press F12 on any fsx file that makes reference to a function that is within the same file.

If you press F12 in a .net type, for example the "string" definition, it will properly open the correct reference and show me the definition of the type.

**Expected behavior**
F12 should take me to the correct reference within the same file. Note that, in the error message, is adding/starting with "c:\c:\", the rest of the path is correct.

**Screenshots**
![Erros Msg](https://user-images.githubusercontent.com/20627825/61152029-5eeae900-a4b5-11e9-8d68-7db64dbd3efd.PNG)

**Environment (please complete the following information):**
 - OS: Win 10
 - Ionide version: 4.0.5
 - VSCode version: 1.36.1
 - mono / .Net Framework version: 4.7.2

**Additional notes**
I also noted that LenseCode is not working, not sure if the issue is related or not:

Setup:
![Code Lens](https://user-images.githubusercontent.com/20627825/61152423-6232a480-a4b6-11e9-955b-3d6e5a2d7fbe.PNG)

Missing Signature in functions/values:
![Missing signature](https://user-images.githubusercontent.com/20627825/61152431-6c54a300-a4b6-11e9-9092-c6b64ea2fd86.PNG)

**Comment by baronfel** [comment] 2019-07-12 19:19
This is a duplicate of #1177, which is being worked on.

**Closed** 2019-07-12 19:35 UTC
