### ISSUE TITLE
F# Language Server crashed 5 times in the last 3 minutes

### ISSUE THREAD

**Issue by aolney** [ionide/ionide-vscode-fsharp#1477] opened 2021-01-09 18:07 UTC
### Describe the bug**

F# Language Server crashed 5 times in the last 3 minutes

### Steps to reproduce

On startup

### Link to sample reproduction

https://github.com/fable-compiler/fable2-samples/tree/master/minimal

### Expected behaviour

Not crashing

## Machine info
 - OS: Ubuntu 20.04.1 LTS
 - .NET SDK version: 3.1.302
 - Ionide version: 5.1.0
 - 
### Additional context

Found this issue: https://github.com/fsprojects/fsharp-language-server/issues/43

Resolved by installing Ionide 4.17 [from VSIX](https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix)

**Comment by baronfel** [comment] 2021-01-09 18:16
As noted in the Release Notes for Ionide 5.0 and up, .Net 5 is required. Otherwise yes, you'll see this. Closing as designed.

**Comment by baronfel** [comment] 2021-01-09 18:17
Also, please note that `fsprojects/fsharp-language-server` is a completely separate LSP implementation from Ionide, and it's very unlikely that issues raised in that repo have a direct correlation or relevance to this project as a result.

**Closed by baronfel** 2021-01-09 18:16 UTC

**Comment by OriginatorStar** [comment] 2022-04-24 00:32
> As noted in the Release Notes for Ionide 5.0 and up, .Net 5 is required. Otherwise yes, you'll see this. Closing as designed.

You should not close this, since your argument is invalid. I have enabled .net core 5.0.100 with a global.json file, the version 5 is active and still see the same error.

**Comment by daz10000** [comment] 2022-04-24 20:08
Just a comment since I ran into this just now.  The ionide error reporting for wrong dotnet sdk versions seems to be a little fragile and misleading.   I have a `global.json` file with an older version of the sdk mentioned (6.0.101) and had a newer version installed (6.0.202).  It worked fine when I fixed the global.json file, but the traces in the F# logs are a bit confusing.  The first line is right - there isn't a compatible version installed (compatible with global.json).  The rest of the messages are a little chaotic.  `The application --version does not exist` ??    ` Unable to parse sdk version from the string '        6.0.202 [C:\Program Files\dotnet\sdk]'`  -  might be hard to do, but the information is there to give the user a simple message - project asks for 6.0.101 and it's not installed.  You appear to have `6.0.202` installed.  This is with the F# console opened.  Without that, you just hear that the F# server crashed 5 times in the last 3 minutes - which isn't a wonderful experience for a novice.


```
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application '--version' does not exist.
  * You intended to execute a .NET SDK command:
      A compatible installed .NET SDK for global.json version [6.0.101] from [c:\extproj\Plough.WebApi\global.json] was not found.
      Install the [6.0.101] .NET SDK or update [c:\extproj\Plough.WebApi\global.json] with an installed .NET SDK:
Unhandled exception: System.Exception: Unable to parse sdk version from the string '        6.0.202 [C:\Program Files\dotnet\sdk]'. This value came from running `C:\Program Files\dotnet\dotnet.exe [--version]` at path c:\extproj\Plough.WebApi\src\Plough.WebApi.Client.Dotnet
```

**Comment by baronfel** [comment] 2022-04-24 20:10
Ah gotcha - since we're invoking 'dotnet --version' to check versions, if that dotnet can't be invoked by the SDK itself we need to be able to handle that. Makes sense to me.

**Comment by daz10000** [comment] 2022-04-24 20:19
Exactly,

## With wrong global.json (set tp 6.0.101 vs installed 6..0.202)
```
$ dotnet --version
Could not execute because the application was not found or a compatible .NET SDK is not installed.
Possible reasons for this include:
  * You intended to execute a .NET program:
      The application '--version' does not exist.
  * You intended to execute a .NET SDK command:
      A compatible installed .NET SDK for global.json version [6.0.101] from [C:\extproj\Plough.WebApi\global.json] was not found.
      Install the [6.0.101] .NET SDK or update [C:\extproj\Plough.WebApi\global.json] with an installed .NET SDK:
        6.0.202 [C:\Program Files\dotnet\sdk]
```

## Once global.json is edited to match installed version of sdk

```
$ dotnet --version
6.0.202
```
So you'd have to parse that helpful but messy error message to give the GUI user a clue about what's happening.

**Comment by OriginatorStar** [comment] 2022-04-24 23:13
> Just a comment since I ran into this just now. The ionide error reporting for wrong dotnet sdk versions seems to be a little fragile and misleading. I have a `global.json` file with an older version of the sdk mentioned (6.0.101) and had a newer version installed (6.0.202). It worked fine when I fixed the global.json file, but the traces in the F# logs are a bit confusing. The first line is right - there isn't a compatible version installed (compatible with global.json). The rest of the messages are a little chaotic. `The application --version does not exist` ?? ` Unable to parse sdk version from the string ' 6.0.202 [C:\Program Files\dotnet\sdk]'` - might be hard to do, but the information is there to give the user a simple message - project asks for 6.0.101 and it's not installed. You appear to have `6.0.202` installed. This is with the F# console opened. Without that, you just hear that the F# server crashed 5 times in the last 3 minutes - which isn't a wonderful experience for a novice.
> 
> ```
> Could not execute because the application was not found or a compatible .NET SDK is not installed.
> Possible reasons for this include:
>   * You intended to execute a .NET program:
>       The application '--version' does not exist.
>   * You intended to execute a .NET SDK command:
>       A compatible installed .NET SDK for global.json version [6.0.101] from [c:\extproj\Plough.WebApi\global.json] was not found.
>       Install the [6.0.101] .NET SDK or update [c:\extproj\Plough.WebApi\global.json] with an installed .NET SDK:
> Unhandled exception: System.Exception: Unable to parse sdk version from the string '        6.0.202 [C:\Program Files\dotnet\sdk]'. This value came from running `C:\Program Files\dotnet\dotnet.exe [--version]` at path c:\extproj\Plough.WebApi\src\Plough.WebApi.Client.Dotnet
> ```

I don't think this is my case. I have installed and active the version set up in the global.json.

What I get from the F# output is a reference to a folder path that ionide seems to send, and it breaks it:

`Unhandled exception: System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'c:\repos\fs\FirstIonideProject\dotnet' with working directory 'c:\repos\fs\FirstIonideProject'. The system cannot find the file specified.`

That dotnet folder is not created by default when scaffolding a F# project. To me ionide seems to be failing to look for the dotnet.exe ?

Give me some clues please on where should I look to correct this. I've checked my system path env var, and the first thing there is the path to dotnet sdk.

**Comment by toburger** [comment] 2022-05-17 13:43
Seems my problem was caused by a wrong environment variable:

Wrong:
![image](https://user-images.githubusercontent.com/728782/168825080-f25921ba-96c0-4341-bf47-831d017d0288.png)

Correct:
![image](https://user-images.githubusercontent.com/728782/168825121-d8adcff9-68cb-4d1f-b4d1-af54a6f1bc7f.png)
