### ISSUE TITLE
UTF8 in F# interactive

### ISSUE THREAD

**Issue by haf** [ionide/ionide-vscode-fsharp#290] opened 2016-11-22 20:09 UTC
<img width="588" alt="screen shot 2016-11-22 at 21 07 28" src="https://cloud.githubusercontent.com/assets/193115/20540069/d90c6fce-b0f7-11e6-990b-44bdf7772519.png">

It would seem that writing µ in the text works, it echoes badly but then the result prints nicely. See screenshot.

**Comment by rmunn** [comment] 2016-11-25 09:00
Interesting. I just tried that on Ubuntu 14.04, with a UTF-8 locale and a terminal that has no trouble printing UTF-8, and I got the same results:

![Ubuntu 14.04 reproduction](https://cloud.githubusercontent.com/assets/90762/20619447/3106ecbe-b327-11e6-8be4-25674c6dc576.png)

Notice that the µ showed up just fine in the first line of the terminal output: this was the first line I hit Alt+Enter on after starting up this VS Code window, so it hadn't started F# Interactive yet.

I then did the following in a GNOME Terminal window, with `$LANG` set to `en_US.UTF-8`:

```
rmunn@rmunn-ubuntu-gnome-14:~/Downloads$ echo µs
µs
rmunn@rmunn-ubuntu-gnome-14:~/Downloads$ fsharpi

F# Interactive for F# 4.0 (Open Source Edition)
Freely distributed under the Apache 2.0 Open Source License

For help type #help;;

> let waitTime= 500000 // 500000 �s = 0.5 seconds
- ;;

val waitTime : int = 500000

> printfn "500000 �s = 0.5 seconds" ;;
500000 �s = 0.5 seconds
val it : unit = ()
```

Note that I typed in the µ character each time. When you're seeing � in the F# Interactive window, that's because that is what showed up when I typed µ on my keyboard.

I suspect that something in F# Interactive is at fault, but I haven't figured out what it might be. If it was defaulting to expecting UTF-16, I would have expected to see either 습 (U+C2B5 HANGUL SYLLABLE SEUB) or 뗂 (U+B5C2 HANGUL SYLLABLE DDENH), since the UTF-8 representation of µ is `0xc2 0xb5`. But it produced neither; it produced � (U+FFFD REPLACEMENT CHARACTER).

I'm not sure how to test this further, but what I've found so far suggests this may be a bug that should be filed against F# Interactive.

**Comment by cloudRoutine** [comment] 2016-12-10 08:07
![](http://i.imgur.com/LrM7bPo.png)

At first I thought `--utf8output` might be the solution, but it doesn't seem like that matters. Based on this quick experiment I'm not so sure that fsi is at fault. This might be a vscode issue.

**Comment by rojepp** [comment] 2017-01-05 14:10
I can not reproduce with v2.18.1. Tried on Windows 10 and Mac OS.

<img width="330" alt="screenshot 2017-01-05 15 10 03" src="https://cloud.githubusercontent.com/assets/445888/21683308/1411c6e0-d359-11e6-8935-1bdd18da0dd8.png">

**Comment by aliozgur** [comment] 2017-01-09 10:10
Same on Mac OSX. Code 1.8.1, Ionide-fsharp 2.18.2
<img width="830" alt="capturfiles-20170109_011020" src="https://cloud.githubusercontent.com/assets/799194/21763073/0cf07160-d66d-11e6-9523-681654bfd274.png">

**Comment by rmunn** [comment] 2017-01-10 10:15
Code 1.8.1, Ionide-fsharp 2.19.0, F# 4.0, on Ubuntu 14.04:

![screenshot from 2017-01-10 17 04 26](https://cloud.githubusercontent.com/assets/90762/21802122/20ccd5a8-d757-11e6-9b3e-3e4b972cb5dd.png)

That's with an explicitly-opened VS Code terminal session, where I ran `fsharpi` by hand. But the same thing happened in the F# Interactive window that Ionide automatically opened when I evaluated the `printfn` line with Alt+Enter. Whether I evaled the line, or typed the µ character in by hand, I always got �. BUT when I did `#load "trythis.fsx"`, the same F# session printed µ quite happily.

It doesn't seem to be a VS Code bug, since a VS Code-opened terminal let me type µ without complaints. It does seem to be an F# Interactive bug of some kind, since I could `#load` a UTF-8 file but not type the same characters into F# Interactive.

I've also reproduced this on Mint 18 (based on Ubuntu 16.04). But when I tested on Windows 10 (with the same VS Code and Ionide-fsharp versions, but with F# Interactive version 14.0.23413.0, which I *think* is F# 4.0), I couldn't reproduce the problem, so I'm not 100% certain that it's an F# Interactive bug.

This is proving hard to narrow down to a single cause...

**Comment by rmunn** [comment] 2017-01-11 02:58
Looks like this issue only affects characters between U+0080 and U+00FF: sending `printfn "üýþÿĀāĂă"` to F# Interactive produces `����ĀāĂă` in the output.

![screenshot from 2017-01-11 09 57 06](https://cloud.githubusercontent.com/assets/90762/21833392/775d59a0-d7e4-11e6-8244-a711e5550abd.png)

I've opened https://github.com/fsharp/fsharp/issues/654 to track this issue, since it seems to be caused there rather than in Ionide.

**Comment by Krzysztof-Cieslak** [comment] 2017-02-02 20:59
Closing this one, follow https://github.com/fsharp/fsharp/issues/654 for further information

**Closed by Krzysztof-Cieslak** 2017-02-02 20:59 UTC
Labels: bug

**Comment by haf** [comment] 2017-03-13 18:04
Can you test this PR? https://github.com/Microsoft/visualfsharp/pull/2582
