### ISSUE TITLE
Warning MSB3270: architecture mismatch: project being built as "MSIL", but referenced mscorlib.dll was built as "AMD64"

### ISSUE THREAD

**Issue by lilred** [ionide/ionide-vscode-fsharp#334] opened 2017-01-13 15:54 UTC
* Windows 7 SP1, x64
* Visual Studio Code 1.8.1
* `ionide-fsharp` 2.19.1
* .NET version: Registry key `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full` has entries `TargetVersion` with value `4.0.0`, `Version` with value `4.6.01590` (should correspond to the 4.6.2 release)

Error message code is `MSB3270`, with text:

    warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "mscorlib.dll", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.

Any ideas?

**Comment by Krzysztof-Cieslak** [comment] 2017-01-15 12:54
Duplicate of #289

**Closed by Krzysztof-Cieslak** 2017-01-15 12:54 UTC
