### ISSUE TITLE
FSI window does not auto-scroll

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#360] opened 2017-02-10 08:35 UTC
In the latest Code (1.9.x), FSI does not autoscroll down as new text is sent to the window.

**Comment by CompleteBrains** [comment] 2017-02-14 08:59
I have it too. 
Recently in `VSCode` was added a feature that disables `autoscroll` when user has scrolled terminal window up.
But even if I don't touch terminal window, the `autoscroll` becomes disabled at some point. 
Probably the reason is that `Ionide` logs to the terminal this info every time I switch tabs:
```
> # silentCd @"c:\Projects\Fleet (F#)\Domain";;
- # 1 @"c:\Projects\Fleet (F#)\Domain\Run.fs"
```
But I can't reproduce this each time, only occasionally.

My workaround was to assign a shortcut for scrolling to the end quickly:
```
        "key": "ctrl+numpad2",
        "command": "workbench.action.terminal.scrollToBottom"
```

**Comment by Krzysztof-Cieslak** [comment] 2017-02-14 16:51
Cc: @Tyriar

Anything I should know about scroll behaviour?

**Comment by Tyriar** [comment] 2017-02-15 22:51
Might be related to this https://github.com/Microsoft/vscode/issues/20505?

If you can get some reliable repro steps and check if the scrollbar exists that would be useful.

**Comment by Krzysztof-Cieslak** [comment] 2017-02-24 18:41
OK, closing as it's probably issue on VSCode side

**Closed by Krzysztof-Cieslak** 2017-02-24 18:41 UTC
Labels: upstream - vscode issue

**Comment by Rhywun** [comment] 2017-04-16 00:36
Is there any way to **not** display the "silent" stuff that appears every time I load the FSI and switch tabs? It's not very silent when it's cluttering up the terminal window :)
