### ISSUE TITLE
Error opening module in same folder/project (F# 4.1 issue?)

### ISSUE THREAD

**Issue by akaegi** [ionide/ionide-vscode-fsharp#357] opened 2017-02-07 07:53 UTC
Ionide cannot open module (same folder, correct build order) even though compilation through build.cmd works fine. Ionide says: 
> 'The namespace or module 'Cards' is not defined'

I just do 
```f#
module Game
open Cards
```
in module "Game" using module "Cards".

Maybe it has to do with VS 2017 RC build tools?

Environment:
* VS 2017 RC
* 4.1 F# SDK
* Windows 10 64-bit

Code:
https://github.com/akaegi/UnoWS

**Comment by Krzysztof-Cieslak** [comment] 2017-02-14 15:32
I guess its duplicate of https://github.com/ionide/ionide-vscode-fsharp/issues/291

**Closed by Krzysztof-Cieslak** 2017-02-14 15:32 UTC

**Comment by akaegi** [comment] 2017-02-20 12:26
No, i don't think it is a duplicate. I only have one simple project without any (special) dependencies on other projects or libraries. 
If you could hint me at how to enable some debugging output, then I could maybe give some more information or find the cause of the problem.
