### ISSUE TITLE
F# interactive do not accept more than 1357 characters

### ISSUE THREAD

**Issue by adicirstei** [ionide/ionide-vscode-fsharp#199] opened 2016-10-12 11:05 UTC
F# interactive do not accept more than 1357 characters. Neither by `Fsi: Send File` neither by `Fsi: Send Selection` 

In the gif bellow, you can see that the text is sent to fsi when selection is 1357 chars and if I select one more char, nothing happens.

![fsi](https://cloud.githubusercontent.com/assets/1694688/19307700/8a417a80-9084-11e6-9315-a9f2ce694acb.gif)

**Comment by Krzysztof-Cieslak** [comment] 2016-10-13 11:52
Looks like it's some problem with VSCode terminal integration. It may be good idea to create issue on VSCode repo.

**Comment by Dalusia** [comment] 2016-11-07 14:31
I'm having the same problem, however I've noticed the limit is not always 1357. The number of lines seems to play a factor, as new lines seem to count for more than the two bytes I would expect.
I.e. lots of small lines will stop working before 1357 bytes, and long lines will continue working and fail somewhat beyond 1357.
Is there any kind of work around for this? Other than having very short scripts :-)

**Comment by Krzysztof-Cieslak** [comment] 2017-01-05 20:56
I guess @Tyriar could help us a bit with that... or at least tell us where to report issue ;)

**Comment by Dalusia** [comment] 2017-01-06 19:41
Hi Tyriar, the text doesn't seem to be processed or sent to the terminal (when over a certain length), as far as I can see.
I don't know if this is relevant, but I have the same issue on two machines, and on both I have Visual Studio 2015 installed. They're otherwise fairly different (e.g. Win 10 vs Win 7).

**Comment by lilred** [comment] 2017-01-23 08:32
Between this and #340, the process for sending code to FSI might be a bit busted!

**Comment by Dalusia** [comment] 2017-01-23 10:30
Thanks Red, I hope it gets some attention... I am always hopeful for new releases of Ionide or VSCode, but so far the problem persists.

**Comment by lilred** [comment] 2017-01-23 17:12
We're teaching a class with F#, and the way we recommend users run their code is via "FSI: Send Selection". We were not aware of this issue or we'd have picked another approach.

**Comment by lilred** [comment] 2017-01-23 17:17
I've just posted a USD $100 bounty [here](https://www.bountysource.com/issues/39030641-f-interactive-do-not-accept-more-than-1357-characters). In our case this is time-critical, but anybody who fixes this in the next six months will get the bounty.

**Comment by Tyriar** [comment] 2017-01-23 18:02
Is this only happening on Windows? I have no issue sending text of lengths greater than 1400 via `Terminal.sendText` on Linux.

**Comment by Tyriar** [comment] 2017-01-23 18:03
Can someone debug the extension and verify the strings are correct in these spots:

- https://github.com/ionide/ionide-vscode-fsharp/blob/4e6b0f9467d2368c16fb5369f36512d5c528749e/src/Components/Fsi.fs#L100
- https://github.com/ionide/ionide-vscode-fsharp/blob/4e6b0f9467d2368c16fb5369f36512d5c528749e/src/Components/Fsi.fs#L77

**Comment by Krzysztof-Cieslak** [comment] 2017-01-24 09:09
I can't reproduce it at all, sending > 5000 chars works without any problem.

Windows 10, VSCode Insiders.

**Comment by Dalusia** [comment] 2017-01-24 10:12
I have this problem on a Windows 7 machine and a Windows 10 machine. One commonality that springs to mind is that both have Visual Studio 2015 Enterprise. Not sure if installed before or after VS Code.

**Comment by elgrego** [comment] 2017-01-24 10:34
I have this problem on Ubuntu 16.10

**Comment by smoothdeveloper** [comment] 2017-01-24 10:35
I can reproduce it on a windows 7 machine.

**Comment by Krzysztof-Cieslak** [comment] 2017-01-24 10:38
Please add VSCode and Ionide versions to error reports.

**Comment by smoothdeveloper** [comment] 2017-01-24 10:45
vscode: 1.8.1
ionide-fsharp: 2.20.0

**Comment by Krzysztof-Cieslak** [comment] 2017-01-24 11:11
Can't reproduce on 1.8.1, Ionide 2.20.0, Windows 10. :-(

**Comment by Dalusia** [comment] 2017-01-24 11:54
VS Code 1.8.1
Ionide-FAKE 1.1.0
Ionide-fsharp 2.9.0
Ionide-Paket 1.3.2

**Comment by lilred** [comment] 2017-01-24 23:06
Dalusia: can you update your ionide-fsharp package and see if this reproduces?

I can't reproduce here, but my setup is unconventional.

* VS Code `1.9.0-insider` (commit `ee9d91c05fa571de56c41383cceee30b05b0a2f6` )
* Windows 10 Pro Insider Preview (build `14986.rs_prerelease.161202-1928`)
* ionide-fsharp 2.13.2

**Comment by Dalusia** [comment] 2017-01-26 10:54
Sure thing Red. Have done & same problem. I can't get anywhere near your test file's length. I cut it down until it would execute, and could only manage 23 of the printfn statements (plus the first and last line).
Do you also have visual studio installed?
Ionide-fsharp at 2.23.0 now.

**Comment by s952163** [comment] 2017-01-26 13:20
On win7, VSCode 1.8.1, ionide-fsharp 2.21.0 still occurs
On win10, VSCode 1.8.1 ionide-fsharp 2.21.0 cannot reproduce
Both have VS2015

**Comment by lilred** [comment] 2017-01-26 14:35
@Dalusia I've updated my comment to reflect that yes, I have Visual Studio installed.

**Comment by Krzysztof-Cieslak** [comment] 2017-01-26 14:44
I don't believe it has anything to do with VS.

But looks like problem is occurring more on Windows 7.

**Comment by lilred** [comment] 2017-01-26 14:47
It might also be happening in Ubuntu!

My working theory is that this is a platform agnostic, possibly
nondeterministic bug in VS Code. If this were the case, could it be worked
around somehow?

**Comment by Tyriar** [comment] 2017-01-26 18:06
On the VS Code end here's how it works:

1. Text is passed through the extension API from the extension process to the renderer process
2. Text is passed to the 'terminalProcess' which is a process whose sole duty is to launch node-pty (to workaround an electron bug) https://github.com/Microsoft/vscode/blob/4a90b5e23bf43312c113f620f8829372ef10cc81/src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#L271
3. terminalProcess sends it to node-pty https://github.com/Microsoft/vscode/blob/4a90b5e23bf43312c113f620f8829372ef10cc81/src/vs/workbench/parts/terminal/electron-browser/terminalProcess.js#L36
4. node-pty gets it and passes it onto the shell process, the behavior here is significantly different on Windows to Mac/Linux so [if it's also happening on Ubuntu](https://github.com/ionide/ionide-vscode-fsharp/issues/199#issuecomment-274766838)) I doubt it's happening at this level

If it is VS Code's issue maybe characters are being dropped over IPC or something?

If anyone who is reproducing could debug into [these lines](https://github.com/ionide/ionide-vscode-fsharp/issues/199#issuecomment-274567303) and check if the text is valid that should indicate whether it's a VS Code issue or not

**Comment by smoothdeveloper** [comment] 2017-01-26 18:10
> If it is VS Code's issue maybe characters are being dropped over IPC or something?

To me it seems like the IPC step isn't reached, otherwise we would see partial input evaluated in FSI

> If anyone who is reproducing could debug into these lines and check if the text is valid that should indicate whether it's a VS Code issue or not

I'm stuck trying to build ionide on a windows 7 so I could step through the code https://github.com/fable-compiler/Fable/issues/346#issuecomment-274931726

I don't know much about fable / vscode so I can't do much without some more guidance.

**Comment by Tyriar** [comment] 2017-01-26 18:13
@smoothdeveloper oh this whole time I thought it was being truncated, it should be easier to find the cause then by debugging the extension and/or vscode.

**Comment by lilred** [comment] 2017-01-26 18:32
Tested on a 16.04.1 Ubuntu install, while the output was [glitchy](https://gist.github.com/lilred/fafa1f674d6a2eab4267649acf641867) (see #340) I didn't reproduce this bug.

**Comment by Krzysztof-Cieslak** [comment] 2017-01-26 19:26
I'll prepare small VSCode plugin written in typescript to try to reproduce it in environment everyone can easily build.

**Comment by Tyriar** [comment] 2017-01-26 19:36
@Krzysztof-Cieslak that would be great thanks

**Comment by Krzysztof-Cieslak** [comment] 2017-01-26 20:14
Here it is: https://github.com/Krzysztof-Cieslak/vscode-fsi-bug

Can you try reproducing bug following instructions in readme?

**Comment by smoothdeveloper** [comment] 2017-01-26 20:48
![vscodeissue](https://cloud.githubusercontent.com/assets/87944/22349553/69bd3698-e410-11e6-9498-30c07f8a1df2.gif)

**Comment by Krzysztof-Cieslak** [comment] 2017-01-26 20:59
Well, at least we can confirm it's not Ionide ;)

**Comment by lilred** [comment] 2017-01-26 21:01
Several students came in today to report FSI-related glitches. There was a theme: the code gets printed in the F# Interactive panel, but FSI does not output anything.

Nothing reproducible, or I would open another issue. But I'm getting the impression that the FSI component has quite a few gremlins hidden around!

**Comment by Krzysztof-Cieslak** [comment] 2017-01-26 21:04
Let's stay on topic here, and try to fix this one first.

**Comment by Krzysztof-Cieslak** [comment] 2017-02-02 16:38
@Tyriar, any ideas? @smoothdeveloper was able to reproduce it using plugin written in TypeScript so it seems it's not really issue on plugin / Ionide side.

**Comment by Tyriar** [comment] 2017-02-03 02:08
@smoothdeveloper does it happen if you launch cmd/bash and send the same text?

**Comment by carlmr** [comment] 2017-02-15 11:32
Has anyone else noticed that copy+pasting to terminal or FSI console has the same character limit? This definitely excludes Ionide if you ask me.

I'm not very familiar with JavaScript so I don't know if I can really contribute here. I don't have the node environment either, so I couldn't build myself. But looking at the code I find this a bit suspicious:

https://github.com/Microsoft/vscode/blob/4a90b5e23bf43312c113f620f8829372ef10cc81/src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#L268-L270

What does the substring function to when text.length overflows, or it somehow indexes outside the string?

Other than that one could try a workaround, where the string is split into 512 or 1024 character sequences and then sent chunked to the terminal. If this solves the issue, then we would know where it happens.

**Comment by lilred** [comment] 2017-02-19 18:49
Should we open an issue in the VS Code repo?

**Comment by SoftwareApe** [comment] 2017-02-21 13:15
So I got around to testing my assumption. We can put in a workaround for the character limit in the plugin, but the problem is below the sendText function in Terminal. I tested my workaround with 80000 character with no issue.

**Comment by Dalusia** [comment] 2017-02-21 16:02
Thank you, that's great news. If there's any help I can give with testing, please let me know.

**Comment by SoftwareApe** [comment] 2017-02-21 16:12
@Dalusia this is my first time committing anything on GitHub, I'm not sure about the process here. It would make sense to have some tests for the string chunking function.

I'm also not sure how to put this change into the main development branch.

**Comment by Krzysztof-Cieslak** [comment] 2017-02-21 21:12
I've merged it and released fix in `2.23.1`. Please let me know if the problem is gone.

**Comment by lilred** [comment] 2017-02-21 21:16
As an aside - I'd like to give it to my students to test, but we've had to tell them to stop upgrading since so many of them ran into #363.

**Comment by SoftwareApe** [comment] 2017-02-22 06:32
@Krzysztof-Cieslak Thank you. It works in the release for me.

**Comment by Krzysztof-Cieslak** [comment] 2017-02-24 17:45
OK, I assume this is fixed with @SoftwareApe's workaround.  Closing this issue.

P.S. @Tyriar, I still believe that it should be fixed in VSCode (or at least documented somewhere)

**Closed by Krzysztof-Cieslak** 2017-02-24 17:45 UTC
Labels: backburner - requires additional upstream functionality, bug

**Comment by lilred** [comment] 2017-02-24 18:50
I'm going to try and test this in the coming days. Once it's validated, @SoftwareApe you can claim the [bounty](https://www.bountysource.com/issues/39030641-f-interactive-do-not-accept-more-than-1357-characters).

**Comment by lilred** [comment] 2017-02-26 19:32
So I went to check if the bug was fixed, and i realized/remembered that I don't have a machine that would reproduce this problem in the first place. >:(

**Comment by SoftwareApe** [comment] 2017-02-27 07:41
After talking to @lilred about the bounty. I don't need it, and we agreed to give it to @Krzysztof-Cieslak for his great work here.

**Comment by Krzysztof-Cieslak** [comment] 2017-02-27 09:37
I'd suggest doing donation to FSSF ( or any charity / non-profit org) you'd prefer instead.

**Comment by SoftwareApe** [comment] 2017-02-27 11:19
That's a good suggestion, I think https://www.eff.org/ is also very important right now, as there needs to be someone defending our rights online.

**Comment by Dalusia** [comment] 2017-02-27 13:24
Just had a chance to check this out, works perfectly for me.
I initially tried with a ridiculously long line of code, which caused some strange problems... but overall script length seems fine, my past examples (that used to trigger the issue) all pass fine now.
Many thanks to SoftwareApe & Krzysztof-Cieslak, as well as lilred and the others that provided input!
