### ISSUE TITLE
Add file does not work for files in folders

### ISSUE THREAD

**Issue by sjohnsonaz** [ionide/ionide-vscode-fsharp#1825] opened 2023-02-17 19:39 UTC
### Describe the bug

In the F# Solution Explorer, when right clicking on a File inside a folder, I can select "Add file above" or "Add file below", but nothing happens.  I also cannot get a context menu at all for folders.

#### Case 1

* Navigate to the F# Solution Explorer
* Locate a file nested inside a folder

![Screenshot_20230217_123402](https://user-images.githubusercontent.com/2746299/219770845-43e51ddd-8010-4b5c-b538-7dc4d534a196.png)

* Right click any file inside that folder to show the context menu

![Screenshot_20230217_123526](https://user-images.githubusercontent.com/2746299/219771322-1e85d5e6-6c91-4051-9232-49893dfdec04.png)

* Click "Add file below" or "Add file above"
* Nothing happens

#### Case 2

* Navigate to the F# Solution Explorer
* Locate a file nested inside a folder
* Right click any folder to show the context menu
* Nothing happens

### Expected behaviour

The add file dialog appears

## Machine info
 - OS: Windows
 - .NET SDK version: 7.0.102
 - Ionide version: 7.4.2

**Comment by sjohnsonaz** [comment] 2023-03-01 00:51
This bug is definitely still happening in the new version.  It's making F# in VS Code pretty unusable.

**Comment by TheAngryByrd** [comment] 2023-03-01 01:48
The place to start diagnosing this would be [SolutionExplorer.fs](https://github.com/ionide/ionide-vscode-fsharp/blob/main/src/Components/SolutionExplorer.fs).

Would you be willing to contribute a fix for this?

**Comment by farlee2121** [comment] 2023-03-09 23:50
I can confirm that add file (either above or below) work in two of my personal projects while using Ionide 7.5.1.
However, it doesn't work with this project (ionide-vscode-fsharp). 

When I try to debug, I can open other project folders but trying to open the ionide-vscode-fsharp project folder fails silently. The debug vscode instance neither closes nor opens the folder. I don't see any logs either.

**Comment by MangelMaxime** [comment] 2023-03-11 20:10
After looking at the code, I think this is because when trying to compute the path of the file. We need to detect the project it belongs too.

But when coded the logic, I only added support for File directly under the project without supporting Folders. I need to rework, the logic to consider the folders.

https://github.com/ionide/ionide-vscode-fsharp/blob/52d607ad7aacdb3c144014741386620f67a5f6ac/src/Components/SolutionExplorer.fs#L821-L840

**Closed** 2023-03-12 18:13 UTC
Labels: bug, up for grabs
