### ISSUE TITLE
ENOENT: no such file or directory found, when trying to run F# code on Windows 10

### ISSUE THREAD

**Issue by SirKastic** [ionide/ionide-vscode-fsharp#1007] opened 2019-02-06 00:40 UTC
Error:
I've been trying to run a fsproj in Visual Studio, however it keeps giving me the "ENOENT: no such file or directory found", however the code runs with the F# Interactive tools
As I'm new to programming I'm not sure what is this error, how to fix it, or what informations I must supply to get help

I would appreciate any help, thank you

**Comment by inosik** [comment] 2019-02-07 08:19
Maybe a duplicate of #965?

**Comment by Krzysztof-Cieslak** [comment] 2019-06-24 14:10
This shouldn't happen in Ionide 4.0

**Closed** 2019-06-24 14:10 UTC
