### ISSUE TITLE
connect ECONNREFUSED 127.0.0.1:8960

### ISSUE THREAD

**Issue by Gulogomi** [ionide/ionide-vscode-fsharp#941] opened 2018-10-17 10:10 UTC
Greetings everyone.

I get the error "connect ECONNREFUSED 127.0.0.1:8960" whenever I try to run the script within Code Studio. It used to work before. I have tried to press ALT+ENTER but I get the following errors:
"Failed to send text to FSI" 
"Failed to spawn FSI, please ensure it's in PATH"

I'm running Ubuntu 18.04.1
Code 1.28.1

The log output:

```
[11:58:54 INFO ] Logging to output at level INFO. If you want detailed messages, try level DEBUG.
[11:58:54 INFO ] .Net runtime specified
[11:58:54 INFO ] finding FSAC for
	runtime: NET
	mono: mono
	dotnet: null
[11:58:55 ERROR] RES (001) <- {compilerlocation} ERROR in 7 ms: {stack: Error: connect ECONNREFUSED 127.0.0.1:8960
	at Object._errnoException (util.js:1024:11)
	at _exceptionWithHostPort (util.js:1046:20)
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14), message: connect ECONNREFUSED 127.0.0.1:8960, code: ECONNREFUSED, errno: ECONNREFUSED, syscall: connect, address: 127.0.0.1, port: 8960, config: [object Object], request: [object Object], response: undefined} Data=undefined
[11:59:00 ERROR] RES (002) <- {compilerlocation} ERROR in 2 ms: {stack: Error: connect ECONNREFUSED 127.0.0.1:8960
	at Object._errnoException (util.js:1024:11)
	at _exceptionWithHostPort (util.js:1046:20)
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14), message: connect ECONNREFUSED 127.0.0.1:8960, code: ECONNREFUSED, errno: ECONNREFUSED, syscall: connect, address: 127.0.0.1, port: 8960, config: [object Object], request: [object Object], response: undefined} Data=undefined
[11:59:02 ERROR] RES (003) <- {compilerlocation} ERROR in 47 ms: {stack: Error: connect ECONNREFUSED 127.0.0.1:8960
	at Object._errnoException (util.js:1024:11)
	at _exceptionWithHostPort (util.js:1046:20)
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14), message: connect ECONNREFUSED 127.0.0.1:8960, code: ECONNREFUSED, errno: ECONNREFUSED, syscall: connect, address: 127.0.0.1, port: 8960, config: [object Object], request: [object Object], response: undefined} Data=undefined
[11:59:02 ERROR] RES (004) <- {compilerlocation} ERROR in 3 ms: {stack: Error: connect ECONNREFUSED 127.0.0.1:8960
	at Object._errnoException (util.js:1024:11)
	at _exceptionWithHostPort (util.js:1046:20)
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14), message: connect ECONNREFUSED 127.0.0.1:8960, code: ECONNREFUSED, errno: ECONNREFUSED, syscall: connect, address: 127.0.0.1, port: 8960, config: [object Object], request: [object Object], response: undefined} Data=undefined
[11:59:02 ERROR] RES (005) <- {compilerlocation} ERROR in 1 ms: {stack: Error: connect ECONNREFUSED 127.0.0.1:8960
	at Object._errnoException (util.js:1024:11)
	at _exceptionWithHostPort (util.js:1046:20)
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14), message: connect ECONNREFUSED 127.0.0.1:8960, code: ECONNREFUSED, errno: ECONNREFUSED, syscall: connect, address: 127.0.0.1, port: 8960, config: [object Object], request: [object Object], response: undefined} Data=undefined
[11:59:02 ERROR] RES (006) <- {compilerlocation} ERROR in 3 ms: {stack: Error: connect ECONNREFUSED 127.0.0.1:8960
	at Object._errnoException (util.js:1024:11)
	at _exceptionWithHostPort (util.js:1046:20)
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14), message: connect ECONNREFUSED 127.0.0.1:8960, code: ECONNREFUSED, errno: ECONNREFUSED, syscall: connect, address: 127.0.0.1, port: 8960, config: [object Object], request: [object Object], response: undefined} Data=undefined
[11:59:02 ERROR] RES (007) <- {compilerlocation} ERROR in 3 ms: {stack: Error: connect ECONNREFUSED 127.0.0.1:8960
	at Object._errnoException (util.js:1024:11)
	at _exceptionWithHostPort (util.js:1046:20)
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14), message: connect ECONNREFUSED 127.0.0.1:8960, code: ECONNREFUSED, errno: ECONNREFUSED, syscall: connect, address: 127.0.0.1, port: 8960, config: [object Object], request: [object Object], response: undefined} Data=undefined
[11:59:34 ERROR] RES (008) <- {compilerlocation} ERROR in 5 ms: {stack: Error: connect ECONNREFUSED 127.0.0.1:8960
	at Object._errnoException (util.js:1024:11)
	at _exceptionWithHostPort (util.js:1046:20)
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14), message: connect ECONNREFUSED 127.0.0.1:8960, code: ECONNREFUSED, errno: ECONNREFUSED, syscall: connect, address: 127.0.0.1, port: 8960, config: [object Object], request: [object Object], response: undefined} Data=undefined
[12:01:46 ERROR] RES (009) <- {compilerlocation} ERROR in 4 ms: {stack: Error: connect ECONNREFUSED 127.0.0.1:8960
	at Object._errnoException (util.js:1024:11)
	at _exceptionWithHostPort (util.js:1046:20)
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14), message: connect ECONNREFUSED 127.0.0.1:8960, code: ECONNREFUSED, errno: ECONNREFUSED, syscall: connect, address: 127.0.0.1, port: 8960, config: [object Object], request: [object Object], response: undefined} Data=undefined
[12:02:27 ERROR] RES (010) <- {compilerlocation} ERROR in 4 ms: {stack: Error: connect ECONNREFUSED 127.0.0.1:8960
	at Object._errnoException (util.js:1024:11)
	at _exceptionWithHostPort (util.js:1046:20)
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14), message: connect ECONNREFUSED 127.0.0.1:8960, code: ECONNREFUSED, errno: ECONNREFUSED, syscall: connect, address: 127.0.0.1, port: 8960, config: [object Object], request: [object Object], response: undefined} Data=undefined
[12:03:35 ERROR] RES (011) <- {compilerlocation} ERROR in 4 ms: {stack: Error: connect ECONNREFUSED 127.0.0.1:8960
	at Object._errnoException (util.js:1024:11)
	at _exceptionWithHostPort (util.js:1046:20)
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14), message: connect ECONNREFUSED 127.0.0.1:8960, code: ECONNREFUSED, errno: ECONNREFUSED, syscall: connect, address: 127.0.0.1, port: 8960, config: [object Object], request: [object Object], response: undefined} Data=undefined
[12:04:53 ERROR] RES (012) <- {compilerlocation} ERROR in 3 ms: {stack: Error: connect ECONNREFUSED 127.0.0.1:8960
	at Object._errnoException (util.js:1024:11)
	at _exceptionWithHostPort (util.js:1046:20)
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14), message: connect ECONNREFUSED 127.0.0.1:8960, code: ECONNREFUSED, errno: ECONNREFUSED, syscall: connect, address: 127.0.0.1, port: 8960, config: [object Object], request: [object Object], response: undefined} Data=undefined
[12:05:28 ERROR] RES (013) <- {compilerlocation} ERROR in 3 ms: {stack: Error: connect ECONNREFUSED 127.0.0.1:8960
	at Object._errnoException (util.js:1024:11)
	at _exceptionWithHostPort (util.js:1046:20)
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14), message: connect ECONNREFUSED 127.0.0.1:8960, code: ECONNREFUSED, errno: ECONNREFUSED, syscall: connect, address: 127.0.0.1, port: 8960, config: [object Object], request: [object Object], response: undefined} Data=undefined
```

**Comment by Krzysztof-Cieslak** [comment] 2018-10-18 09:04
Duplicate of #939

**Closed by Krzysztof-Cieslak** 2018-10-18 09:04 UTC
