### ISSUE TITLE
Can't automatically F5 Start a .NET 6 app

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#1689] opened 2022-04-16 14:18 UTC
### Describe the bug
I've got the latest Ionide but unfortunately the new F5 support isn't working for me and won't create a launch.json file. In fact, at the moment I don't seem to be able to make F5 work at all, even if I manually make one.

### Steps to reproduce
1. I created a .NET 6 console app.
1. CTRL + SHIFT + B works fine: I get a command palette option to Build my app (app.fsproj), select it, it works.
2. No tasks.json is made. I'm not sure if this is by design or not.
3. Hit F5. I get a command palette as follows and choose "Ionide LaunchSettings"

<img width="641" alt="image" src="https://user-images.githubusercontent.com/1781813/163678249-73be6737-9054-4d41-9d74-b5fca4010708.png">

4. I get the following error message:

<img width="486" alt="image" src="https://user-images.githubusercontent.com/1781813/163678264-e5ea5537-bc69-4a7e-b3d6-752ead08f762.png">

and am left with an empty `launch.json` file as follows:

```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": []
}
```

5. I then manually created the launch.JSON file by adding a Configuration as follows:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Core Launch (console)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceFolder}/src/app/bin/Debug/net6.0/app.dll",
            "args": [],
            "cwd": "${workspaceFolder}",
            "stopAtEntry": false,
            "console": "internalConsole"
        }

    ]
}
```

6. I then get this error because there's no tasks.json file:

<img width="425" alt="image" src="https://user-images.githubusercontent.com/1781813/163678356-ab4179ed-f30d-459b-9eba-50797d963a3d.png">

7. I chose Configure Task and get this option in the palette:

<img width="635" alt="image" src="https://user-images.githubusercontent.com/1781813/163678391-de4c2689-0800-4a05-ab2d-50538cb64e82.png">

8. I end up with a `tasks.json` file like this:

```json
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "msbuild",
			"problemMatcher": [
				"$msCompile"
			],
			"group": "build",
			"label": "Build: app.fsproj",
			"detail": "Build the app.fsproj project using dotnet build"
		}
	]
}
```

9. I hit F5 again (with my F# code active and open) and get the same error as in point 6.

### Expected behaviour
I'm not entirely sure what the F5 experience is supposed to be in the new Ionide but I assumed that it would automatically launch the app and attach the debugger.

## Machine info
 - OS: Windows
 - .NET SDK version: 6.0.202
 - Ionide version: 6.0.0

**Comment by baronfel** [comment] 2022-04-16 18:48
That's super-weird - the experience with no launch.json is clearly not what we want.

So a couple base assertions, based on my own testing:
* Ionide is generating the automatic debug configurations - if you open the Command Palette and choose the `Debug: Select and Start Debugger`, you should see the `Ionide LaunchSettings` item (PS - would love feedback on the name), and upon selecting that you should see your debug configuration.
 
![image](https://user-images.githubusercontent.com/573979/163687485-6cc6e92e-89d3-47a4-91b6-a80ebabb5988.png)

* Once you _do_ choose a debug configuration, F5 works.

For point 3, yeah that's by design. Both the new tasks integration and the launch config integration are both in-memory. You can 'eject' one out into a task/launch setting in your file with the little gear icon on the pick list:
![image](https://user-images.githubusercontent.com/573979/163687480-36ba37f8-9269-4729-9e2f-0c168ac348a1.png)

I'm wondering if the odd default behavior when you F5 in an empty project is coming from Omnisharp, and we don't get a chance to overwrite it...

For point 6, you specified the name of a build task that doesn't exist - you'd need the full name, which is something like `Build: <project file name>`

**Comment by baronfel** [comment] 2022-04-16 19:22
And of course it goes without saying that the 'debug your code' section of the docs should be updated with some/all of this information in a more user-digestible form.

**Comment by isaacabraham** [comment] 2022-04-16 20:48
Yes, that worked like a charm - thank you! So where do these "ephemeral" (?) files live - they seem to persist across Code restarts, but no new files show up in e.g. Git.

Also - I tried "Configure Task" from the palette and now see this:

<img width="645" alt="image" src="https://user-images.githubusercontent.com/1781813/163690790-6e2b8ced-e865-4f4a-a85d-6453f844672e.png">

One general thought is: Is it possible to actually generate and persist the tasks created by Ionide? Otherwise on restart you see this in the Debug pane:

<img width="289" alt="image" src="https://user-images.githubusercontent.com/1781813/163690892-e9a96ca5-8649-4598-880b-312b1094959c.png">

Which sort of contradicts what I just said about things persisting... I'm super confused now!

**Comment by baronfel** [comment] 2022-04-23 22:35
The cool thing is, these ephemeral tasks/debug configurations are never persisted to a file - they're populated by code responding to an API call so we can make sure they're up to date. There's a little gear icon on the right hand side of each one in the drop down menus that you can use to automatically extract it to an actual file, however.

**Comment by Krzysztof-Cieslak** [comment] 2022-07-23 22:46
Ok, I think everything here is working as expected (assuming O# starts correctly... but we can't do anything with it) so closing.

**Closed by Krzysztof-Cieslak** 2022-07-23 22:46 UTC

**Comment by ilog2000** [comment] 2023-01-19 09:55
Not sure this issue was properly fixed. I created a new console project and pressing F5 followed by choosing "Ionide launchsettings.json" DID NOT WORK until I open Command Palette, selected "Debug: Select and Start Debugger" and confirmed "Ionide launchsettings.json" and the current project.

**Comment by baronfel** [comment] 2023-01-19 12:04
That's IMO kind of unavoidable because of the way that VSCode's logic works here - if you have run a launch configuration before, f5 runs the last selected one again. Otherwise it does....something? It's this last part that I haven't been able to really solve.

**Comment by ilog2000** [comment] 2023-01-19 15:56
Oh, okay, will remember for the future. Thank you for responding.
