### ISSUE TITLE
F#: Clear cache project doesn't work

### ISSUE THREAD

**Issue by MangelMaxime** [ionide/ionide-vscode-fsharp#1616] opened 2021-11-09 14:24 UTC
### Describe the bug**

![image](https://user-images.githubusercontent.com/4760796/140941186-40d315f8-2ec3-4621-a26b-0ed1b94981fa.png)

### Steps to reproduce

1.Press `Ctrl+Shift+P`
2. Launch "F#: Clear cache project"
3. See the error

### Expected behaviour

Should not fail

## Machine info
 - OS: Windows/Mac/Linux
 - .NET SDK version:
    - 3.1.415 [/usr/share/dotnet/sdk]
    - 5.0.403 [/usr/share/dotnet/sdk]
    - 6.0.100 [/usr/share/dotnet/sdk]
 - Ionide version: 5.9.0

**Comment by Krzysztof-Cieslak** [comment] 2021-11-19 14:29
Duplicate of #1586

**Closed by Krzysztof-Cieslak** 2021-11-19 14:29 UTC
