### ISSUE TITLE
Request textDocument/formatting failed

### ISSUE THREAD

**Issue by JonCanning** [ionide/ionide-vscode-fsharp#1496] opened 2021-02-10 14:09 UTC
`Format Document` command yields this error in the Output console

```
[Error - 2:03:34 PM] Request textDocument/formatting failed.
  Message: Newtonsoft.Json.JsonSerializationException: Cannot set value onto extension data member 'AdditionalData'. The extension data collection is null and it cannot be set.
   at Newtonsoft.Json.Serialization.DefaultContractResolver.<>c__DisplayClass45_1.<SetExtensionDataDelegates>b__0(Object o, String key, Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
   at LanguageServerProtocol.Server.requestHandling@2513.Invoke(server lspServer, FSharpOption`1 paramsToken) in D:\a\ionide-vscode-fsharp\ionide-vscode-fsharp\paket-files\github.com\fsharp\FsAutoComplete\src\LanguageServerProtocol\LanguageServerProtocol.fs:line 2546
  Code: -32700 
```

**Comment by michael-i2o** [comment] 2021-02-10 14:31
I am experiencing this too since v5.3.0 was released.

**Comment by baronfel** [comment] 2021-02-10 15:09
Can either of you please provide a sample fsx file or zipped project that this can be reproduced on?

**Comment by JonCanning** [comment] 2021-02-10 15:18
It happens to me with an empty fsx file

**Comment by baronfel** [comment] 2021-02-10 15:28
Thanks, that helps a lot

**Comment by baronfel** [comment] 2021-02-10 23:47
I can't replicate on my machine using ionide 5.3.2 on macos on .net sdk 5.0.102. Here's the log I see with the following settings set when I invoke 'format document' on an empty (or even full!) script file:

```json
    "FSharp.verboseLogging": false,
    "FSharp.trace.server": "verbose"
```

```
[Trace - 5:40:10 PM] Sending request 'textDocument/formatting - (20)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/chethusk/oss/scratch/script.fsx"
    },
    "options": {
        "tabSize": 4,
        "insertSpaces": true
    }
}


[17:40:10.247 WRN] [Fantomas] No fantomas configuration found for file '/Users/chethusk/oss/scratch/script.fsx' or parent directories. Using the default configuration.
[Trace - 5:40:10 PM] Received response 'textDocument/formatting - (20)' in 126ms.
Result: [
    {
        "range": {
            "start": {
                "line": 0,
                "character": 0
            },
            "end": {
                "line": 0,
                "character": 0
            }
        },
        "newText": ""
    }
]

```

Can you provide me with these calls back and forth on your machine? Otherwise I don't know how to help you.

**Comment by JonCanning** [comment] 2021-02-11 08:56
```
[Trace - 8:54:00 AM] Sending request 'textDocument/formatting - (168)'.
Params: {
    "textDocument": {
        "uri": "file:///Users/jon/dev/Property/output/empty.fsx"
    },
    "options": {
        "tabSize": 2,
        "insertSpaces": true,
        "trimTrailingWhitespace": true,
        "trimFinalNewlines": true
    }
}


[Trace - 8:54:00 AM] Received response 'textDocument/formatting - (168)' in 2ms. Request failed: Newtonsoft.Json.JsonSerializationException: Cannot set value onto extension data member 'AdditionalData'. The extension data collection is null and it cannot be set.
   at Newtonsoft.Json.Serialization.DefaultContractResolver.<>c__DisplayClass45_1.<SetExtensionDataDelegates>b__0(Object o, String key, Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
   at LanguageServerProtocol.Server.requestHandling@2513.Invoke(server lspServer, FSharpOption`1 paramsToken) in D:\a\ionide-vscode-fsharp\ionide-vscode-fsharp\paket-files\github.com\fsharp\FsAutoComplete\src\LanguageServerProtocol\LanguageServerProtocol.fs:line 2546 (-32700).
[Error - 8:54:00 AM] Request textDocument/formatting failed.
  Message: Newtonsoft.Json.JsonSerializationException: Cannot set value onto extension data member 'AdditionalData'. The extension data collection is null and it cannot be set.
   at Newtonsoft.Json.Serialization.DefaultContractResolver.<>c__DisplayClass45_1.<SetExtensionDataDelegates>b__0(Object o, String key, Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
   at LanguageServerProtocol.Server.requestHandling@2513.Invoke(server lspServer, FSharpOption`1 paramsToken) in D:\a\ionide-vscode-fsharp\ionide-vscode-fsharp\paket-files\github.com\fsharp\FsAutoComplete\src\LanguageServerProtocol\LanguageServerProtocol.fs:line 2546
  Code: -32700 
  ```

**Comment by michael-i2o** [comment] 2021-02-11 09:24
Developers in my team are experiencing the same. We're running Ionide 5.3.2 VSCode 1.53.1 on Windows 10.

```
[Trace - 09:20:45] Sending request 'textDocument/formatting - (3570)'.
Params: {
    "textDocument": {
        "uri": "******"
    },
    "options": {
        "tabSize": 4,
        "insertSpaces": true,
        "trimTrailingWhitespace": true,
        "trimFinalNewlines": true
    }
}


[Trace - 09:20:45] Received response 'textDocument/formatting - (3570)' in 1ms. Request failed: Newtonsoft.Json.JsonSerializationException: Cannot set value onto extension data member 'AdditionalData'. The extension data collection is null and it cannot be set.
   at Newtonsoft.Json.Serialization.DefaultContractResolver.<>c__DisplayClass45_1.<SetExtensionDataDelegates>b__0(Object o, String key, Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
   at LanguageServerProtocol.Server.requestHandling@2513.Invoke(server lspServer, FSharpOption`1 paramsToken) in D:\a\ionide-vscode-fsharp\ionide-vscode-fsharp\paket-files\github.com\fsharp\FsAutoComplete\src\LanguageServerProtocol\LanguageServerProtocol.fs:line 2546 (-32700).
[Error - 09:20:45] Request textDocument/formatting failed.
  Message: Newtonsoft.Json.JsonSerializationException: Cannot set value onto extension data member 'AdditionalData'. The extension data collection is null and it cannot be set.
   at Newtonsoft.Json.Serialization.DefaultContractResolver.<>c__DisplayClass45_1.<SetExtensionDataDelegates>b__0(Object o, String key, Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
   at LanguageServerProtocol.Server.requestHandling@2513.Invoke(server lspServer, FSharpOption`1 paramsToken) in D:\a\ionide-vscode-fsharp\ionide-vscode-fsharp\paket-files\github.com\fsharp\FsAutoComplete\src\LanguageServerProtocol\LanguageServerProtocol.fs:line 2546
  Code: -32700 
```

**Comment by JonCanning** [comment] 2021-02-11 09:33
Have tracked it down to having these enabled:
```
"files.trimFinalNewlines": true,
"files.trimTrailingWhitespace": true,
  ```

**Comment by michael-i2o** [comment] 2021-02-11 10:06
I can confirm removing those VSCode settings does provide a workaround.

**Comment by JonCanning** [comment] 2021-02-11 16:37
Seems like these settings are now unnecessary since my editor is still trimming whitespace and lines. If this is the same for you @michael-i2o then I'll close this

**Comment by baronfel** [comment] 2021-02-11 16:43
Many thanks you two. Due to your discussion I was able to easily trace this to our implementation of Newtonsoft.Json AdditionalData (https://github.com/fsharp/fsautocomplete/blob/master/src/LanguageServerProtocol/LanguageServerProtocol.fs#L1175), which doesn't seem to be working with records.

That explains why removing the properties we didn't explicitly have mapped caused this to start working.

It's worth noting that since we use fantomas for formatting, if you have a .editorconfig in your repo it will use those settings around newlines, whitespace, etc to format the document.

**Comment by michael-i2o** [comment] 2021-02-11 18:42
The global `files.trimTrailingWhitespace` setting applies to all file types and not just F# files, so unfortunately requiring users to remove it or set to `false` for Ionide F# linting to work isn't going to be acceptable for many users.

My team has it set to ensure code and data files for many different languages/formats have trailing whitespace trimmed when saving a file. Instead of setting a global setting we could instead set it per file type, but I don't think a VSCode extension should put a requirement on the use/state of VSCode global settings. 

Is the real issue here that the Ionide implementation of Newtonsoft.Json AdditionalData doesn't support records, or an issue in another package? Sorry, I quite didn't follow your explaination @baronfel

**Comment by baronfel** [comment] 2021-02-11 18:45
Oh I don't disagree at all, just suggesting workarounds for the current state. Really we need to do a fix in FSAC for the additional data field. That may mean removing it, that may mean changing that structure to a class for better interior with Newtonsoft.Json, or other resolutions.

**Comment by michael-i2o** [comment] 2021-02-11 19:00
Removing or moving those global settings to specific file type settings is a painless workaround 👍

**Comment by colelawrence** [comment] 2021-02-24 20:53
A couple of the suggestions here didn't work out for me, but putting the following settings into my workspace `settings.json` resolved the error:
```json
{
  "[fsharp]": {
    "files.insertFinalNewline": false,
    "editor.defaultFormatter": "Ionide.Ionide-fsharp"
  },
}
```

`editor.defaultFormatter` isn't entirely necessary.

**Comment by MangelMaxime** [comment] 2022-08-17 09:29
With the new Fantomas service, is there still something to be done for this issue?

**Comment by Krzysztof-Cieslak** [comment] 2022-08-17 10:31
I don't think Fantmas service helped here in any way (the bug was in our LSP layer), but maybe this got accidentally fixed with all the improvements to our LPS library? CC: @baronfel

**Comment by baronfel** [comment] 2022-08-17 11:18
Correct - this was fixed in the underlying library.

**Closed** 2022-08-17 11:18 UTC
Labels: bug, language services
