### ISSUE TITLE
Adding a quote to function name makes VSCode unresponsive

### ISSUE THREAD

**Issue by yngvedh** [ionide/ionide-vscode-fsharp#1454] opened 2020-12-19 20:59 UTC
**Describe the bug**
The plugin makes Visual Studio Code unresponsive when I add a single (') or double quote (") in a function name.
VSCode completely locks up and only comes back to life after I select _Reopen_ when it finally realises that _The window is no longer responding_.

I would like to be able to name my tests:
```let ``Should produce "ok"`` () =``` 

**To Reproduce**
1. Create a new Xunit test project `dotnet new xunit --language F#`
1. Add a single or double quote to the generated test function name.

**Expected behaviour**
I expect to be able to add a single or double quote to a function name without an issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/1963918/102699328-0a1fd600-4244-11eb-898e-b70ee58c3222.png)

**Environment (please complete the following information):**
 - OS: macOS Big Sur
 - Ionide version: 4.17.0
 - VSCode version: 14.0.2 (16610.3.7.1.9)
 - dotnet SDK version: 5.0
 - mono / .Net Framework version: 5.0

**Comment by cartermp** [comment] 2020-12-19 21:47
hmm, I can't reproduce this with VSCode 1.52.0 (from one week ago):

```
Version: 1.52.0
Commit: 940b5f4bb5fa47866a54529ed759d95d09ee80be
Date: 2020-12-10T22:46:53.673Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.1.0
```

Using macOS big sure and .NET 5 as well

**Comment by baronfel** [comment] 2020-12-19 22:24
We've seen this over several versions. I know that other users have reported this to me personally. My suspicion is that we have a bad regex in the old textmate grammars that uses a ton of CPU for specific member names with backticks.

**Comment by Krzysztof-Cieslak** [comment] 2020-12-19 22:26
Duplicate of https://github.com/ionide/ionide-vscode-fsharp/issues/1073

**Closed by Krzysztof-Cieslak** 2020-12-19 22:26 UTC
Labels: reproduction needed
