### ISSUE TITLE
Ionide crashes repeateadly and get logs crashes

### ISSUE THREAD

**Issue by jkone27** [ionide/ionide-vscode-fsharp#1656] opened 2022-01-18 10:32 UTC
### Describe the bug
Ionide crashes and VSCODE hangs completely

### Steps to reproduce
modifying code, when code is not valid in a big soluton (while working on it) and does not compile yet, ionide and vscode both crash

### Link to sample reproduction
using FSharp.Data big project, no sample atm

### Expected behaviour
vscode nor ionide crashes

### Screenshots
![image](https://user-images.githubusercontent.com/10419217/149920052-15a3808d-761f-41d9-8ddb-bf818793f30d.png)

no logs either

![image](https://user-images.githubusercontent.com/10419217/149920199-bdbb5e05-5e6f-4c44-ada5-81618288acd4.png)

## Machine info
 - OS: Mac
 - .NET 6 
 - Ionide version: 5.10.2

**Comment by baronfel** [comment] 2022-01-18 13:05
Judging from your screenshot, this is a duplicate of https://github.com/ionide/ionide-vscode-fsharp/issues/1073

**Comment by Krzysztof-Cieslak** [comment] 2022-07-12 13:08
Duplicate of https://github.com/ionide/ionide-vscode-fsharp/issues/1073

**Closed by Krzysztof-Cieslak** 2022-07-12 13:08 UTC
