### ISSUE TITLE
Namespace not defined issues with project created by VS

### ISSUE THREAD

**Issue by csmager** [ionide/ionide-vscode-fsharp#132] opened 2016-08-12 10:12 UTC
I'm not sure if I'm being dumb here, but I can't get this to work. I first tried opening a larger project that references other 3rd party dlls that had similar issues in using types from there, but I've managed to recreate with something very minimal. I've pushed the repro [here](https://github.com/csmager/ionide-error-repro), but for completeness the steps I followed were:
1. Create new project in VS 2015 (F# Class Lib, .NET 4.6)
2. Add some simple code that uses `System.Text.RegularExpressions`.  This compiles fine.
3. Open folder in VS Code with Ionide.

I get these errors:

![image](https://cloud.githubusercontent.com/assets/5575049/17619001/a0f28722-607a-11e6-8aaa-3359fb653d64.png)

If I create the same project via VS Code using 'F# New Project (without FAKE)', I get no errors. For what it's worth, I tried this in Atom too and had the same issues.

I've tried manually editing the `.fsproj` file to match the one created by Ionide (using `FSharp.Core.dll` from Paket was the main change), but didn't have any success.

**Comment by csmager** [comment] 2016-08-12 10:26
After a bit more fiddling, it appears the offending issue  the import of `MIcrosoft.FSharp.Targets`.  This, created by VS code, works:
```
<Import Project="$(FSharpTargetsPath)" Condition="Exists('$(FSharpTargetsPath)')" />
```
This, created by VS 2015, doesn't:
```
<Import Project="$(FSharpTargetsPath)" />
```
I'm guessing this is only needed at compile time and, without the condition, ionide is choking on it.

**Comment by cloudRoutine** [comment] 2016-08-12 11:49
Can't reproduce using your `ionide-error-repro` repo

![](http://i.imgur.com/Yks1oZW.png)

When diagnosing an issue you're having with ionide turn on this setting

![](http://i.imgur.com/kTPs54f.png)

and check the developer log for the errors that are produced

![](http://i.imgur.com/clu9gfG.png)

**Comment by csmager** [comment] 2016-08-12 12:03
This seems to be the relevant bits. I assume the conditions to set `FSharpTargetsPath` aren't met, so the path is empty:

>[Extension Host] [IONIDE-FSAC-RES] 0 http://localhost:8263/project project Object {Project: "c:\dev\FSharpTest\FSharpTest\FSharpTest.fsproj", Files: Array[0], Output: "null", References: Array[1], Logs: Object}Files: Array[0]Logs: Objectc:\dev\FSharpTest\FSharpTest\FSharpTest.fsproj: "Microsoft.Build.Exceptions.InvalidProjectFileException: The value "" of the "Project" attribute in element <Import> is invalid. Parameter "path" cannot have zero length.
↵   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
↵   at Microsoft.Build.Shared.ProjectErrorUtilities.VerifyThrowInvalidProject(Boolean condition, String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object arg0, Object arg1, Object arg2, Object arg3)
↵   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, String importExpressionEscaped, ProjectImportElement importElement)
↵   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
↵   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
↵   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate()
↵   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCache projectRootElementCache, BuildEventContext buildEventContext, ProjectInstance projectInstanceIfAnyForDebuggerOnly)
↵   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation)
↵   at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings)
↵   at Microsoft.Build.Evaluation.Project..ctor(XmlReader xmlReader, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings)
↵   at Microsoft.FSharp.Compiler.SourceCodeServices.ProjectCrackerTool.Program.projectInstanceFromFullPath@139(FSharpProjectFileInfo this, ProjectCollection engine, String fsprojFullPath)
↵   at Microsoft.FSharp.Compiler.SourceCodeServices.ProjectCrackerTool.Program.FSharpProjectFileInfo.CrackProjectUsingNewBuildAPI(String fsprojFile)
↵   at Microsoft.FSharp.Compiler.SourceCodeServices.ProjectCrackerTool.Program.FSharpProjectFileInfo..ctor(String fsprojFileName, FSharpOption`1 properties, FSharpOption`1 enableLogging)
↵   at Microsoft.FSharp.Compiler.SourceCodeServices.ProjectCrackerTool.Program.getOptions@376(Boolean enableLogging, FSharpList`1 properties, String file)
↵   at Microsoft.FSharp.Compiler.SourceCodeServices.ProjectCrackerTool.Program.getOptions(String file, Boolean enableLogging, FSharpList`1 properties)
↵   at Microsoft.FSharp.Compiler.SourceCodeServices.ProjectCrackerTool.Program.main(String[] argv)"__proto__: ObjectOutput: "null"Project: "c:\dev\FSharpTest\FSharpTest\FSharpTest.fsproj"References: Array[1]__proto__: Object
[Extension Host] [IONIDE-FSAC-REQ] 0 http://localhost:8263/project Object {FileName: "c:\dev\FSharpTest\FSharpTest\FSharpTest.fsproj"}
[Extension Host] [IONIDE-FSAC-RES] 0 http://localhost:8263/project project Object {Project: "c:\dev\FSharpTest\FSharpTest\FSharpTest.fsproj", Files: Array[0], Output: "null", References: Array[1], Logs: Object}Files: Array[0]length: 0__proto__: Array[0]Logs: ObjectOutput: "null"Project: "c:\dev\FSharpTest\FSharpTest\FSharpTest.fsproj"References: Array[1]0: "C:\Program Files (x86)\Reference Assemblies\Microsoft\FSharp\.NETFramework\v4.0\4.4.0.0\FSharp.Core.dll"length: 1__proto__: Array[0]concat: concat()constructor: Array()copyWithin: copyWithin()entries: entries()every: every()fill: fill()filter: filter()find: find()findIndex: findIndex()forEach: forEach()includes: includes()indexOf: indexOf()join: join()keys: keys()lastIndexOf: lastIndexOf()length: 0map: map()pop: pop()push: push()reduce: reduce()reduceRight: reduceRight()reverse: reverse()shift: shift()slice: slice()some: some()sort: sort()splice: splice()toLocaleString: toLocaleString()toString: toString()unshift: unshift()Symbol(Symbol.iterator): values()Symbol(Symbol.unscopables): Object__proto__: Object__proto__: Object__defineGetter__: __defineGetter__()__defineSetter__: __defineSetter__()__lookupGetter__: __lookupGetter__()__lookupSetter__: __lookupSetter__()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get __proto__: get __proto__()set __proto__: set __proto__()
[Extension Host] [IONIDE-FSAC-REQ] 0 http://localhost:8263/parse Object {FileName: "c:\dev\FSharpTest\FSharpTest\TextUtil.fs", IsAsync: true, Lines: Array[9]}
[Extension Host] [IONIDE-FSAC-RES] 0 http://localhost:8263/parse errors [Object, Object]0: ObjectEndColumn: 36EndLine: 3FileName: "c:\dev\FSharpTest\FSharpTest\TextUtil.fs"Message: "The namespace 'RegularExpressions' is not defined"Severity: "Error"StartColumn: 18StartLine: 3Subcategory: "typecheck"__proto__: Object1: Objectlength: 2__proto__: Array[0]

**Comment by csmager** [comment] 2016-08-12 13:31
Some further info.  If I changed the import to what $(FSharpTargetsPath) should be set to::
```
<Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\FSharp\Microsoft.FSharp.Targets" />
```
I get this error:

>"Microsoft.Build.Exceptions.InvalidProjectFileException: The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\FSharp\Microsoft.FSharp.Targets" was not found.

So that's the cause - that path really doesn't exist as I don't have VS 2013 installed. The $(VisualStudioVersion) should be set to 14.0.

It looks like an issue in ProjectCrackerTool, which it seems that [this pull request](https://github.com/fsharp/FSharp.Compiler.Service/pull/515) fixed and was included in the [2.0.0.3](https://github.com/fsharp/FSharp.Compiler.Service/releases/tag/2.0.0.3) release.  As it's not versioned, I quickly decompiled and it looks like the fix is in the version with `ionide-fsharp` - can you confirm?

**Comment by csmager** [comment] 2016-08-12 14:53
After some tracking down, there are some issues raised against this on FSC and FSAC resulting in [this pull request](https://github.com/fsharp/FSharp.Compiler.Service/pull/566) that will fix the issue (you can follow the links from there back to the original issues).  

I suppose this will be fixed as and when that's merged and released.

**Comment by cloudRoutine** [comment] 2016-08-12 15:44
@csmager great job tracking that down, I'm going to keep nudging them to pick up the pace on that one.

**Comment by Krzysztof-Cieslak** [comment] 2016-08-18 14:00
Is there any progress with that on FCS side?

**Comment by blumu** [comment] 2016-11-15 01:17
@Krzysztof-Cieslak  Would it make sense to keep the bug open to keep track of the issue? Even if the root cause is in FCS it's still a bug that surfaces when using Ionide-Vscode. Also, the next person who hits the issue may end up reopening a new bug for it.

**Comment by Krzysztof-Cieslak** [comment] 2016-11-15 19:04
@blumu I think it should be fixed in latest release of FCS (changes in MsBuild dependency). At least I haven't seen this bug in quite some time. 

I'm happy to reopen it if someone still experience it.

**Comment by blumu** [comment] 2016-11-17 00:18
@Krzysztof-Cieslak  I'm still getting the error on Ionide-fsharp 2.9.4:
![image](https://cloud.githubusercontent.com/assets/3913258/20371248/3d4f6962-ac18-11e6-84b6-376bd8346c48.png)

**Comment by arcticcacti** [comment] 2017-02-27 19:04
I'm not sure if this is exactly the same issue, but I'm getting something similar with Ionide 2.23.5 - in VS Code I do `New Project (windows)` and get this
![image](https://cloud.githubusercontent.com/assets/20615708/23374032/755bcdd4-fd1a-11e6-8b90-9b9df2fcea14.png)

Building also spits out the `error FS0039: The namespace 'ViewModule' is not defined` messages

Paket's pulled in the `FSharp.ViewModule.Core` package and everything *seems* ok, but I'm not too familiar with the whole dependency system. Sorry if this is in the wrong place!

**Comment by Krzysztof-Cieslak** [comment] 2017-08-27 20:36
Closing due to lack of new reports. Hopefully it's fixed.

**Comment by serialhex** [comment] 2017-08-29 13:52
Doing a `New Project (windows)` gives me the same error.

Simply changing the line `open FSharp.ViewModule` -> `open ViewModule` and the same for `open FSharp.ViewModule.Validation` fixes the error.

I'm not sure why that is, but it works, and builds the default project just fine now.

**Comment by blumu** [comment] 2017-08-31 20:27
@Krzysztof-Cieslak Nothing changed since my last comment so I did not bother reporting the same issue again but I confirm that this is still broken.

**Comment by cmeeren** [comment] 2017-10-19 07:42
I'm experiencing the same error. A brand new .NET 4.7 class library created by VS 2017 contains the line `<Import Project="$(FSharpTargetsPath)" />`, which causes VS Code to fail loading the fsproj:

> The value "" of the "Project" attribute in element is invalid. Parameter "path" cannot have zero length.

(I'd guess the missing element name `<Project>` is due to some bug in VS Code.)

This also leads to "namespace not found" errors.

Adding `Condition="Exists('$(FSharpTargetsPath)')"` to the `<Project>` element fixes the problem (and does not seem to break anything in VS 2017).

**Comment by Firgeis** [comment] 2018-01-16 18:24
Same problem as above when opening FSharp.Management, all projects fail to load

VS Code 1.19.2 Ionide 3.15.8

**Closed** 2018-07-20 12:30 UTC
Labels: language services, project cracker
