### ISSUE TITLE
Get ionide logs error

### ISSUE THREAD

**Issue by jkone27** [ionide/ionide-vscode-fsharp#1624] opened 2021-11-10 16:47 UTC
### Describe the bug
get ionide logs using F1 in vscode throws error 

### Steps to reproduce
F1 and get ionide logs on a mac

### Expected behaviour
i can see ionide logs

### Screenshots
![image](https://user-images.githubusercontent.com/10419217/141155986-93c2eb38-7d70-4b31-bd9f-0e1fd01b433a.png)

## Machine info
 - OS: MAC
 - .NET SDK version: 6.0.1
 - Ionide version: 1.61.2 (latest)

**Comment by MangelMaxime** [comment] 2021-11-10 18:48
This is a duplicate of  #1617

**Closed** 2021-11-10 19:45 UTC
