### ISSUE TITLE
Double-backticks can crash the editor

### ISSUE THREAD

**Issue by baronfel** [ionide/ionide-vscode-fsharp#1391] opened 2020-06-26 18:47 UTC
**Describe the bug**
This is a duplicate report of https://github.com/microsoft/vscode/issues/90369, where a user added a new identifier with double-backticks and the editor crashed.  I have seen it as well on personal projects intermittently, as has Mathias Brandewinder.

**Comment by Krzysztof-Cieslak** [comment] 2020-06-26 18:50
Duplicate of https://github.com/ionide/ionide-vscode-fsharp/issues/1073

**Closed by Krzysztof-Cieslak** 2020-06-26 18:50 UTC
