### ISSUE TITLE
InteliSense completion hints are not type aware

### ISSUE THREAD

**Issue by mjarosie** [ionide/ionide-vscode-fsharp#1395] opened 2020-07-05 20:23 UTC
**Describe the bug**

InteliSense completion hints are not "type aware". When invoking the code-completion popup it doesn't take parameter types into account. It results in the "there you go - here's a list of all variables ever defined" hint, which isn't too helpful.

**To Reproduce**

Put a cursor at the end of the last line of this snippet and press `ctrl+space`:

```
let myFunc (x: string): string =
    x

let myInt1: int = 123
let myFloat1: float = 123.0
let myString1: string = "hello"

myFunc my
```

![vscode-code-completion](https://user-images.githubusercontent.com/9082353/86541348-0ac9e780-bf04-11ea-94ab-e904b47664b6.gif)

If you remove `my` from after `myFunc` and press `ctrl+space`, completion hint shows all variables in scope, most of which don't make sense type-wise:

![vscode-code-completion-all-possible-options](https://user-images.githubusercontent.com/9082353/86541434-ca1e9e00-bf04-11ea-89b9-494d0ad7deac.gif)

**Expected behaviour**
I'd expect the hint to show only entries which make sense in terms of types.

**Environment**

 - Ionide version: `v4.14.0`
 - dotnet SDK version: `v3.1.300`
- output of `VSCode -> Help -> About`:

```
Version: 1.46.1 (system setup)
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041
```

**Comment by cartermp** [comment] 2020-07-05 22:24
This is ultimately a limitation of the F# compiler service, where parameters to function calls are not fed as input into the machinery that determines a context for completion. Such a context would then allow for filtering based on relevant situations, like you describe. As it stands, Ionide would need to either work around this limitation with its own ad-hoc implementation of completion context, or do nothing since it's an upstream concern.

**Comment by mjarosie** [comment] 2020-07-06 22:31
Would that make sense to raise it in the upstream repository then?

**Comment by Krzysztof-Cieslak** [comment] 2020-07-08 13:24
Duplicate of #164

**Closed by Krzysztof-Cieslak** 2020-07-08 13:24 UTC
