### ISSUE TITLE
Intellisense, etc. no longer working for version 2.34.0+

### ISSUE THREAD

**Issue by samhanes** [ionide/ionide-vscode-fsharp#516] opened 2017-08-28 16:57 UTC
VS Code 1.15.1
Windows 10 Pro
Ionide-fsharp 2.34.0-4

I'm no longer seeing intellisense/function signatures/error underlining as of version 2.34.0  I have confirmed that everything works fine after downgrading to 2.33.2.

From language service output:
```[12:49:10 DEBUG] REQ (007) -> {tooltip}, File = "~\src\foo\bar.fs"
Data={"FileName":"c:\\code\\src\\foo\\bar.fs","Line":68,"Column":15,"Filter":""}
[12:49:10 DEBUG] RES (007) <- {tooltip} in 4 ms: Kind={"error"}
Data={"Code":1,"Message":"File 'c:\\code\\src\\foo\\bar.fs' not parsed","AdditionalData":{}}
[12:49:10 ERROR] Cannot execute tooltip, File 'c:\code\src\foo\bar.fs' not parsed 
[12:49:33 DEBUG] REQ (008) -> {project}, File = "~\src\foo\bar.fsproj"
Data={"FileName":"c:\\code\\src\\foo\\bar.fsproj"}
[12:49:33 ERROR] RES (008) <- {project} ERROR in 15 ms: Error: Request failed with status code 500 Data=undefined
[12:49:55 DEBUG] REQ (009) -> {project}, File = "~\src\foo\bar.fsproj"
Data={"FileName":"c:\\code\\src\\foo\\bar.fsproj"}
[12:49:55 ERROR] RES (009) <- {project} ERROR in 4 ms: Error: Request failed with status code 500 Data=undefined
```

**Comment by Krzysztof-Cieslak** [comment] 2017-08-28 19:59
Duplicate of #514

**Closed by Krzysztof-Cieslak** 2017-08-28 19:59 UTC
