### ISSUE TITLE
No intellisense / code lens on new file

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#1245] opened 2019-10-13 10:38 UTC
1. Configure VS Code to use F# as the default file type (`"files.defaultLanguage": "fsharp"`)
1. Create a new file in code (e.g. `CTRL + N`).
1. Start typing some F#. Observe that although Code knows it's F# (e.g. F# logo appears in the tab), no intellisense or codelens shows up.
1. Save the file, giving it an `.fsx` extension.
1. Everything starts to work.

**Comment by Krzysztof-Cieslak** [comment] 2019-10-13 12:17
Duplicate of #1156

**Closed by Krzysztof-Cieslak** 2019-10-13 12:17 UTC
Labels: backer

**Comment by isaacabraham** [comment] 2019-10-14 06:59
Sorry for the dupe (from myself!) - forgot I added it.
