### ISSUE TITLE
Add file above/below, Rename file do not work on .NET Core 3.1

### ISSUE THREAD

**Issue by hectorchu** [ionide/ionide-vscode-fsharp#1291] opened 2020-01-20 15:13 UTC
**Describe the bug**
Normally its possible to add a new file to the project by right-clicking an existing file in Project References in the Solution Explorer, and choosing Add file above or below. If .NET Core 3.1 is installed this no longer works as intended. The file is created but the fsproj is not updated.
Rename file is also bugged and does nothing.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install .NET Core 3.1
2. Open existing project containing some files already
3. Right-click on an existing file and choose either to add file above/below, or rename file
4. Observe that the operation does not operate as intended

**Expected behaviour**
It should do what was intended.
It should work as it did on .NET Core 3.0.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Windows & MacOS are both affected.
 - Ionide version: 4.5.0
 - VSCode version: 1.41.1
 - dotnet SDK version: 3.1
 - mono / .Net Framework version: n/a

**Additional context**

**Comment by dkpsk** [comment] 2020-02-11 02:53
This issue might be same as #1297

**Comment by Krzysztof-Cieslak** [comment] 2020-02-16 14:40
Duplicate of #1297

**Closed by Krzysztof-Cieslak** 2020-02-16 14:40 UTC
Labels: bug, forge
