### ISSUE TITLE
Unused open being flagged incorrectly

### ISSUE THREAD

**Issue by mike-morr** [ionide/ionide-vscode-fsharp#614] opened 2017-10-26 20:22 UTC
![image](https://user-images.githubusercontent.com/6625993/32075027-ac056f2e-ba58-11e7-97ba-3ec49de2c81d.png)

If I remove the ```open Types```, ```Model``` stops resolving.  

Expected Result:  No green squiggly on ```open Types```

Note: Increment, Decrement, and Reset are all in the Types module.

Also, this is OOB Fable-Elmish-React-Demo template with no modifications if you need a repro project.

**Comment by Krzysztof-Cieslak** [comment] 2017-10-26 20:31
Hey, @forki I think we've discussed it on Slack, haven't we?

I think it's by design - actually, after removing those opens F# code still will be "correct" since you can use any identifier for pattern match case.

**Comment by forki** [comment] 2017-10-27 02:26
@vasily-kirichenko is doing couple of improvements here. Not sure if this case is covered

**Comment by vasily-kirichenko** [comment] 2017-10-27 05:44
Yes, I rewrote the analyzer and it always works correctly now. But it becomes slow (up to 2-3 seconds on 1K files with 30 opens), I’m waiting for missing info in TAST @dsyme promised to add. After that it will work very fast.

**Comment by Krzysztof-Cieslak** [comment] 2017-11-02 21:28
Fixed in `3.10.1`

**Closed by Krzysztof-Cieslak** 2017-11-02 21:28 UTC
Labels: language services (FSAC / FCS / Project Cracker)
