### ISSUE TITLE
Arguments of extern declarations are marked unused

### ISSUE THREAD

**Issue by Pharmhaus-2** [ionide/ionide-vscode-fsharp#727] opened 2018-03-04 15:17 UTC
```fsharp
open System
open System.Runtime.InteropServices

[<DllImport("abc.dll", CallingConvention = CallingConvention.Cdecl, CharSet=CharSet.Ansi)>]
extern IntPtr Test (string procname) 

            
[<EntryPoint>]
let main args =
    
    0
```

The application I am writing heavily relies on extern declarations.
After a few thousand warnings causes by extern declarations the linter (or vs code?) stops with the message "not showing xxx further warnings and errors"

**Comment by enricosada** [comment] 2018-03-08 11:39
i can repro.

seems an FCS issue, i'll open a bug

**Comment by enricosada** [comment] 2018-03-08 19:25
@Pharmhaus-2 is a bug in the F# compiler service (FCS) component, used by ionide. 

I moved this issue in the repo where should be fixed ( https://github.com/Microsoft/visualfsharp/issues/4473 ), and when fixed will be merged in ionide with the next update of FCS

Closing because not a bug of ionide itself.

**Closed by enricosada** 2018-03-08 19:25 UTC
Labels: bug, language services (FSAC / FCS / Project Cracker)
