### ISSUE TITLE
Generate Type Annotations

### ISSUE THREAD

**Issue by g5becks** [ionide/ionide-vscode-fsharp#1434] opened 2020-11-11 17:15 UTC
In Jetbrains rider, there is a feature to generate annotations for any let bindings. I was wondering if this is something that could be added to Ionide, or maybe it already exists and I am unaware?

Thanks.

**Comment by Krzysztof-Cieslak** [comment] 2020-12-14 15:49
Duplicate of #173

**Closed by Krzysztof-Cieslak** 2020-12-14 15:49 UTC
