### ISSUE TITLE
Quick help not working in latest released version

### ISSUE THREAD

**Issue by mike-morr** [ionide/ionide-vscode-fsharp#432] opened 2017-05-10 23:10 UTC
https://www.youtube.com/watch?v=WyDyM0gUuwM

Please see the above 30 second video for the actual results.

Expected results would be green line no longer shows up after it fixes my code the first time.

**Comment by Krzysztof-Cieslak** [comment] 2017-05-11 10:43
I think the problem is that VSCode doesn't raise TextChanged event after applying Edit... interesting.

Anyway, we can probably work around it.

**Comment by Krzysztof-Cieslak** [comment] 2017-06-19 11:58
Fixed in `2.27.3`

**Closed by Krzysztof-Cieslak** 2017-06-19 11:58 UTC
Labels: bug
