### ISSUE TITLE
Intellisense not working in .fs files

### ISSUE THREAD

**Issue by AdamPaulSmith** [ionide/ionide-vscode-fsharp#372] opened 2017-02-22 19:52 UTC
When I create an .fs file there is no intellisence or error underlining. When I create a .fsx file all features seem to work correctly.

**Comment by Krzysztof-Cieslak** [comment] 2017-02-24 17:48
Please enable debugging as described in readme and post detailed log from `F# Language Service` and `F# Language Service (server)` output tabs

**Comment by AdamPaulSmith** [comment] 2017-02-24 18:26
Rerpoduction steps:

1. Create a new file with the .fs extension
2. Intellisense does not work
3. Create a new file with the .fsx extension
4. Intellisense does work

Log for when opening a .fs file:

[Extension Host] [IONIDE-FSAC] REQ (017) -> {parse}, File = "~\Model.fs"
Data=Object
[Extension Host] last output: [object Map]
[Extension Host] [IONIDE-FSAC] REQ (018) -> {lint}, File = "~\Model.fs"
Data=Object
[Extension Host] [IONIDE-FSAC] RES (018) <- {lint} in 5 ms: Kind={"info"}
Data=Cached typecheck results not yet available
[Extension Host] [IONIDE-FSAC] RES (017) <- {parse} in 32 ms: Kind={"info"}
Data=Parse aborted
[Extension Host] [IONIDE-FSAC] REQ (019) -> {declarations}, File = "~\Model.fs"
Data=Object

**Comment by lsmullenbrock** [comment] 2017-02-28 04:18
Having the same problem here. 
.fsx file debug output:
`[22:15:23 INFO ] REQ (257) -> {parse}, File = "c:\test.fsx"
Data={"FileName":"c:\\test.fsx","IsAsync":true,"Lines":[""],"Version":1}
[22:15:23 INFO ] REQ (258) -> {lint}, File = "c:\test.fsx"
Data={"FileName":"c:\\test.fsx"}
[22:15:23 INFO ] RES (258) <- {lint} in 36 ms: Kind={"lint"} 
[22:15:23 INFO ] RES (257) <- {parse} in 99 ms: Kind={"errors"} 
[22:15:23 INFO ] REQ (259) -> {declarations}, File = "c:\test.fsx"
Data={"FileName":"c:\\test.fsx","Version":1}
[22:15:23 INFO ] RES (259) <- {declarations} in 4 ms: Kind={"declarations"} 
`

.fs file output:
`[22:16:00 INFO ] REQ (268) -> {parse}, File = "c:\test2.fs"
Data={"FileName":"c:\\test2.fs","IsAsync":true,"Lines":[""],"Version":1}
[22:16:00 INFO ] REQ (269) -> {lint}, File = "c:\test2.fs"
Data={"FileName":"c:\\test2.fs"}
[22:16:00 INFO ] RES (269) <- {lint} in 3 ms: Kind={"info"} 
[22:16:00 INFO ] RES (268) <- {parse} in 33 ms: Kind={"info"} 
[22:16:01 INFO ] REQ (270) -> {declarations}, File = "c:\test2.fs"
Data={"FileName":"c:\\test2.fs","Version":1}`

**Comment by DaveEmmerson** [comment] 2017-03-02 07:26
vscode 1.10.0
ionide 2.23.5

The tooltip when hovering over the .fsx works (see the last line), as does the help/autocomplete popup when typing. Neither the help nor the popups work on the .fs

Is there any additional debugging that would help? Don't mind putting some breakpoints in the developer console or whatever and grabbing some live values.

test.fs
```
module Test
    let a = 1
```

test.fs.log
```
[Extension Host] [IONIDE-FSAC] REQ (001) -> {parse}, File = "~\test.fs"
Data=Object
[Extension Host] [msbuild] MSBuild found at C:\Program Files (x86)\\MSBuild\14.0\Bin\MSBuild.exe
[Extension Host] [msbuild] MSBuild activated
[Extension Host] [IONIDE-FSAC] RES (001) <- {parse} in 1699 ms: Kind={"info"}
Data=Parse aborted
[Extension Host] [IONIDE-FSAC] REQ (002) -> {parseProjects}, File = "~\test.fs"
Data=Object
[Extension Host] [IONIDE-FSAC] RES (002) <- {parseProjects} in 54 ms: Kind={"errors"}
Data=Object
[Extension Host] [IONIDE-FSAC] REQ (003) -> {lint}, File = "~\test.fs"
Data=Object
[Extension Host] [IONIDE-FSAC] RES (003) <- {lint} in 20 ms: Kind={"info"}
Data=Cached typecheck results not yet available
[Extension Host] [IONIDE-FSAC] REQ (004) -> {completion}, File = "~\test.fs"
Data=Object
[Extension Host] [IONIDE-FSAC] RES (004) <- {completion} ERROR in 19 ms: {SyntaxError: Unexpected token u in JSON at position 0}, Data=%O
[Extension Host] [IONIDE-FSAC] REQ (005) -> {tooltip}, File = "~\test.fs"
Data=Object
[Extension Host] [IONIDE-FSAC] RES (005) <- {tooltip} in 37 ms: Kind={"error"}
Data=Position is out of range
[Extension Host] [IONIDE-FSAC] REQ (006) -> {completion}, File = "~\test.fs"
Data=Object
[Extension Host] [IONIDE-FSAC] RES (006) <- {completion} ERROR in 11 ms: {SyntaxError: Unexpected token u in JSON at position 0}, Data=%O
[Extension Host] [IONIDE-FSAC] REQ (007) -> {tooltip}, File = "~\test.fs"
Data=Object
[Extension Host] [IONIDE-FSAC] RES (007) <- {tooltip} in 16 ms: Kind={"error"}
Data=Position is out of range
[Extension Host] [IONIDE-FSAC] REQ (008) -> {tooltip}, File = "~\test.fs"
Data=Object
[Extension Host] [IONIDE-FSAC] RES (008) <- {tooltip} in 24 ms: Kind={"error"}
Data=Position is out of range
[Extension Host] [IONIDE-FSAC] REQ (009) -> {parse}, File = "~\test.fs"
Data=Object
[Extension Host] [IONIDE-FSAC] REQ (010) -> {lint}, File = "~\test.fs"
Data=Object
[Extension Host] [IONIDE-FSAC] RES (010) <- {lint} in 16 ms: Kind={"info"}
Data=Cached typecheck results not yet available
[Extension Host] [IONIDE-FSAC] RES (009) <- {parse} in 68 ms: Kind={"info"}
Data=Parse aborted
[Extension Host] [IONIDE-FSAC] REQ (011) -> {tooltip}, File = "~\test.fs"
Data=Object
[Extension Host] [IONIDE-FSAC] RES (011) <- {tooltip} in 8 ms: Kind={"error"}
Data=Position is out of range
[Extension Host] [IONIDE-FSAC] REQ (012) -> {completion}, File = "~\test.fs"
Data=Object
[Extension Host] [IONIDE-FSAC] RES (012) <- {completion} ERROR in 8 ms: {SyntaxError: Unexpected token u in JSON at position 0}, Data=%O
[Extension Host] [IONIDE-FSAC] REQ (013) -> {completion}, File = "~\test.fs"
Data=Object
[Extension Host] [IONIDE-FSAC] RES (013) <- {completion} ERROR in 8 ms: {SyntaxError: Unexpected token u in JSON at position 0}, Data=%O
[Extension Host] [IONIDE-FSAC] REQ (014) -> {tooltip}, File = "~\test.fs"
Data=Object
[Extension Host] [IONIDE-FSAC] RES (014) <- {tooltip} in 29 ms: Kind={"error"}
Data=Position is out of range
[Extension Host] [IONIDE-FSAC] REQ (015) -> {tooltip}, File = "~\test.fs"
Data=Object
[Extension Host] [IONIDE-FSAC] RES (015) <- {tooltip} in 14 ms: Kind={"error"}
Data=Position is out of range
[Extension Host] [IONIDE-FSAC] REQ (016) -> {parse}, File = "~\test.fs"
Data=Object
[Extension Host] [IONIDE-FSAC] REQ (017) -> {lint}, File = "~\test.fs"
Data=Object
[Extension Host] [IONIDE-FSAC] RES (017) <- {lint} in 25 ms: Kind={"info"}
Data=Cached typecheck results not yet available
[Extension Host] [IONIDE-FSAC] RES (016) <- {parse} in 41 ms: Kind={"info"}
Data=Parse aborted
```

test.fsx
```
let a = 1
```

test.fsx.log
```
[Extension Host] [IONIDE-FSAC] REQ (043) -> {parse}, File = "~\test.fsx"
Data=Object
[Extension Host] last output: [object Map]
[Extension Host] [IONIDE-FSAC] REQ (044) -> {lint}, File = "~\test.fsx"
Data=Object
[Extension Host] [IONIDE-FSAC] RES (044) <- {lint} in 24 ms: Kind={"lint"}
Data=Array[0]
[Extension Host] [IONIDE-FSAC] RES (043) <- {parse} in 303 ms: Kind={"errors"}
Data=Object
[Extension Host] [IONIDE-FSAC] REQ (045) -> {completion}, File = "~\test.fsx"
Data=Object
[Extension Host] [IONIDE-FSAC] RES (045) <- {completion} in 87 ms: Kind={"completion"}
Data=Array[163]
[Extension Host] [IONIDE-FSAC] REQ (046) -> {helptext}, Symbol = "let"
Data=Object
[Extension Host] [IONIDE-FSAC] RES (046) <- {helptext} in 4 ms: Kind={"error"}
Data=No help text available for symbol 'let'
[Extension Host] [IONIDE-FSAC] REQ (047) -> {helptext}, Symbol = "let"
Data=Object
[Extension Host] [IONIDE-FSAC] RES (047) <- {helptext} in 8 ms: Kind={"error"}
Data=No help text available for symbol 'let'
[Extension Host] [IONIDE-FSAC] REQ (048) -> {completion}, File = "~\test.fsx"
Data=Object
[Extension Host] [IONIDE-FSAC] RES (048) <- {completion} in 133 ms: Kind={"completion"}
Data=Array[198]
[Extension Host] [IONIDE-FSAC] REQ (049) -> {helptext}, Symbol = "abs"
Data=Object
[Extension Host] [IONIDE-FSAC] RES (049) <- {helptext} in 4 ms: Kind={"helptext"}
Data=Object
[Extension Host] [IONIDE-FSAC] REQ (050) -> {tooltip}, File = "~\test.fsx"
Data=Object
[Extension Host] [IONIDE-FSAC] RES (050) <- {tooltip} in 12 ms: Kind={"error"}
Data=Position is out of range
[Extension Host] [IONIDE-FSAC] REQ (051) -> {parse}, File = "~\test.fsx"
Data=Object
[Extension Host] [IONIDE-FSAC] REQ (052) -> {lint}, File = "~\test.fsx"
Data=Object
[Extension Host] [IONIDE-FSAC] RES (052) <- {lint} in 37 ms: Kind={"lint"}
Data=Array[0]
[Extension Host] [IONIDE-FSAC] RES (051) <- {parse} in 152 ms: Kind={"errors"}
Data=Object
[Extension Host] [IONIDE-FSAC] REQ (053) -> {tooltip}, File = "~\test.fsx"
Data=Object
[Extension Host] [IONIDE-FSAC] RES (053) <- {tooltip} in 10 ms: Kind={"tooltip"}
Data=Array[1]
```

**Comment by Hummer311** [comment] 2017-03-11 15:24
I can also reproduce the issue. I used the tour.fs file from https://github.com/dotnet/docs/blob/master/samples/snippets/fsharp/tour.fs

See the attached debug logs for each file.

[tour.fsx.txt](https://github.com/ionide/ionide-vscode-fsharp/files/835875/tour.fsx.txt)
[tour.fs.txt](https://github.com/ionide/ionide-vscode-fsharp/files/835874/tour.fs.txt)

**Comment by lilred** [comment] 2017-03-14 18:42
I've reproduced this on two Windows 10 computers. VS Code 1.10.2, ionide-fsharp 2.23.9.

Did not reproduce on Ubuntu 16.04. VS Code 1.8.1, ionide-fsharp 2.23.9.

Here are the logs from a Windows machine:

F# Language Service (server):

```
Resolving startup promise because FSAC printed the 'listener started' message
[I] 2017-03-14T18:37:42.7678820Z: listener started in 201.086 ms with binding 127.0.0.1:8423 [Suave.Tcp.tcpIpServer]
```

F# Language Service:

```
[14:37:42 INFO ] REQ (001) -> {parse}, File = "c:\Users\Carl\OneDrive\Desktop\test.fs"
Data={"FileName":"c:\\Users\\Carl\\OneDrive\\Desktop\\test.fs","IsAsync":true,"Lines":["let exchange p1 p2 =\r","    let tmp = !p1\r","    p1 := !p2\r","    p2 := tmp\r","\r","l"],"Version":1}
[14:37:46 DEBUG] RES (001) <- {parse} in 3782 ms: Kind={"info"}
Data="Parse aborted"
[14:37:46 INFO ] REQ (002) -> {parseProjects}, File = "c:\Users\Carl\OneDrive\Desktop\test.fs"
Data={"FileName":"c:\\Users\\Carl\\OneDrive\\Desktop\\test.fs"}
[14:37:46 DEBUG] RES (002) <- {parseProjects} in 178 ms: Kind={"errors"}
Data={"File":"c:\\Users\\Carl\\OneDrive\\Desktop\\test.fs","Errors":[{"FileName":"startup","StartLine":1,"EndLine":1,"StartColumn":1,"EndColumn":1,"Severity":"Error","Message":"internal error: BuildFrameworkTcImports: no resolution of 'FSharp.Core, Version=4.4.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'","Subcategory":"typecheck"},{"FileName":"startup","StartLine":1,"EndLine":1,"StartColumn":1,"EndColumn":1,"Severity":"Error","Message":"Could not resolve this reference. Could not locate the assembly \"FSharp.Core, Version=4.4.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. (Code=MSB3245)","Subcategory":"parameter"},{"FileName":"startup","StartLine":1,"EndLine":1,"StartColumn":1,"EndColumn":1,"Severity":"Error","Message":"internal error: BuildFrameworkTcImports: no resolution of 'FSharp.Core, Version=4.4.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'","Subcategory":"typecheck"},{"FileName":"startup","StartLine":1,"EndLine":1,"StartColumn":1,"EndColumn":1,"Severity":"Error","Message":"Could not resolve this reference. Could not locate the assembly \"FSharp.Core, Version=4.4.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. (Code=MSB3245)","Subcategory":"parameter"}]}
[14:37:46 INFO ] REQ (003) -> {lint}, File = "c:\Users\Carl\OneDrive\Desktop\test.fs"
Data={"FileName":"c:\\Users\\Carl\\OneDrive\\Desktop\\test.fs"}
[14:37:46 DEBUG] RES (003) <- {lint} in 50 ms: Kind={"info"}
Data="Cached typecheck results not yet available"
[14:37:47 INFO ] REQ (004) -> {declarations}, File = "c:\Users\Carl\OneDrive\Desktop\test.fs"
Data={"FileName":"c:\\Users\\Carl\\OneDrive\\Desktop\\test.fs","Version":1}
[14:37:47 INFO ] REQ (005) -> {symboluse}, File = "c:\Users\Carl\OneDrive\Desktop\test.fs"
Data={"FileName":"c:\\Users\\Carl\\OneDrive\\Desktop\\test.fs","Line":6,"Column":2,"Filter":""}
[14:37:47 DEBUG] RES (005) <- {symboluse} in 25 ms: Kind={"info"}
Data="Cached typecheck results not yet available"
[14:37:47 INFO ] REQ (006) -> {tooltip}, File = "c:\Users\Carl\OneDrive\Desktop\test.fs"
Data={"FileName":"c:\\Users\\Carl\\OneDrive\\Desktop\\test.fs","Line":6,"Column":2,"Filter":""}
[14:37:47 DEBUG] RES (006) <- {tooltip} in 16 ms: Kind={"info"}
Data="Cached typecheck results not yet available"
[14:37:49 INFO ] REQ (007) -> {tooltip}, File = "c:\Users\Carl\OneDrive\Desktop\test.fs"
Data={"FileName":"c:\\Users\\Carl\\OneDrive\\Desktop\\test.fs","Line":6,"Column":1,"Filter":""}
[14:37:49 DEBUG] RES (007) <- {tooltip} in 17 ms: Kind={"info"}
Data="Cached typecheck results not yet available"
[14:37:50 INFO ] REQ (008) -> {parse}, File = "c:\Users\Carl\OneDrive\Desktop\test.fs"
Data={"FileName":"c:\\Users\\Carl\\OneDrive\\Desktop\\test.fs","IsAsync":true,"Lines":["let exchange p1 p2 =\r","    let tmp = !p1\r","    p1 := !p2\r","    p2 := tmp\r","\r",""],"Version":2}
[14:37:50 INFO ] REQ (009) -> {lint}, File = "c:\Users\Carl\OneDrive\Desktop\test.fs"
Data={"FileName":"c:\\Users\\Carl\\OneDrive\\Desktop\\test.fs"}
[14:37:50 DEBUG] RES (009) <- {lint} in 42 ms: Kind={"info"}
Data="Cached typecheck results not yet available"
[14:37:50 DEBUG] RES (008) <- {parse} in 81 ms: Kind={"info"}
Data="Parse aborted"
[14:37:55 INFO ] REQ (010) -> {tooltip}, File = "c:\Users\Carl\OneDrive\Desktop\test.fs"
Data={"FileName":"c:\\Users\\Carl\\OneDrive\\Desktop\\test.fs","Line":4,"Column":14,"Filter":""}
[14:37:56 DEBUG] RES (010) <- {tooltip} in 66 ms: Kind={"info"}
Data="Cached typecheck results not yet available"
[14:37:56 INFO ] REQ (011) -> {tooltip}, File = "c:\Users\Carl\OneDrive\Desktop\test.fs"
Data={"FileName":"c:\\Users\\Carl\\OneDrive\\Desktop\\test.fs","Line":5,"Column":5,"Filter":""}
[14:37:56 DEBUG] RES (011) <- {tooltip} in 62 ms: Kind={"error"}
Data="Position is out of range"
[14:37:57 INFO ] REQ (012) -> {parse}, File = "c:\Users\Carl\OneDrive\Desktop\test.fs"
Data={"FileName":"c:\\Users\\Carl\\OneDrive\\Desktop\\test.fs","IsAsync":true,"Lines":["let exchange p1 p2 =\r","    let tmp = !p1\r","    p1 := !p2\r","    p2 := tmp\r","    "],"Version":8}
[14:37:57 INFO ] REQ (013) -> {lint}, File = "c:\Users\Carl\OneDrive\Desktop\test.fs"
Data={"FileName":"c:\\Users\\Carl\\OneDrive\\Desktop\\test.fs"}
[14:37:57 DEBUG] RES (013) <- {lint} in 41 ms: Kind={"info"}
Data="Cached typecheck results not yet available"
[14:37:57 DEBUG] RES (012) <- {parse} in 88 ms: Kind={"info"}
Data="Parse aborted"
[14:37:58 INFO ] REQ (014) -> {tooltip}, File = "c:\Users\Carl\OneDrive\Desktop\test.fs"
Data={"FileName":"c:\\Users\\Carl\\OneDrive\\Desktop\\test.fs","Line":4,"Column":14,"Filter":""}
[14:37:58 DEBUG] RES (014) <- {tooltip} in 15 ms: Kind={"info"}
Data="Cached typecheck results not yet available"
[14:37:58 INFO ] REQ (015) -> {parse}, File = "c:\Users\Carl\OneDrive\Desktop\test.fs"
Data={"FileName":"c:\\Users\\Carl\\OneDrive\\Desktop\\test.fs","IsAsync":true,"Lines":["let exchange p1 p2 =\r","    let tmp = !p1\r","    p1 := !p2\r","    p2 := tmp"],"Version":11}
[14:37:58 INFO ] REQ (016) -> {lint}, File = "c:\Users\Carl\OneDrive\Desktop\test.fs"
Data={"FileName":"c:\\Users\\Carl\\OneDrive\\Desktop\\test.fs"}
[14:37:58 DEBUG] RES (016) <- {lint} in 47 ms: Kind={"info"}
Data="Cached typecheck results not yet available"
[14:37:58 DEBUG] RES (015) <- {parse} in 87 ms: Kind={"info"}
Data="Parse aborted"
[14:37:59 INFO ] REQ (017) -> {tooltip}, File = "c:\Users\Carl\OneDrive\Desktop\test.fs"
Data={"FileName":"c:\\Users\\Carl\\OneDrive\\Desktop\\test.fs","Line":1,"Column":1,"Filter":""}
[14:37:59 DEBUG] RES (017) <- {tooltip} in 62 ms: Kind={"info"}
Data="Cached typecheck results not yet available"
[14:38:00 INFO ] REQ (018) -> {parse}, File = "c:\Users\Carl\OneDrive\Desktop\test.fs"
Data={"FileName":"c:\\Users\\Carl\\OneDrive\\Desktop\\test.fs","IsAsync":true,"Lines":[""],"Version":14}
[14:38:00 INFO ] REQ (019) -> {lint}, File = "c:\Users\Carl\OneDrive\Desktop\test.fs"
Data={"FileName":"c:\\Users\\Carl\\OneDrive\\Desktop\\test.fs"}
[14:38:00 DEBUG] RES (019) <- {lint} in 19 ms: Kind={"info"}
Data="Cached typecheck results not yet available"
[14:38:00 DEBUG] RES (018) <- {parse} in 76 ms: Kind={"info"}
Data="Parse aborted"
[14:38:13 INFO ] REQ (020) -> {parse}, File = "c:\Users\Carl\OneDrive\Desktop\test.fs"
Data={"FileName":"c:\\Users\\Carl\\OneDrive\\Desktop\\test.fs","IsAsync":true,"Lines":[""],"Version":14}
[14:38:13 INFO ] REQ (021) -> {lint}, File = "c:\Users\Carl\OneDrive\Desktop\test.fs"
Data={"FileName":"c:\\Users\\Carl\\OneDrive\\Desktop\\test.fs"}
[14:38:13 DEBUG] RES (021) <- {lint} in 14 ms: Kind={"info"}
Data="Cached typecheck results not yet available"
[14:38:13 DEBUG] RES (020) <- {parse} in 78 ms: Kind={"info"}
Data="Parse aborted"
[14:38:19 INFO ] REQ (022) -> {parse}, File = "c:\Users\Carl\OneDrive\Desktop\test.fs"
Data={"FileName":"c:\\Users\\Carl\\OneDrive\\Desktop\\test.fs","IsAsync":true,"Lines":[""],"Version":14}
[14:38:19 INFO ] REQ (023) -> {lint}, File = "c:\Users\Carl\OneDrive\Desktop\test.fs"
Data={"FileName":"c:\\Users\\Carl\\OneDrive\\Desktop\\test.fs"}
[14:38:19 DEBUG] RES (023) <- {lint} in 41 ms: Kind={"info"}
Data="Cached typecheck results not yet available"
[14:38:19 DEBUG] RES (022) <- {parse} in 86 ms: Kind={"info"}
Data="Parse aborted"
[14:38:22 INFO ] REQ (024) -> {parse}, File = "c:\Users\Carl\OneDrive\Desktop\test.fs"
Data={"FileName":"c:\\Users\\Carl\\OneDrive\\Desktop\\test.fs","IsAsync":true,"Lines":[""],"Version":14}
[14:38:22 INFO ] REQ (025) -> {lint}, File = "c:\Users\Carl\OneDrive\Desktop\test.fs"
Data={"FileName":"c:\\Users\\Carl\\OneDrive\\Desktop\\test.fs"}
[14:38:22 DEBUG] RES (025) <- {lint} in 17 ms: Kind={"info"}
Data="Cached typecheck results not yet available"
[14:38:22 DEBUG] RES (024) <- {parse} in 46 ms: Kind={"info"}
Data="Parse aborted"
[14:38:41 INFO ] REQ (026) -> {parse}, File = "c:\Users\Carl\OneDrive\Desktop\test.fs"
Data={"FileName":"c:\\Users\\Carl\\OneDrive\\Desktop\\test.fs","IsAsync":true,"Lines":[""],"Version":14}
[14:38:41 INFO ] REQ (027) -> {lint}, File = "c:\Users\Carl\OneDrive\Desktop\test.fs"
Data={"FileName":"c:\\Users\\Carl\\OneDrive\\Desktop\\test.fs"}
[14:38:41 DEBUG] RES (027) <- {lint} in 50 ms: Kind={"info"}
Data="Cached typecheck results not yet available"
[14:38:41 DEBUG] RES (026) <- {parse} in 225 ms: Kind={"info"}
Data="Parse aborted"
[14:40:01 INFO ] REQ (028) -> {parse}, File = "c:\Users\Carl\OneDrive\Desktop\test.fs"
Data={"FileName":"c:\\Users\\Carl\\OneDrive\\Desktop\\test.fs","IsAsync":true,"Lines":[""],"Version":14}
[14:40:01 INFO ] REQ (029) -> {lint}, File = "c:\Users\Carl\OneDrive\Desktop\test.fs"
Data={"FileName":"c:\\Users\\Carl\\OneDrive\\Desktop\\test.fs"}
[14:40:01 DEBUG] RES (029) <- {lint} in 54 ms: Kind={"info"}
Data="Cached typecheck results not yet available"
[14:40:01 DEBUG] RES (028) <- {parse} in 100 ms: Kind={"info"}
Data="Parse aborted"
[14:40:17 INFO ] REQ (030) -> {parse}, File = "c:\Users\Carl\OneDrive\Desktop\test.fs"
Data={"FileName":"c:\\Users\\Carl\\OneDrive\\Desktop\\test.fs","IsAsync":true,"Lines":[""],"Version":14}
[14:40:17 INFO ] REQ (031) -> {lint}, File = "c:\Users\Carl\OneDrive\Desktop\test.fs"
Data={"FileName":"c:\\Users\\Carl\\OneDrive\\Desktop\\test.fs"}
[14:40:17 DEBUG] RES (031) <- {lint} in 17 ms: Kind={"info"}
Data="Cached typecheck results not yet available"
[14:40:17 DEBUG] RES (030) <- {parse} in 74 ms: Kind={"info"}
Data="Parse aborted"
[14:41:13 INFO ] REQ (032) -> {parse}, File = "c:\Users\Carl\OneDrive\Desktop\test.fs"
Data={"FileName":"c:\\Users\\Carl\\OneDrive\\Desktop\\test.fs","IsAsync":true,"Lines":[""],"Version":14}
[14:41:13 INFO ] REQ (033) -> {lint}, File = "c:\Users\Carl\OneDrive\Desktop\test.fs"
Data={"FileName":"c:\\Users\\Carl\\OneDrive\\Desktop\\test.fs"}
[14:41:13 DEBUG] RES (033) <- {lint} in 16 ms: Kind={"info"}
Data="Cached typecheck results not yet available"
[14:41:13 DEBUG] RES (032) <- {parse} in 43 ms: Kind={"info"}
Data="Parse aborted"
[14:41:16 INFO ] REQ (034) -> {parse}, File = "c:\Users\Carl\OneDrive\Desktop\test.fs"
Data={"FileName":"c:\\Users\\Carl\\OneDrive\\Desktop\\test.fs","IsAsync":true,"Lines":[""],"Version":14}
[14:41:16 INFO ] REQ (035) -> {lint}, File = "c:\Users\Carl\OneDrive\Desktop\test.fs"
Data={"FileName":"c:\\Users\\Carl\\OneDrive\\Desktop\\test.fs"}
[14:41:16 DEBUG] RES (035) <- {lint} in 100 ms: Kind={"info"}
Data="Cached typecheck results not yet available"
[14:41:17 DEBUG] RES (034) <- {parse} in 171 ms: Kind={"info"}
Data="Parse aborted"
[14:41:29 INFO ] REQ (036) -> {parse}, File = "c:\Users\Carl\OneDrive\Desktop\test.fs"
Data={"FileName":"c:\\Users\\Carl\\OneDrive\\Desktop\\test.fs","IsAsync":true,"Lines":[""],"Version":14}
[14:41:29 INFO ] REQ (037) -> {lint}, File = "c:\Users\Carl\OneDrive\Desktop\test.fs"
Data={"FileName":"c:\\Users\\Carl\\OneDrive\\Desktop\\test.fs"}
[14:41:29 DEBUG] RES (037) <- {lint} in 79 ms: Kind={"info"}
Data="Cached typecheck results not yet available"
[14:41:29 DEBUG] RES (036) <- {parse} in 98 ms: Kind={"info"}
Data="Parse aborted"
[14:41:30 INFO ] REQ (038) -> {parse}, File = "c:\Users\Carl\OneDrive\Desktop\test.fs"
Data={"FileName":"c:\\Users\\Carl\\OneDrive\\Desktop\\test.fs","IsAsync":true,"Lines":[""],"Version":14}
[14:41:30 INFO ] REQ (039) -> {lint}, File = "c:\Users\Carl\OneDrive\Desktop\test.fs"
Data={"FileName":"c:\\Users\\Carl\\OneDrive\\Desktop\\test.fs"}
[14:41:30 DEBUG] RES (039) <- {lint} in 47 ms: Kind={"info"}
Data="Cached typecheck results not yet available"
[14:41:30 DEBUG] RES (038) <- {parse} in 73 ms: Kind={"info"}
Data="Parse aborted"
```

**Comment by lilred** [comment] 2017-03-17 01:46
@Krzysztof-Cieslak: Do you know if this affects all Windows 10 machines?

**Comment by DaveEmmerson** [comment] 2017-03-22 17:14
Creating a new project from the CLI and opening that now works for me (followed https://twitter.com/enricosada/status/843569801448570881).

Looked at the .fsproj and it had some differences from the one I was using, so I amended mine to match and my project now has intellisense and error squigglies, etc.

👍

**Comment by Krzysztof-Cieslak** [comment] 2017-03-31 15:55
Should be fixed in `2.25.7`

**Closed by Krzysztof-Cieslak** 2017-03-31 15:55 UTC
Labels: bug, language services (FSAC / FCS / Project Cracker), up for grabs

**Comment by hasparus** [comment] 2019-02-11 20:24
Syntax highlighting and intellisense don't work in `.fs` files for me. `.fsx` files are okay though.

**Comment by amatiasq** [comment] 2020-05-12 21:07
Idem, same message as OP.

I've just done "Reload window" on VS Code and lost al intellisense for 10 mins now.

```
[Error - 11:06:02 PM] Request textDocument/hover failed.
  Message: Cached typecheck results not yet available
  Code: -32603 
[Error - 11:06:24 PM] Request textDocument/hover failed.
  Message: Cached typecheck results not yet available
  Code: -32603 
[Error - 11:06:25 PM] Request textDocument/definition failed.
  Message: Cached typecheck results not yet available
  Code: -32603 
[Error - 11:06:25 PM] Request textDocument/hover failed.
  Message: Cached typecheck results not yet available
  Code: -32603
```

**Comment by CherenkovLiu** [comment] 2020-08-08 04:25
It seems that you could try "Select Language Mode" in VS Code, probably ".fs" is associated with other files, e.g. GLSL file like in my VS code which caused the intellisense unable to work, that should be OK

**Comment by nuvem565** [comment] 2021-09-06 08:49
I have something similar. I cannot to use intellisense but syntax highlighting is fine. It pertains only to .fs files. There is a yellow message on status bar below: "Not in a F# project (still loading)" and VSC error on click: "Running the contributed command: 'fsharp.AddFileToProject' failed". I managed with it by installing "F# language support" extension which is deprecated by itself (added to F#), I think.

**Comment by general-rishkin** [comment] 2023-08-14 10:59
I am also experiencing this issue. I am on VSCode version 1.81.1 on Ubuntu 22.04 and .NET sdk 7.0.306.
