### ISSUE TITLE
FSAC fails to start (unhandled module resolution exception)

### ISSUE THREAD

**Issue by piaste** [ionide/ionide-vscode-fsharp#373] opened 2017-02-24 00:09 UTC
**Ionide version**: 2.23.3
**Platform**: Windows 10 x64
**Tooling installed**: F# 4.1, VS2017 RC4 w/ MSBuild 14.0

Opening a f# project gives the message:

>Failed to start language services. Please check if Microsoft Build Tools 2013 are installed

Manually setting the `FSharp.msbuildLocation` configuration option to point at MSBuild 14.0 has no effect. Neither does installing MSBuild 2013 (12.0), just in case.

Turns out the error in Event Viewer is:

```
Application: FsAutoComplete.Suave.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileLoadException

Exception Info: System.IO.FileLoadException
   at System.ModuleHandle.ResolveType(System.Reflection.RuntimeModule, Int32, IntPtr*, Int32, IntPtr*, Int32, System.Runtime.CompilerServices.ObjectHandleOnStack)
   at System.ModuleHandle.ResolveTypeHandleInternal(System.Reflection.RuntimeModule, Int32, System.RuntimeTypeHandle[], System.RuntimeTypeHandle[])
   at System.Reflection.RuntimeModule.ResolveType(Int32, System.Type[], System.Type[])
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(System.Reflection.CustomAttributeRecord, System.Reflection.MetadataImport, System.Reflection.Assembly ByRef, System.Reflection.RuntimeModule, System.Reflection.MetadataToken, System.RuntimeType, Boolean, System.Object[], System.Collections.IList, System.RuntimeType ByRef, System.IRuntimeMethodInfo ByRef, Boolean ByRef, Boolean ByRef)
   at System.Reflection.CustomAttribute.GetCustomAttributes(System.Reflection.RuntimeModule, Int32, Int32, System.RuntimeType, Boolean, System.Collections.IList, Boolean)
   at System.Reflection.CustomAttribute.GetCustomAttributes(System.Reflection.RuntimeAssembly, System.RuntimeType)
   at System.Attribute.GetCustomAttributes(System.Reflection.Assembly, System.Type, Boolean)
   at System.AppDomain.GetTargetFrameworkName()

```

**Comment by Krzysztof-Cieslak** [comment] 2017-02-24 17:46
Given that you have VS2017 installed I assume it's duplicate of https://github.com/ionide/ionide-vscode-fsharp/issues/291

**Closed by Krzysztof-Cieslak** 2017-02-24 17:46 UTC
