### ISSUE TITLE
Definition of the (^) operator breaks linelens

### ISSUE THREAD

**Issue by Savelenko** [ionide/ionide-vscode-fsharp#1304] opened 2020-02-11 15:34 UTC
When a module contains a top-level definition of the `^` operator, linelens (I believe it is called like that, sorry) does not work.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add a file with the following module definition to a project and open the project with VS Code/Ionide.

~~~
module Test

let (^) f x = f x
let (<*>) f x = f x

let a = 1

let b = id ^ "string"
~~~

2. There will be no linelens type annotations.

3. Comment the definition of `^`. Linelens type annotations immediately appear.

4. Uncomment the definition of `^`. Linelens type annotations remain visible.

5. Change the definition of `a` to `true`. Linelens type annotation does not get updated.

6. Comment the definition of `^` again. Linelens type annotation of `a` immediately updates.

**Expected behaviour**
Linelens works in presence of a `^` operator definition similarly to when no such definition is present.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Ionide version: 4.5.0
 - VSCode version: 1.42.0
 - dotnet SDK version: 3.1.101

**Comment by Krzysztof-Cieslak** [comment] 2020-12-14 18:05
I guess it's duplicate of #1203

**Closed by Krzysztof-Cieslak** 2020-12-14 18:05 UTC
Labels: bug, language services
