### ISSUE TITLE
Ionide freezes when adding # at end of double-backtick marks encosed identifiers

### ISSUE THREAD

**Issue by dbrattli** [ionide/ionide-vscode-fsharp#1427] opened 2020-10-10 10:52 UTC
**Describe the bug**
Ionide (code-helper) freezes when adding characters such as e.g `#` to the end of identifiers enclosed in double-backtick marks. The CPU load will increase with the size of the identifier, typically with identifiers with more than 24 characters. This is quite normal with e.g test files.

**To Reproduce**
Steps to reproduce the behaviour:

Create an identifier such as

```fs
let ``123456789012345678901234``() =
    ()
```

Then add a `#` to the end of the name and notice Ionide starting to become sluggish:

```fs
let ``123456789012345678901234#``() =
    ()
```
From 25 characters and more, Ionide becomes more unresponsive. E.g:

```fs
let ``1234567890123456789012345#``() =
    ()
```

From 29 characters Ionide is no longer responding:

<img width="579" alt="Screenshot 2020-10-10 at 12 48 10" src="https://user-images.githubusercontent.com/849479/95653183-fb57cd00-0af6-11eb-9689-0146a6450d65.png">

**Expected behaviour**

Ionide should not get unresponsive no matter the size of the identifiers having chars such as `#` added to them.

**Environment (please complete the following information):**
 - OS: Mac OS X, Windows 10
 - Ionide version: 4.17.0
 - VSCode version: 1.50.0
 - dotnet SDK version: 3.0.402
 - mono / .Net Framework version: N/A

**Additional context**

The bug only happens when you add e.g `#` to the end (after 24 chars) of the identifier. Adding to the start (before 24 chars) does not effect performance even if the identifier is longer than e.g 25 characters.

I think the bug have been present in Ionide for a very long time.

**Comment by Krzysztof-Cieslak** [comment] 2020-10-23 12:15
Duplicate of #1073

**Closed by Krzysztof-Cieslak** 2020-10-23 12:15 UTC
