### ISSUE TITLE
Setting proxy in environment variable results in F# language service Error: socket hang up

### ISSUE THREAD

**Issue by rusanov-vladimir** [ionide/ionide-vscode-fsharp#747] opened 2018-03-21 12:51 UTC
I'm using VS Code on windows 10 behind corporate proxy. I've setup proxy in windows environment variables:
![2018-03-21_14h06_42](https://user-images.githubusercontent.com/3341799/37708957-44ca7102-2d11-11e8-8b07-1b47ca884aec.png)
So when opening a F# solution I have no intellisense, F# project explorer and all the stuff needed and in F# Language Service I see:
![2018-03-21_14h10_42](https://user-images.githubusercontent.com/3341799/37709065-a7122422-2d11-11e8-9cb4-b45ab5ed9033.png)
If I remove the proxy from environment variables and use `"http.proxy": "http://my-proxy:3128",` in settings.json instead everything seems to be running smoothly again.
Is it the expected behavior?

**Comment by vbfox** [comment] 2018-03-21 15:10
Duplicate of #272 (and a few others).

Now that axios merged my PR and did a release, this should be easily solvable.

**Closed** 2018-03-21 15:13 UTC
