### ISSUE TITLE
Missing optdata and sigdata

### ISSUE THREAD

**Issue by mastoj** [ionide/ionide-vscode-fsharp#433] opened 2017-05-11 09:30 UTC
I don't know when this bug first surfaced, but it seems like the optdata and sigdata is not in the extensions bin folder. I added them manually from another project I have to the extensions folder and things began to work again. I don't know where to add it in ionide though.

System info:
OS: OSX 
Mono verison: 5.0.0.48
Ionide-Fsharp version: 2.25.12

**Comment by Krzysztof-Cieslak** [comment] 2017-05-11 09:31
Has it ever been there? ;)

**Comment by mastoj** [comment] 2017-05-11 09:32
Not sure... don't even know why I need it, I just followed the error messages :)

**Comment by Krzysztof-Cieslak** [comment] 2017-05-11 09:39
Maybe you don't have F# 4.0 installed?

**Comment by Krzysztof-Cieslak** [comment] 2017-05-11 09:39
Oh, mono... nvm

**Comment by Krzysztof-Cieslak** [comment] 2017-05-11 09:40
I guess it has something to do with the fact that mono 5 bundles F# 4.1... so maybe it can't find optdata / sigdata for 4.0 FSharp.Core

**Comment by mastoj** [comment] 2017-05-11 10:03
but it did work before, that's why I think it is strange. Hmm... maybe I updated mono?

**Comment by Krzysztof-Cieslak** [comment] 2017-05-11 10:30
If you updated XS / VS for Mac recently it included mono update AFAIK.

**Comment by mastoj** [comment] 2017-05-11 12:46
ok, maybe it is that. 

With that said, should ionide includ sigdata and optdata to be sure to run?

**Comment by rojepp** [comment] 2017-05-11 13:19
@mastoj For some some context, .sigdata and .optdata are resource files that are usually baked into assemblies compiled by fsc (or fsharpc in your case). They were recently [baked into the FSharp.Core assembly](https://github.com/Microsoft/visualfsharp/commit/4fcfb8b6e16804105cab8d7500e82530cd1b8500), just like every other F# assembly (consistency, yay!). 

Older versions of the F# compiler will still special-case FSharp.Core.dll and look for these files next to it. Are you on an older compiler? What does `fsharpi` in terminal tell you? 
Are you using FSharp.Core from Nuget?

**Comment by mastoj** [comment] 2017-05-11 13:48
@rojepp, thanks for adding context.

`fsharpi`- F# Interactive for F# 4.1

Not sure which version of `FSharp.Core` that ionide is using, but when I added the optdata and sigdata files to the extension of ionide, next to `FSharp.Core`, everything started working.

**Comment by Krzysztof-Cieslak** [comment] 2017-05-11 14:09
> Are you using FSharp.Core from Nuget?

As I understand the problem is not with @mastoj's project but with FSAC. 

FSAC is compiled against F# 4.0 (4.0.0.1 from NuGet) and probably latest mono is lacking ` .sigdata` and `.optdata` for FSharp.Core 4.0. We have 2 solutions - either bump FSharp.Core version to latest (not requiring separate `.sigdata` and `.optdata`) or distribute `.sigdata` and `.optdata` for FSharp.Core 4.0 together with Ionide.

**Comment by mastoj** [comment] 2017-05-11 14:11
Isn't ionide using the version of `FSharp.Core` that's in the extensions folder, how is my version of mono affecting that? Just trying to understand.

**Comment by Krzysztof-Cieslak** [comment] 2017-05-11 15:32
As far as I know, there are several places when runtime looks for the `.sigdata` and `.optdata` - next to the FSharp.Core.dll and in couple of global locations (no idea what's that in case of the mono).  Since we don't  distribute  `.sigdata` and `.optdata` next to `FSharp.Core.dll`  in `bin` folder, I *think* that runtime tries to find those file in some global locations and they're probably not there (since mono 5 bundles F# 4.1).

At least, that's my understanding of the problem... it might be completely wrong ;)

**Comment by mastoj** [comment] 2017-05-11 18:42
You're probably more right than me :)

I didn't check all the locations it were looking for, I just noticed that the runtime looked in the extension bin folder. 

However, the question still stands, should those file be included in the extension? My guess is that more people than me have the same versions of fsharp, mono and other relevant pieces and will cause them problem as well.

**Comment by mastoj** [comment] 2017-05-11 20:47
Downgraded to latest stable versiopn of mono, 4.8.1, and now it works again.

**Comment by 7sharp9** [comment] 2017-05-14 18:07
5.2 work fine

**Comment by sergey-tihon** [comment] 2017-05-14 18:26
Mono 5.0 is bad mono.

As I understand (know) mono team merges mono with corefx, to have an implementation as close to .net core as possible as it possible. And Mono 5.0 released include corefx forked approximately around 2017/02 (and a lot of bug where fixed since then)

We found that Fsharp.Data Http module does not work on Mono 5, because this fix https://github.com/dotnet/corefx/commit/a6c7e23421701870c1eb855eae95e4605e5b04b3 is not included in the release.

The good part is that Miguel promised that they will do their best to release next Mono asap
https://github.com/fsharp/FSharp.Data/issues/1053#issuecomment-301138733

Also, FCS story is not perfect on Mono, especially on Mono 5 https://github.com/fsharp/FSharp.Compiler.Service/pull/772

So for now, is better to wait and continue with 4.8.1 or install 5.2 or nightly release (5.3)

**Closed** 2017-05-22 21:02 UTC
