### ISSUE TITLE
Measure names show up as numbers in tooltip

### ISSUE THREAD

**Issue by onionhammer** [ionide/ionide-vscode-fsharp#1332] opened 2020-03-27 21:34 UTC
Ionide FSharp 4.8.1, when you hover over a measurement it shows a number rather than the name of the measurement

![image](https://user-images.githubusercontent.com/969938/77802334-a49e1080-7048-11ea-9603-5628d6880416.png)

```F#
open System
open Microsoft.FSharp.Data.UnitSystems.SI.UnitNames
open Microsoft.FSharp.Data.UnitSystems.SI.UnitSymbols

let PI = Math.PI

// Angular velocity
let ω (period: float<s>) = 
    (2.0 * PI) / period
```

**Comment by Krzysztof-Cieslak** [comment] 2020-04-14 13:17
I can't reproduce exactly this one.... in my case thing looks a bit differently 🙄

![image](https://user-images.githubusercontent.com/5427083/79229234-f7f2ca00-7e62-11ea-8f7e-f502ea011d88.png)

**Comment by onionhammer** [comment] 2020-04-14 20:37
@Krzysztof-Cieslak hmm, I'm on Mac OS with netcore 3.1 (and 5 preview) installed, and ionide 4.9.0 now. Same issue

**Comment by Krzysztof-Cieslak** [comment] 2021-11-19 15:46
This seems to be fixed on latest Ionide 
<img width="292" alt="Screenshot 2021-11-19 at 16 46 13" src="https://user-images.githubusercontent.com/5427083/142650929-a044afb9-8ed1-47f6-a5c6-fabe5d7c37ae.png">

**Closed by Krzysztof-Cieslak** 2021-11-19 15:46 UTC
Labels: bug
