### ISSUE TITLE
LSP crash due to string length not valid during FsAutoComplete.NamedText.GetText(Range m)

### ISSUE THREAD

**Issue by fwaris** [ionide/ionide-vscode-fsharp#1786] opened 2022-09-27 19:57 UTC
Here is the stack trace (prob. needs a length check):
```
[19:10:51.553 ERR] [Startup] Start - LSP mode crashed
System.AggregateException: One or more errors occurred. (Index and length must refer to a location within the string. (Parameter 'length'))
 ---> System.ArgumentOutOfRangeException: Index and length must refer to a location within the string. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at FsAutoComplete.NamedText.GetText(Range m) in /home/runner/work/FsAutoComplete/FsAutoComplete/src/FsAutoComplete.Core/FileSystem.fs:line 134
   at FsAutoComplete.Lsp.getLineText@915.Invoke(NamedText lines, Range range) in /home/runner/work/FsAutoComplete/FsAutoComplete/src/FsAutoComplete/FsAutoComplete.Lsp.fs:line 915
   at FsAutoComplete.CodeFix.AddMissingFunKeyword.binder@1-2(FSharpFunc`2 getLineText, Diagnostic diagnostic, CodeActionParams codeActionParams, NamedText lines) in /home/runner/work/FsAutoComplete/FsAutoComplete/src/FsAutoComplete/CodeFixes/AddMissingFunKeyword.fs:line 19
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, b result1, FSharpFunc`2 userCode) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 465
   at Microsoft.FSharp.Control.AsyncActivation`1.Success(AsyncActivation`1 ctxt, T result) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 324
   at FsToolkit.ErrorHandling.AsyncResult.retn@39.Invoke(AsyncActivation`1 ctxt)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 104
   --- End of inner exception stack trace ---
   at Ionide.LanguageServerProtocol.Server.startWithSetup[client](FSharpFunc`2 setupRequestHandlings, Stream input, Stream output, FSharpFunc`2 clientCreator, FSharpFunc`2 customizeRpc) in /_//src/LanguageServerProtocol.fs:line 179
   at Ionide.LanguageServerProtocol.Server.start@268-2.Invoke(FSharpFunc`2 customizeRpc) in /_//src/LanguageServerProtocol.fs:line 268
   at FsAutoComplete.Lsp.startCore(ToolsPath toolsPath, DirectoryInfo stateStorageDir, FSharpFunc`2 workspaceLoaderFactory) in /home/runner/work/FsAutoComplete/FsAutoComplete/src/FsAutoComplete/FsAutoComplete.Lsp.fs:line 2947
   at FsAutoComplete.Lsp.start(ToolsPath toolsPath, DirectoryInfo stateStorageDir, FSharpFunc`2 workspaceLoaderFactory) in /home/runner/work/FsAutoComplete/FsAutoComplete/src/FsAutoComplete/FsAutoComplete.Lsp.fs:line 2959
[Error - 7:10:51 PM] The F# server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```

**Comment by baronfel** [comment] 2022-09-27 20:12
Duplicate of #1786

**Closed** 2022-09-27 20:13 UTC
