### ISSUE TITLE
"Problem reading assembly" after `dotnet build` succeeds

### ISSUE THREAD

**Issue by samuela** [ionide/ionide-vscode-fsharp#924] opened 2018-09-24 23:58 UTC
Ionide is still showing some red squiggles after a successful `dotnet build`. Hovering over one of the errors shows a "Problem reading assembly" exception.

Screenshot attached.

![screen shot 2018-09-24 at 4 54 16 pm](https://user-images.githubusercontent.com/226872/45985423-05dfc080-c01b-11e8-82a4-db0c1a48256b.png)

**Comment by Krzysztof-Cieslak** [comment] 2018-10-11 22:30
Is the project OSSed or can you provide some minimal reproduction of the problem?

**Comment by samuela** [comment] 2018-10-11 22:33
@Krzysztof-Cieslak Project is OSSed here: https://github.com/samuela/grpc-polyglot!

**Comment by JonathanMEdwards** [comment] 2018-10-15 01:59
Here is another version of the problem.

<img width="1440" alt="screen shot 2018-10-14 at 9 52 34 pm" src="https://user-images.githubusercontent.com/2237165/46925752-95b1d280-cffb-11e8-9530-e2caed2dd05f.png">

Repo: https://github.com/JonathanMEdwards/subtext

### Machine infos

* Operating system: **Darwin**
* Arch: **x64**
* VSCode: **1.28.1**
* Runtime: **netcore**
* Dotnet version: **2.1.403**
* Runtime: **.Net**
* Mono version:
```shell
Mono JIT compiler version 5.16.0.179 (2018-06/6e48ad4f7b1 Wed Oct  3 14:05:19 EDT 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(3.6.0svn-mono-master/0b3cb8ac12c)
	GC:            sgen (concurrent by default)
```
* MSBuild version:
```shell
Microsoft (R) Build Engine version 16.0.40-preview+ge6c3a1f9e4 for Mono
Copyright (C) Microsoft Corporation. All rights reserved.
```

**Comment by JonathanMEdwards** [comment] 2018-10-15 13:53
@samuela are you on Windows?

**Comment by mvsmal** [comment] 2018-10-15 15:14
I have the same issue in a project which has a dependency on another project. It happens when I add new file to the project. Sometimes rebuild helps.

**Comment by samuela** [comment] 2018-10-15 17:44
@JonathanMEdwards I'm on macOS 10.14.

**Comment by samuela** [comment] 2018-10-15 17:45
I also have two projects with one referencing the other, though I'm not sure exactly how to reproduce.

**Comment by JonathanMEdwards** [comment] 2018-10-15 19:20
So the common thread is inter-project dependencies on Mac? @mvsmal are you on Mac too?
After struggling for days to get a working Mac configuration I am starting to think I need to be on Windows to do F# dev.

**Comment by Binjaaa** [comment] 2018-10-15 20:01
I had this issue today. I was trying to add a new file to an F# project but even building successfully VSCode (Ionide) just marked my new file red along with all the files in my project.
Tried, rebuild, clean, git clean -xfd, closing VSCode, restarting machine, nothing.
Not sure it's the exact solution to this, but did the trick for me.

Set the **"FSharp.fsacRuntime": "net"**, settings in my workspace to use **"netcore"**

**Comment by JonathanMEdwards** [comment] 2018-10-15 20:20
I already have fsacRuntime set to netcore, so sounds like a different issue

**Comment by samuela** [comment] 2018-10-15 20:51
@Binjaaa I've also had that issue, but I don't think I've bothered to report it before. Definitely very annoying. Cleaning and rebuilding always does it for me. I also have FSharp.fsacRuntime set to netcore, but I've still seen it.

**Comment by cannorin** [comment] 2018-10-16 08:30
Sorry, it became unreproducible just after submitting the above comment.. :thinking:

**Comment by cannorin** [comment] 2018-10-16 08:50
OK, now I can reproduce it.

### Source-only state

```
```

**Comment by Binjaaa** [comment] 2018-10-17 16:20
@Krzysztof-Cieslak : Made a minimal repro on this.
Repro steps:
1. Created 2 F# projects **Main** and **Sub**
2. Set Sub as a reference to Main
3. Added a new file via the context menu in Main
4. Referenced the new file manually in the MainProject.fsproj
5. Saved the .fsproj modifications
6. There we go!

Here is my basic repro, hopefully going to give you the same behavior:
https://github.com/Binjaaa/ionide-dll-read-error-repo

**Comment by Krzysztof-Cieslak** [comment] 2018-10-18 09:17
@Binjaaa Can't reproduce the problem.

<img width="1680" alt="screen shot 2018-10-18 at 11 15 06" src="https://user-images.githubusercontent.com/5427083/47144251-5919fb80-d2c7-11e8-9fb0-0ecd88461710.png">

**Comment by Krzysztof-Cieslak** [comment] 2018-10-22 14:34
o_O

**Comment by mvsmal** [comment] 2018-10-22 14:58
It looks so :) I will keep on eye on it for some time. 
Thanks

**Comment by Binjaaa** [comment] 2018-10-24 11:18
Well, every miracle lasts 2 days. 😢Same error again.

**Comment by abk-x** [comment] 2018-10-29 23:40
I cloned https://github.com/Binjaaa/ionide-dll-read-error-repo and build it then opened and I didnt have the errors.

I then added another subproject and referenced it from MainProject, and the error didnt occur.

Then, I did this:

    src/$ mkdir SubProject3 && cd SubProject3
    src/$ dotnet new classlib 
    src/$ code ../

And the error occurred. Note that I didn't even add SubProject3 as a project reference to MainProject.

I then deleted the folder SubProject3, and any bin/obj dirs with `find . | grep "obj|bin" | xargs rm -rf` from the root, and rebuilt the main project, then reloaded vscode, and the error was still present. I then cleared the F# cache, and reloaded, and the error went away, which doesnt make sense at all because the fsac.cache is in the obj/ directories.

I am struggling to find the cause of this one.

**Comment by wuzzeb** [comment] 2018-11-30 22:18
I get this error too anytime a file or package reference is added to the fsproj file.  Like @abk-x said, deleting the obj bin and rebuilding just the dependent package doesn't fix it.  But I did find a reliabile fix: delete all obj and bin folders, then run `dotnet build` one by one in each project in order.  If you run `dotnet build` from just the final project the error still shows up, you must run it one-by-one in each project in order.

Thus I created a shell script with the following

```
#!/bin/sh
DIRS="proj1 proj2 proj3 proj4"
for dir in $DIRS; do
	rm -rf $dir/bin $dir/obj
done
for dir in $DIRS; do
	dotnet build $dir
done
```

Make sure the DIRS variable contains the project directories in the ascending order of dependencies! That is, proj2 can depend only on projects earlier in the list.  By exiting vscode, building in ascending order, and then opening vscode, I can reliably get the error to disappear.

**Comment by guiri14** [comment] 2018-12-04 17:21
I'm also getting this error and can confirm that @wuzzeb's solution worked great for me.

**Comment by normanhh3** [comment] 2018-12-19 10:12
> Set the **"FSharp.fsacRuntime": "net"**, settings in my workspace to use **"netcore"**

This worked for me in a workspace targetting .net core.

**Comment by aflofo** [comment] 2018-12-29 04:39
I don't know why but when I removed ```<?xml version="1.0" encoding="utf-8"?>``` from my fsproj the error went away. Probably some parsing issue.

**Comment by joelvandiver** [comment] 2019-01-09 23:08
Confirmed, @wuzzeb's solution of a complete clean out and rebuilding in dependency order worked for me.

**Comment by abk-x** [comment] 2019-01-17 00:47
Finally time to debug this a bit (holidays). I set up a debug version of FsAutoComplete and printed the project options in full for a working version of my code, and then a non working version, and diffed the output.

When the issue occurs, it appears that the [FSharpProjectOptions](http://fsharp.github.io/FSharp.Compiler.Service/reference/microsoft-fsharp-compiler-sourcecodeservices-fsharpprojectoptions.html) that [FsAutoComplete](https://github.com/fsharp/FsAutoComplete) provides is not populating the 'OtherOptions' field.

On a working project this field should contain the framework references and some other info for FSC:

```
ReferencedProjects =
     [|("/home/user/projects/res/backend/src/Analysis/Model/bin/Debug/netstandard2.0/Analysis.Model.dll",
        {ProjectFileName =
          "/home/user/projects/res/backend/src/Analysis/Model/Analysis.Model.fsproj";
         ProjectId =
          Some
            "/home/user/projects/res/backend/src/Analysis/Model/Analysis.Model.fsproj";
         SourceFiles = [||];
         OtherOptions =
          [|"-o:/home/user/projects/res/backend/src/Analysis/Model/obj/Debug/netstandard2.0/Analysis.Model.dll";
            "-g"; "--debug:portable"; "--noframework"; "--define:TRACE";
            "--define:DEBUG"; "--define:NETSTANDARD"; "--define:NETSTANDARD2_0";
            "--optimize-"; "--tailcalls-";
            "-r:/home/user/.nuget/packages/fsharp.core/4.5.4/lib/netstandard1.6/FSharp.Core.dll";
            "-r:/home/user/.nuget/packages/netstandard.library/2.0.3/build/netstandard2.0/ref/Microsoft.Win32.Primitives.dll";
            "-r:/home/user/.nuget/packages/netstandard.library/2.0.3/build/netstandard2.0/ref/mscorlib.dll";
            "-r:/home/user/.nuget/packages/netstandard.library/2.0.3/build/netstandard2.0/ref/netstandard.dll";
...
```

On a project that causes the error on this issue, we get this instead:

```
 ReferencedProjects =
     [|("/home/user/projects/res/backend/src/Analysis/Model/bin/Debug/netstandard2.0/Analysis.Model.dll",
        {ProjectFileName =
          "/home/user/projects/res/backend/src/Analysis/Model/Analysis.Model.fsproj";
         ProjectId =
          Some
            "/home/user/projects/res/backend/src/Analysis/Model/Analysis.Model.fsproj";
         SourceFiles = [||];
         OtherOptions = [||];
         ReferencedProjects = [||];
         IsIncompleteTypeCheckEnvironment = false;
         UseScriptResolutionRules = false;
         LoadTime = 1/16/19 8:22:34 PM;
         UnresolvedReferences = None;
         OriginalLoadReferences = [];
```

I think [commands](https://github.com/fsharp/FsAutoComplete/blob/master/src/FsAutoComplete.Core/Commands.fs#L273) should recompile projects on the fly (then cache them) that have missing references, something like this (I tried but it lead to issues in [here](https://github.com/fsharp/FsAutoComplete/blob/master/src/FsAutoComplete.Core/NETFrameworkInfoProvider.fs#L43),  :
```
                let! checkOptions =
                    match state.GetCheckerOptions(file, lines) with
                    | Some c when Array.isEmpty c.ReferencedProjects -> 
                        do printfn "checker options for %s already existed %A" file c
                        async.Return c
                    // sometimes we get a cached referenceProject that does not have
                    // the correct 'OtherOptions' framework details
                    | Some c -> 
                        if not(Array.isEmpty c.ReferencedProjects) then 
                            let missingOpts = 
                                c.ReferencedProjects 
                                |> Array.filter (fun (_,x) -> Array.isEmpty x.OtherOptions) 
                            if Array.isEmpty missingOpts then
                                do printfn "checker options for %s already existed %A" file c
                                async.Return c
                            else
                                for _,prj in missingOpts do 
                                    do printfn "Missing opts! %A" prj.ProjectFileName
                                    let sts = x.Compile prj.ProjectFileName |> Async.RunSynchronously 
                                    printfn "Compiled project %A" sts

                                async {
                                    let! checkOptions = checker.GetProjectOptionsFromScript(file, text)
                                    state.AddFileTextAndCheckerOptions(file, lines, normalizeOptions checkOptions)
                                    return checkOptions
                                }
                        else
                            do printfn "checker options for %s already existed %A" file c
                            async.Return c
                    | None -> 
                        do printfn "No checker options returned, adding"
                        async {
                            let! checkOptions = checker.GetProjectOptionsFromScript(file, text)
                            state.AddFileTextAndCheckerOptions(file, lines, normalizeOptions checkOptions)
                            return checkOptions
                        }
```
It also seems that [this](https://github.com/fsharp/FsAutoComplete/blob/master/src/FsAutoComplete.Core/NETFrameworkInfoProvider.fs#L43) might need updating to use `dotnet msbuild` instead of `msbuild`, but this leads to other issues inside (dotnet-proj-info): 

```
...
            let msbuildPath =
            #if NETCOREAPP || NETSTANDARD 
                Dotnet.ProjInfo.Inspect.MSBuildExePath.DotnetMsbuild "dotnet"
            #else
                Dotnet.ProjInfo.Inspect.MSBuildExePath.Path "msbuild"
            #endif
...
```
@enricosada am I on the right track here, I am trying to use:
`Dotnet.ProjInfo.Inspect.getProjectInfo` but it returns a strange error that suggests something with path concatenation is going odd:
```
Request cancelled (exn was System.IO.DirectoryNotFoundException: Could not find a part of the path '/tmp/tmpHYk1pa.tmp/obj/EnvironmentInfo.proj.proj-info.targets'
```
I will keep trying to debug this soon. My next step is to update the version of dotnet-proj-info that is used in FsAutoComplete (currently its 0.11.0 I think).

**Comment by enricosada** [comment] 2019-01-17 02:53
@abk-x good investigation, let's continue in FSAC repo

**Comment by JonCanning** [comment] 2019-01-21 11:36
Thanks @wuzzeb, reordering my .sln file has fixed it 🙃

**Comment by lenadroid** [comment] 2019-02-12 22:41
I have the same issue and @wuzzeb's idea works for me as well on a Mac!

**Comment by Krzysztof-Cieslak** [comment] 2019-03-15 11:06
Is that still happening? I'm hoping we may have accidentally fixed it while fixing some other things in the latest release.

**Comment by KillyMXI** [comment] 2019-04-30 16:21
I got this issue just now, trying to add an xUnit test project to a solution.

Deleting bin and obj folders and rebuilding projects one by one in order doesn't seem to work for me.

**Comment by wallymathieu** [comment] 2019-08-05 17:30
@Krzysztof-Cieslak I get the issue though after removing bin/obj folders I only get issues around type provider usage? Could that be related?

**Comment by Krzysztof-Cieslak** [comment] 2020-01-17 22:57
I haven't seen this in a while. And known workaround to any such problems in .Net is cleaning `obj` folders. 
Closing.

**Closed by Krzysztof-Cieslak** 2020-01-17 22:57 UTC
Labels: reproduction needed

**Comment by meggermo** [comment] 2020-03-22 15:15
Well, the issue popped up again for me.

What I noticed is that the project files that gave me problems contained multiple project references. The paths separators of the Include attribute values were mixed: one reference had forward slashes the other one backward slashes. If I make all slashes in one fsproj file consistent and rebuild the the issue is gone.

This is probably because I used dotnet on the cmd-line (which produces forward slashes) to add a reference and then added a second reference with the ionide plugin in vscode (which produces back slashes).  So I guess the fix is to make sure that tools/plugins consistently use the path separator that fits best with the OS.

OS: Linux x64 5.3.0-42-generic
vscode: Version: 1.43.0, Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
ionide-fsharp: Version: 4.7.0

**Comment by meggermo** [comment] 2020-03-22 19:40
Hmm, maybe not the root  cause after all. I now have a project with mixed slashes in the references and all is fine. Still, path separator consistency in tools would be nice though!

**Comment by romanprocopie** [comment] 2020-11-01 20:05
Got this problem today. Looks like the problem was the latest ionide (4.17.0 at the time of writing this) and not latest .net core SDK (3.1.401). An install of latest SDK (3.1.403) sorted out all problems

OS : MacOS 10.15
vscode : 1.50.1
