### ISSUE TITLE
Ionide inserts "open ..." statements in a syntactically invalid location

### ISSUE THREAD

**Issue by samuela** [ionide/ionide-vscode-fsharp#932] opened 2018-10-12 05:06 UTC
After using autocomplete and accepting some suggestions, I get the necessary imports added inside a type definition:

![screen shot 2018-10-11 at 10 03 51 pm](https://user-images.githubusercontent.com/226872/46848975-c0a0ea00-cda1-11e8-8cdd-29a9a003705d.png)

**Comment by Krzysztof-Cieslak** [comment] 2018-10-12 13:08
Duplicate of #906

**Closed by Krzysztof-Cieslak** 2018-10-12 13:08 UTC
