### ISSUE TITLE
Version 5.7.0: Running the contributed command: 'fsi.SendSelection' failed.

### ISSUE THREAD

**Issue by dgrimmin** [ionide/ionide-vscode-fsharp#1560] opened 2021-08-05 10:41 UTC
### Describe the bug**
With the release of version 5.7.0 sending script to fsi stopped working.

### Steps to reproduce
Open script select text and alt+enter

### Expected behaviour
terminal opens and script gets executed

## Machine info
 - OS: Windows
 - .NET SDK version: 5
 - Ionide version: 5.7.0

### Workaround
Revert to 5.6.0

**Comment by baronfel** [comment] 2021-08-05 11:35
Thanks for reporting! I introduced a regression in this release, I'll try to take a hotfix today to resolve it. In the meantime you can manually use the previous version by choosing it from the extensions page in vscode.

**Comment by andagr** [comment] 2021-08-05 11:46
Log (copied from the [discussion about this in slack](https://fsharp.slack.com/archives/C04BJKUP2/p1628143865131100)):

```
mainThreadExtensionService.ts:63 [[object Object]]Terminal has already been disposed
$onExtensionRuntimeError @ mainThreadExtensionService.ts:63
_doInvokeHandler @ rpcProtocol.ts:418
_invokeHandler @ rpcProtocol.ts:403
_receiveRequest @ rpcProtocol.ts:319
_receiveOneMessage @ rpcProtocol.ts:246
(anonymous) @ rpcProtocol.ts:111
fire @ event.ts:583
fire @ ipc.net.ts:513
_receiveMessage @ ipc.net.ts:866
(anonymous) @ ipc.net.ts:705
fire @ event.ts:583
acceptChunk @ ipc.net.ts:286
(anonymous) @ ipc.net.ts:247
T @ ipc.net.ts:50
emit @ events.js:315
addChunk @ internal/streams/readable.js:309
readableAddChunk @ internal/streams/readable.js:284
Readable.push @ internal/streams/readable.js:223
onStreamRead @ internal/stream_base_commons.js:188
mainThreadExtensionService.ts:64 Error: Terminal has already been disposed
	at S._checkDisposed (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:32647)
	at Object.sendText (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:31253)
	at c:\Users\user\.vscode\extensions\ionide.ionide-fsharp-5.7.0\fsharp.js:2:425043
	at c:\Users\user\.vscode\extensions\ionide.ionide-fsharp-5.7.0\fsharp.js:1:14453
	at L (c:\Users\user\.vscode\extensions\ionide.ionide-fsharp-5.7.0\fsharp.js:1:13875)
	at z (c:\Users\user\.vscode\extensions\ionide.ionide-fsharp-5.7.0\fsharp.js:1:14436)
	at Ra (c:\Users\user\.vscode\extensions\ionide.ionide-fsharp-5.7.0\fsharp.js:2:425027)
	at Na (c:\Users\user\.vscode\extensions\ionide.ionide-fsharp-5.7.0\fsharp.js:2:428523)
	at c:\Users\user\.vscode\extensions\ionide.ionide-fsharp-5.7.0\fsharp.js:2:429237
	at d.fire (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1726)
	at y.$acceptTerminalOpened (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:38208)
	at c._doInvokeHandler (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:88:12743)
	at c._invokeHandler (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:88:12435)
	at c._receiveRequest (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:88:11097)
	at c._receiveOneMessage (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:88:9900)
	at c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:88:8004
	at d.fire (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1726)
	at h.fire (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15777)
	at c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:103:29836
	at d.fire (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1726)
	at h.fire (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15777)
	at r._receiveMessage (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:21035)
	at c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:17921
	at d.fire (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1726)
	at u.acceptChunk (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:13138)
	at c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:12486
	at Socket._ (c:\Users\user\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:103:13107)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
``

**Comment by baronfel** [comment] 2021-08-05 14:04
Releasing 5.7.1 with the fix for this as we speak.

**Comment by baronfel** [comment] 2021-08-05 14:51
5.7.1 is released and seems to be working. Thanks again for reporting to let me know!

**Closed by baronfel** 2021-08-05 14:51 UTC
