### ISSUE TITLE
giving parameters to run/debug the project with

### ISSUE THREAD

**Issue by yilmazdurmaz** [ionide/ionide-vscode-fsharp#1392] opened 2020-06-29 21:23 UTC
**Is your feature request related to a problem? Please describe.**
going back and forth with vscode debug/run menus and f# solution explorer when I need to input parameters to my program from console is exhausting my coding energy.

**Describe the solution you'd like**
whatever you use to debug/run the project in vscode, give a setting to give parameters to my programs, either static or live. vscode itself has this capability in its "launch.json" file

**Describe alternatives you've considered**
as I mentioned, I use "launch.json" but going back and forth is exhausting.

**Additional context**

thanks

**Comment by Krzysztof-Cieslak** [comment] 2020-07-08 17:55
Duplicate of #569

**Closed by Krzysztof-Cieslak** 2020-07-08 17:55 UTC
