### ISSUE TITLE
Missing code lens

### ISSUE THREAD

**Issue by 7sharp9** [ionide/ionide-vscode-fsharp#570] opened 2017-10-04 21:24 UTC
<img width="600" alt="screen shot 2017-10-04 at 22 23 11" src="https://user-images.githubusercontent.com/588746/31200398-c39e44ce-a952-11e7-8355-d94b6ca2a0d7.png">

Notice the missing code lens, space is allocated for it.

**Comment by Krzysztof-Cieslak** [comment] 2017-10-04 21:29
Hmm... Haven't seen that yet. Does it show if you do any edit in file? Or scroll down and up?

**Comment by 7sharp9** [comment] 2017-10-04 21:32
Its the only function or property with allocated space but no lens.  Its from https://github.com/SAFE-Stack/SAFE-Nightwatch/blob/master/build.fsx#L54

**Comment by 7sharp9** [comment] 2017-10-04 21:32
No it doesn't appear if you scroll or edit either, Im altering that function as part of a PR.

**Comment by Krzysztof-Cieslak** [comment] 2017-10-04 21:35
Weird... I can't repro

![image](https://user-images.githubusercontent.com/5427083/31200839-aade875a-a95c-11e7-9ab1-0e4c3dafe2ae.png)

**Comment by Krzysztof-Cieslak** [comment] 2017-10-04 21:35
What's the Ionide version?

**Comment by 7sharp9** [comment] 2017-10-04 21:36
You have `Lazy<obj>` lower down whereas mine are `Lazy<string>` too.

**Comment by 7sharp9** [comment] 2017-10-04 21:37
Im ionide 3.3.3

**Comment by Krzysztof-Cieslak** [comment] 2017-10-04 21:39
> You have `Lazy<obj>` lower down whereas mine are `Lazy<string>` too.

That's just because I haven't restored deps.... it's same after I've restored

![image](https://user-images.githubusercontent.com/5427083/31200955-30e7963e-a95d-11e7-8dc7-5a809f9da403.png)

**Comment by Krzysztof-Cieslak** [comment] 2017-10-04 21:39
> Im ionide 3.3.3

We've released 3.3.4 today, can you please try it out?

**Comment by 7sharp9** [comment] 2017-10-04 21:44
I'll try it out, tooltips don't work on that function either, I can't see an error in the console either.  Hmmm

**Comment by 7sharp9** [comment] 2017-10-04 21:49
3.3.4 is the same.

**Comment by Krzysztof-Cieslak** [comment] 2017-10-26 16:39
Can't repro, and it's not critical. Closing.

**Comment by 2moveit** [comment] 2017-11-09 16:35
@Krzysztof-Cieslak Your #Remmidemmi talk on Open Source and contributing worked ;-)
I was able to reproduce this issue:

As soon as you add `./` or a folder path like  `./RefFolder/` into the #load statement the code lenses will disappear.

Steps to reproduce:
1. Create a new classlibrary with VSCode/Ionide-Fsharp so that you have a Script.fsx and another .fs file (the .fs file can be empty)

2. change the #load statement in the .fsx file:
```
//#load @"./RefFolder/RefFIle.fs"  //CodeLenses will not work
#load @"./RefFileWithoutFolder.fs" //CodeLenses will not work

//#load @"RefFileWithoutFolder.fs"  //CodeLenses will work
let x = 1
```

**Comment by realvictorprm** [comment] 2017-11-24 10:06
I can confirm this, any idea what's happening?

**Closed** 2018-02-28 11:46 UTC
Labels: reproduction needed
