### ISSUE TITLE
No Intellisense or autocomplete from Ionide

### ISSUE THREAD

**Issue by Lewiszz** [ionide/ionide-vscode-fsharp#1178] opened 2019-07-12 10:44 UTC
**Describe the bug**
When using the Ionide FSharp extension, none of its features such as autocomplete, intellisense or tooltip hovering is working (both on fsac runtime net and netcore).

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new F# project with **dotnet new console -lang f#**
2. Install Ionide Fsharp if it is not installed yet 
3. Type something that does not compile

**Expected behaviour**
A red line beneath the faulty code and information on what's wrong.

**Screenshots**
![afbeelding](https://user-images.githubusercontent.com/38034937/61122522-44f3db00-a4a2-11e9-8c2c-2086838caa8b.png)

**Environment (please complete the following information):**
 - OS: Windows 10 Pro, 64-bit operating system, x64 based processor
 - Ionide version: 4.0.5
 - VSCode version: 1.36.1
 - dotnet SDK version: 2.2.300
 - .Net Framework version: 4.0

**Additional context**
This has been mentioned before in #1153. 

I have tried reinstalling Ionide and/or restarting VS Code and reloading window.

Not sure if it is useful, but I noticed the following appears in my F# Output log when I hover over my code:
[Error - 12:42:46 PM] Request textDocument/hover failed.
  Message: System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at FsAutoComplete.Lsp.positionHandler@194.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
  Code: -32603

**Comment by baronfel** [comment] 2019-07-12 19:19
This is a duplicate of #1177, which is being worked on.

**Closed** 2019-07-12 19:35 UTC
