### ISSUE TITLE
VsCode is locking '.fsproj.proj-info.targets' msbuild files

### ISSUE THREAD

**Issue by matthid** [ionide/ionide-vscode-fsharp#782] opened 2018-04-08 15:32 UTC
![2018-04-07 16_20_36-program fs - fake - visual studio code](https://user-images.githubusercontent.com/1866463/38469268-3968e0a6-3b52-11e8-8dfb-d9735abd9002.png)

The error here is:

```
error: MSB4024: The imported project file `project/obj/project.fsproj.proj-info.targets` could not be loaded. The process cannot access the file  `project/obj/project.fsproj.proj-info.targets` because it is being used by another process.
```

I get similar errors on various situations when VSCode is opened:
 - manually running `dotnet build`/`dotnet run` in the integrated terminal (like in this instance)
 - Running `fake build` (which might actually be the same because it runs `dotnet-cli`)

**Comment by vbfox** [comment] 2018-04-08 19:16
I see a project not loading, maybe you were entering the infinite restore loop (Each re-creating a new `proj-info.targets` file) latest ionide release (1h ago) should solve that (#767).

If it's the cause I also sent a PR to solve the file re-creation (as it's always the same anyway) in https://github.com/enricosada/dotnet-proj-info/pull/17 that is not yet merged.

**Comment by matthid** [comment] 2018-04-08 19:59
@vbfox thanks. Usually I load a solution where the not loadable project is not part of. But maybe VSCode is trying to load it in the background anyway?

How do I know I have the correct version? :P I will keep my eyes open ...

**Comment by Krzysztof-Cieslak** [comment] 2018-09-02 20:59
Is this still a case?

**Closed** 2018-11-16 13:22 UTC
Labels: bug, language services
