### ISSUE TITLE
Unwanted .ionide\symbolCache.db in non-F# workspaces

### ISSUE THREAD

**Issue by nightroman** [ionide/ionide-vscode-fsharp#1278] opened 2019-12-27 13:31 UTC
**Describe the bug**

On opening a non-F# workspace in VSCode ionide may create unexpected `.ionide\symbolCache.db`
This does not happen often. And cannot find reliable steps to reproduce.
But it's often enough to make me post this report :)

I have the ionide extension installed in my VSCode. But I work on all kind of projects including non-F#. Sometime when I open a non-F# workspace containing nothing related to F#, ionide nevertheless creates `.ionide\symbolCache.db`. The last time it happened for this pure PowerShell repository workspace - https://github.com/nightroman/FarMongo

As far as I can see, it's an SQLite database with one empty table `Symbols`.

**Expected behaviour**
ionide should not create anything in non-F# workspaces

**Environment (please complete the following information):**
 - OS: Windows 8.1, 10
 - Ionide version: 4.4.2
 - VSCode version: 1.41.1

**Comment by Krzysztof-Cieslak** [comment] 2019-12-28 10:45
Duplicate of #1041

**Closed by Krzysztof-Cieslak** 2019-12-28 10:45 UTC
