### ISSUE TITLE
Exported logs are empty

### ISSUE THREAD

**Issue by kentcb** [ionide/ionide-vscode-fsharp#1627] opened 2021-11-11 23:15 UTC
### Describe the bug
I'm trying to understand why my Ionide tooling has stopped working (probably related to VS upgrades). However, when I export logs, the log file is empty.

### Steps to reproduce
1. Open my project
2. Wait for it to load and show hints etc
3. Export logs via `F#: Get Ionide Logs`
4. Open the log file (it's empty)

### Expected behaviour
The log should be helpful in diagnosing what is going on.

## Machine info
 - OS: Windows 10
 - .NET SDK version: I can't know because the logs don't tell me. It's either 5.0.209, 5.0.403, or 6.0.100
 - Ionide version: 5.9.0

**Comment by HerrNiklasRaab** [comment] 2021-11-14 22:56
Can confirm this, using macOS and .net 6

**Comment by Krzysztof-Cieslak** [comment] 2021-11-19 14:28
Duplicate of #1617

**Closed by Krzysztof-Cieslak** 2021-11-19 14:28 UTC

**Comment by kentcb** [comment] 2021-11-19 22:21
@Krzysztof-Cieslak I don't think those issues are the same as the one I reported. In my case, the export works, but the exported file is empty.
