### ISSUE TITLE
F# Source Code Formatting

### ISSUE THREAD

**Issue by teo-tsirpanis** [ionide/ionide-vscode-fsharp#274] opened 2016-11-09 13:29 UTC
Visual Studio Code will not react if the user presses Shift + Alt + F. On the contrary, Visual Studio F# Power Tools support code formatting.

**Comment by cloudRoutine** [comment] 2016-11-09 16:38
Formatting in VFPT is implemented using [Fantomas](https://github.com/dungpa/fantomas). To enable source code formatting in vscode a [`DocumentFormattingEditProvider`](https://code.visualstudio.com/docs/extensionAPI/vscode-api#DocumentFormattingEditProvider) would need to be implemented.

As Fantomas cannot be used inside of this repo the formatting functionality would need to be implemented as a part of [FsAutoComplete](https://github.com/ionide/FsAutoComplete) with commands on this side to call the formatting service and apply the set of text edits it receives back to the editor buffer.

Feel free to submit a PR

**Comment by kirill-gerasimenko** [comment] 2016-11-09 16:57
It doesn't look very complex, I could try adding that. 
To summarize:
* add new endpoint, say "/format" in FSAC, which accepts F# source code, feeds it to Fantomas and returns result back
* add provider implementation @cloudRoutine mentioned on Code's side

**Comment by cloudRoutine** [comment] 2016-11-09 17:30
You can use [the VFPT implementation as a reference](https://github.com/fsprojects/VisualFSharpPowerTools/tree/master/src/FSharp.Editing.VisualStudio/Formatting)

* don't forget to provide some sort of error message when the file isn't parsable, that's the only way fantomas can process it
* formatting needs to operate on dirty buffers

Expect an increase in issues when Fantomas starts breaking people's code and when they complain about the limitations of the settings and options for configuration

**Comment by kirill-gerasimenko** [comment] 2016-11-09 18:29
> formatting needs to operate on dirty buffers

Do you mean on the content of the buffer(text editor) which might not be saved to disk yet, so I need to send the whole text to the endpoint for formatting?

**Comment by cloudRoutine** [comment] 2016-11-09 18:32
yup

**Comment by jmmk** [comment] 2016-12-31 14:02
In IntelliJ, I think it blocks formatting (for Java at least) if there is a compiler error in the current buffer. If that's possible here, it would hopefully prevent a lot of "fantomas broke my code".

**Comment by teo-tsirpanis** [comment] 2017-03-24 12:58
[This pull request](https://github.com/ionide/FsAutoComplete/pull/50) has added an FSAC endpoint. What else needs to be done?

**Comment by jgrund** [comment] 2017-06-21 20:21
This would be great to have, is this something that is still doable?

**Comment by teo-tsirpanis** [comment] 2017-06-22 09:28
I guess, but I don't get any response from the developers. @Krzysztof-Cieslak?

**Comment by kirill-gerasimenko** [comment] 2017-07-21 11:14
There are merge conflicts there, I bet they won't take a look if it is not fixed first.

**Comment by WangJi** [comment] 2018-02-10 08:41
hey guys, how is this going?

**Comment by Svetomechc** [comment] 2018-03-21 12:27
No progress?

**Comment by teo-tsirpanis** [comment] 2018-03-21 15:20
I literally don't know. They said that Fantomas would be integrated to FCS, yet the actual Fantomas has an issue with outdated libraries. I submitted a PR to fix it, and got no response.

**Comment by Krzysztof-Cieslak** [comment] 2018-03-21 16:23
There is no plan to add F# Formatting (Fantomas) support in its current state due to quality problems of the formater. Some activity discussing adding it to VF# and FCS is happening here - https://github.com/Microsoft/visualfsharp/pull/3542, please check @dsyme's comments about existing Fantomas issues.

**Comment by s-trooper** [comment] 2019-01-23 09:16
I just wrote my own source code [formatter](https://github.com/s-trooper/FSharpFormat), may be it can be used for this issue.

**Comment by cspaniard** [comment] 2019-02-22 10:07
if there is a way, pleeeeeeeeeease make it happen... ;)
Nowadays this is a must ;)

**Comment by nojaf** [comment] 2019-09-14 14:02
Hey @Krzysztof-Cieslak. hypothetically 😋 what would need to be done for this?
Fantomas is in a slightly better state now and I might want to try and integrate it.

I would assume there are two components here:
* The "I pressed format code" in VSCode.
* The formatting happening in a language server (I'm guessing https://github.com/fsharp/FsAutoComplete) somewhere.

Could you provide me with some pointers?

**Comment by Krzysztof-Cieslak** [comment] 2019-09-14 16:16
Because we use LSP there's one thing that must happen - we must implement it on the server side, "press format code in VSCode" part we get for free ;-). 

We need to implement couple of overrides (https://github.com/fsharp/FsAutoComplete/blob/master/src/LanguageServerProtocol/LanguageServerProtocol.fs#L2023-L2035) in the FsharpLspServer class (https://github.com/fsharp/FsAutoComplete/blob/master/src/FsAutoComplete/FsAutoComplete.Lsp.fs#L46) in FSAC and inform client that server has the formatting capabilities (change what we return here - https://github.com/fsharp/FsAutoComplete/blob/master/src/FsAutoComplete/FsAutoComplete.Lsp.fs#L337-L369)

**Comment by Krzysztof-Cieslak** [comment] 2019-09-14 16:17
Since the problem is only related to server side, let's move any further discussion to FSAC repo.

**Comment by maarek** [comment] 2019-11-13 16:46
Since Fantomas integration has been merged into FsAutoComplete, is there anything else to do from the Ionide side?

**Closed** 2019-11-13 17:52 UTC
Labels: backburner - requires additional upstream functionality, feature request
