### ISSUE TITLE
Terminal not rendering normally.

### ISSUE THREAD

**Issue by cmbrown1598** [ionide/ionide-vscode-fsharp#591] opened 2017-10-11 20:58 UTC
This started happening with the 17.0v of code or what, but FSI:Start doesn't render in the terminal right away anymore.

To repro. 

Open VS Code, Ctrl+Shift+P and go to FSI:Start
No text renders.

![image](https://user-images.githubusercontent.com/1802671/31466267-7995a12c-ae8b-11e7-9703-bae6839bfa9e.png)

Click the Problems tab (or Output, or Debug Console), any of those lower tabs.
Click back to Terminal

Text renders properly
![image](https://user-images.githubusercontent.com/1802671/31466341-b0eb0d88-ae8b-11e7-9475-97b785880737.png)

My system. 
Windows 10 Enterprise, v1703
12 GB ram, 2 procs.

F# 4.1 installed.

Following plugins installed in Code.
![image](https://user-images.githubusercontent.com/1802671/31466442-034f359a-ae8c-11e7-8b28-06e4fbf28003.png)

**Comment by enricosada** [comment] 2017-10-11 21:59
@cmbrown1598 it's a bug of vscode tracked in https://github.com/Microsoft/vscode/issues/35728

as a workaround you can resize the panel vertically (even by 1 px)

Closing as dupe of https://github.com/ionide/ionide-vscode-fsharp/issues/580

**Closed by enricosada** 2017-10-11 21:59 UTC
