### ISSUE TITLE
Cannot execute recordStubGenerator every second in output

### ISSUE THREAD

**Issue by hsorbo** [ionide/ionide-vscode-fsharp#864] opened 2018-07-26 23:08 UTC
Just got the newest bits (3.24.0). In the ouptut i get loads of this
`[01:02:28 ERROR] Cannot execute recordStubGenerator, File '/extension-output-#6.fsx' not parsed `

Ionide works, but it seems like something that shouldn't happen.

<img width="1225" alt="screen shot 2018-07-27 at 00 56 47" src="https://user-images.githubusercontent.com/1906744/43293138-fe6999cc-9138-11e8-8a6e-67b0526c33bf.png">

Thank you so much for a great product!

**Comment by Krzysztof-Cieslak** [comment] 2018-07-26 23:42
cc: @MangelMaxime

**Comment by MangelMaxime** [comment] 2018-07-27 05:41
This is "normal"

recordStubGenerator is triggered by cursor move. Each time you move your cursor we are trying to see if you can generate a record at the new position.

One solution, could be to add a debouncer. Because, we want to check if we can generate a record at the cursor position, we only want to check the final cursor position.

**Comment by MangelMaxime** [comment] 2018-07-27 05:56
@Krzysztof-Cieslak Something feel strange to me here.

The debouncer thing is probably something needed to send less request and also send only request that make sense.

But what I don't understand is where the file '/home/maxime/extension-output-#2.fsx' is coming from ?
When testing it locally several time, I had:

- '/home/maxime/extension-output-#2.fsx'
- '/home/maxime/extension-output-#1.fsx'

My opened file is `SimpleType.fs` and my working directory is `/home/maxime/Workspace/ionide/ionide-fsgrammar` so nothing to do with '/home/maxime/extension-output-#1.fsx'

**Comment by Krzysztof-Cieslak** [comment] 2018-07-27 10:57
Fixed in 3.24.1 - issue was caused by the fact that 1. there was no any throttling 2. record stub handler was not checking if the document was F# which caused infinite loop (i.e handler was executed when something was written to output channel, and handler itself was writing to output cha

**Closed by Krzysztof-Cieslak** 2018-07-27 10:57 UTC
