### ISSUE TITLE
dotnet/fsharp fails to be loaded on macos

### ISSUE THREAD

**Issue by EverybodyKurts** [ionide/ionide-vscode-fsharp#1488] opened 2021-01-28 01:53 UTC
### Describe the bug**

Projects fail to be loaded in visual studio code on MacOS.

<img width="1424" alt="Screen Shot 2021-01-27 at 8 55 33 PM" src="https://user-images.githubusercontent.com/879734/106078807-094f4f00-60e2-11eb-98ab-43e58428e0a9.png">

### Steps to reproduce

1. Clone dotnet/fsharp repo
2. Run ./build.sh
3. Open up the folder in visual studio code
4. Run `dotnet build FSharp.sln`

### Expected behaviour

`dotnet build` populates a project's `obj` folder

### Screenshots

see top of post

## Machine info
 - OS: Mac
 - .NET SDK version: 5.0.2
 - Ionide version: 5.2.0

**Comment by baronfel** [comment] 2021-01-28 01:57
Yep, this is a dupe of https://github.com/ionide/proj-info/issues/95, which has been going for a bit. Something in the compiler repo changed about a month ago which has us flummoxed.

**Comment by EverybodyKurts** [comment] 2021-01-28 01:59
Oh oops, sorry! I should have searched the issues. I can or you can close this issue if desired.

**Comment by cartermp** [comment] 2021-01-28 03:07
Will close!

**Closed by cartermp** 2021-01-28 03:07 UTC
