### ISSUE TITLE
intellisense and other Lang Services not working (probably because of enterprise proxy)

### ISSUE THREAD

**Issue by cargoge** [ionide/ionide-vscode-fsharp#316] opened 2016-12-20 14:27 UTC
Intellisense and other interactive language features are not working on a Windows 10 machine behind an enterprise proxy.
I strongly suspect there is an issue in handling system-wide or application-wide proxy settings as the requests fail "with status code 401" ( UNAUTHORIZED, The request has not been applied because it lacks valid authentication credentials for the target resource).

I have tried to set the application settings for the proxy without success.
The documentation does not provide examples or indications on well formed values for "http.proxyAuthorization" .
`"http.proxy": "http://__user__:password@__server__:__port__"`  would be the obvious but i don' t know if it is supported)

What follow is retrieved from the console log:
```
[Extension Host] [IONIDE-FSAC] RES (087) <- {tooltip} ERROR in 15 ms: Error: Request failed with status code 401 Data=%O
shell.ts:541 Request failed with status code 401: Error: Request failed with status code 401
    at createError (C:\Users\__MY_USER_NAME__\.vscode\extensions\Ionide.Ionide-fsharp-2.14.0\node_modules\axios\lib\core\createError.js:15:15)
    at settle (C:\Users\__MY_USER_NAME__\.vscode\extensions\Ionide.Ionide-fsharp-2.14.0\node_modules\axios\lib\core\settle.js:18:12)
    at IncomingMessage.handleStreamEnd (C:\Users\__MY_USER_NAME__\.vscode\extensions\Ionide.Ionide-fsharp-2.14.0\node_modules\axios\lib\adapters\http.js:186:11)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
e.onUnexpectedError 		@ shell.ts:541
(anonymous function) 		@ shell.ts:457
e.onUnexpectedExternalError @ errors.ts:74
s 							@ errors.ts:96
(anonymous function) 		@ hover.ts:34
v 							@ winjs.base.raw.js:1209
enter 						@ winjs.base.raw.js:901
_run 						@ winjs.base.raw.js:1068
_error 						@ winjs.base.raw.js:1041
v 							@ winjs.base.raw.js:1209
enter 						@ winjs.base.raw.js:901
_run 						@ winjs.base.raw.js:1068
_error 						@ winjs.base.raw.js:1041
(anonymous function) 		@ async.ts:359
done 						@ winjs.base.raw.js:1378
v 							@ winjs.base.raw.js:1224
enter 						@ winjs.base.raw.js:901
_run 						@ winjs.base.raw.js:1068
_error 						@ winjs.base.raw.js:1041
e.resolveErr 				@ ipcRemoteCom.ts:110
f 							@ ipcRemoteCom.ts:198
_combinedTickCallback 		@ internal/process/next_tick.js:67
_tickCallback 				@ internal/process/next_tick.js:98
extensionHost.ts:293 [Extension Host] [IONIDE-FSAC] RES (088) <- {symboluse} ERROR in 6 ms: Error: Request failed with status code 401 Data=%O
extensionHost.ts:293 [Extension Host] [IONIDE-FSAC] RES (089) <- {tooltip} ERROR in 7 ms: Error: Request failed with status code 401 Data=%O
extensionHost.ts:293 [Extension Host] [IONIDE-FSAC] RES (090) <- {tooltip} ERROR in 7 ms: Error: Request failed with status code 401 Data=%O
extensionHost.ts:293 [Extension Host] rejected promise not handled within 1 second
shell.ts:541 Request failed with status code 401: Error: Request failed with status code 401
    at createError (C:\Users\__MY_USER_NAME__\.vscode\extensions\Ionide.Ionide-fsharp-2.14.0\node_modules\axios\lib\core\createError.js:15:15)
    at settle (C:\Users\__MY_USER_NAME__\.vscode\extensions\Ionide.Ionide-fsharp-2.14.0\node_modules\axios\lib\core\settle.js:18:12)
    at IncomingMessage.handleStreamEnd (C:\Users\__MY_USER_NAME__\.vscode\extensions\Ionide.Ionide-fsharp-2.14.0\node_modules\axios\lib\adapters\http.js:186:11)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
e.onUnexpectedError 		@ shell.ts:541
(anonymous function) 		@ shell.ts:457
e.onUnexpectedError			@ errors.ts:68
o 							@ errors.ts:88
t.onUnexpectedExtHostError 	@ mainThreadErrors.ts:13
e.handle 					@ abstractThreadService.ts:34
s 							@ ipcRemoteCom.ts:269
f 							@ ipcRemoteCom.ts:226
_combinedTickCallback 		@ internal/process/next_tick.js:67
_tickCallback 				@ internal/process/next_tick.js:98
```

**Comment by Krzysztof-Cieslak** [comment] 2016-12-20 14:36
Duplicate of #272

**Closed by Krzysztof-Cieslak** 2016-12-20 14:36 UTC
