### ISSUE TITLE
FSharp.ViewModule missing

### ISSUE THREAD

**Issue by Martin521** [ionide/ionide-vscode-fsharp#461] opened 2017-07-01 16:50 UTC
I am not sure if this is the right place to ask this question.
I am starting with VS Code / Ionide, and got my first console program running.
Now I created a Windows (WPF) project. When trying to build it, I get the above error message.
Do I need to install ViewModule separately?

**Comment by Martin521** [comment] 2017-07-01 18:07
I see that FSharp.ViewModule.dll exists in the packages subdirectory.

And msbuild calls the correct fsc option -r:D:\fsharp\vscode\Test2\packages\FSharp.ViewModule.Core\lib\portable-net45+netcore45+wpa81+wp8+MonoAndroid1+MonoTouch1\FSharp.ViewModule.dll

But fsc says
D:\Test2\src\WinTest\MainWindow.xaml.fs(5,13): error FS0039: The namespace 'ViewModule' is not defined [D:\Test2\src\WinTest\WinTest.fsproj]

**Comment by enricosada** [comment] 2017-07-11 09:57
Hi @Martin521 , can you share the fsproj? 
best will be like a zip of the repository, to reproduce the error.

If fsc doesnt compile, is a build error, probably you need to add `open ViewModule` in your .fs file, to use the files inside namespace

/cc @ReedCopsey

**Comment by Martin521** [comment] 2017-07-11 20:48
Hi Enrico,
Thanks a lot for looking into this.
I just created a new WPF project by Ionide in VS Code. Attached the sources.
The `open ViewModule` is correctly in the code.
Martin
[Test2.zip](https://github.com/ionide/ionide-vscode-fsharp/files/1140180/Test2.zip)

**Comment by enricosada** [comment] 2017-07-13 13:07
hi @Martin521 , the issue was you where doing `open FSharp.ViewModule` instead of just `open ViewModule` (ref https://github.com/enricosada/ionide_issue461/commit/43fa5ce6aa8066f19bf36cd85dc3358887459211)
because that's the namespace (ref [ViewModelBase source](https://github.com/fsprojects/FSharp.ViewModule/blob/master/src/FSharp.ViewModule/ViewModelBase.fs#L17) )

i uploaded your repro `Test2` with added paket in https://github.com/enricosada/ionide_issue461, now build correctly. after that, intellisense work (well, also before was working, showing an error)

I'll close it for now, because was just a build error unrelated to ionide, but feel free to reopen.

for more help, there is FSF slack chat ( http://fsharp.org/guides/slack/ ) , there are chan (like #code ) where to ask for help ( /cc @ReedCopsey )

**Closed by enricosada** 2017-07-13 13:07 UTC
Labels: reproduction needed

**Comment by Martin521** [comment] 2017-07-13 16:10
Hi @enricosada,
Thanks a lot for helping a stupid beginner, this indeed compiles now.
But is it not still somehow an ionide issue, as the source file, which included the incorrect `open FSharp.ViewModule` statement, was created (or copied from somewhere) by ionide "create project", through Forge?
Should I raise a Forge issue?
I tried to understand, looking at the Forge sources, where the templates come from, but did not succeed.

**Comment by enricosada** [comment] 2017-07-13 16:51
Yes indeed is an issue with Forge templates, didnt know what was the original code 😄 

forge templates are in the `templates` branch of the repo (while sources of the engine are in `master` branch).

Your template is in https://github.com/fsharp-editing/Forge/blob/templates/windows/MainWindow.xaml.fs#L5
Just send a PR targeting that branch to fix the error (probably can be done with the online github editor too)

**Comment by enricosada** [comment] 2017-07-13 16:56
> Thanks a lot for helping a stupid beginner, this indeed compiles now.

Mistake happens, and btw is faster if you want to get help to use chat like, FSF slack or https://functionalprogramming.slack.com/ slack in `#fsharp` chan . 
the community is nice 😄

**Comment by Martin521** [comment] 2017-07-13 17:03
Thanks, I just joined FSF 
:-)

**Comment by Martin521** [comment] 2017-07-13 20:37
... and got the template fixed.
Thanks for the pointer.

**Comment by ReedCopsey** [comment] 2017-07-13 21:25
@Martin521 Thank you for updating that! FYI - That was a breaking change from v 2.x to 3.x of FSharp.ViewModule.
