### ISSUE TITLE
F#: Get Ionide logs doesn't work

### ISSUE THREAD

**Issue by MangelMaxime** [ionide/ionide-vscode-fsharp#1617] opened 2021-11-09 14:25 UTC
### Describe the bug**

![image](https://user-images.githubusercontent.com/4760796/140941575-c790e7a7-b096-44a2-8d94-d8199b8519b2.png)

### Steps to reproduce

1.Press `Ctrl+Shift+P`
2. Launch "F#: Get Ionide logs"
3. See the error

### Expected behaviour

Should not fail

## Machine info
 - OS: Windows/Mac/Linux
 - .NET SDK version:
    - 3.1.415 [/usr/share/dotnet/sdk]
    - 5.0.403 [/usr/share/dotnet/sdk]
    - 6.0.100 [/usr/share/dotnet/sdk]
 - Ionide version: 5.9.0

**Comment by Krzysztof-Cieslak** [comment] 2021-11-19 14:29
Duplicate of #1586

**Closed by Krzysztof-Cieslak** 2021-11-19 14:29 UTC

**Comment by MangelMaxime** [comment] 2021-11-19 15:05
Oops, sorry for the duplicate not sure how I missed the original issue..
