### ISSUE TITLE
No intellisense, code lens or F# Explorer view v 

### ISSUE THREAD

**Issue by richardjharding** [ionide/ionide-vscode-fsharp#1185] opened 2019-07-19 20:06 UTC
No Intellisense , hover showing, cannot display either the F# Explorer side view or the info panel - all of the above used to work

windows 10
VSCode v 1.36.1 (user setup)
Ionide 4.0.6 but have also tried reverting to 4.0.4
Dotnet sdk 2.2.301

With verbose logging switched on I have the following example messages:

```
[LSP call] TextDocumentHover
[LSP] PositionHandler - Position request: d:/Source/Repos/RevocationOrchestration/TokenRevocation/configurationSettings.fs at (17,10)
[FSharpChecker] Current Queue Length: 0
[Checker] TryGetRecentCheckResultsForFile - d:\Source\Repos\\RevocationOrchestration\TokenRevocation\configurationSettings.fs
[LSP] PositionHandler - Cached typecheck results not yet available
[Error - 20:58:26] Request textDocument/hover failed.
  Message: Cached typecheck results not yet available
  Code: -32603 
```

This doesn't appear to be related to unexpected char in path to file

I'm also seeing with same in vs code insiders with the ionide experimental extension so I think its environment but I'm not sure what else to check in terms of processes that should be running or pre -reqs

**Comment by rfrerebe** [comment] 2019-09-05 12:34
Hello,

I had the same issue.
I solved it by deleting all `.ionide` folder above my workspace.
Deleting `.ionide` only in workspace root was not enough

**Comment by Krzysztof-Cieslak** [comment] 2019-09-17 17:18
Hey, I'd start with removing the `.ionide` folder as suggested by @rfrerebe and with removing any `bin` and `obj` folders in your project folders.

**Comment by rfrerebe** [comment] 2019-09-17 17:43
Hello,

Also if you have a sln file in your directory without your FSharp project,
it could also create this issue.
Solution is either to add fsproj to sln

dotnet sln add ./path/to/fsproj

Or remove sln file...

If you happen to work on csproj in Visual and fsproj in vs code, Visual
will create a sln for you and Ionide will stop working. I believe this is
by design, but it’s easy to forget this ...

**Comment by Krzysztof-Cieslak** [comment] 2019-09-17 17:49
Yes, `sln` behavior is by-design, indeed. If we detect `sln` file in workspace we load that by-default, otherwise we try to find all fsproj files in the workspace.

**Comment by ronaldschlenker** [comment] 2019-12-18 09:17
When I updated to 4.4.0, I have no intellisense / line lense / tool tips at all. Switches FSAC to core / netfw didn't have any effect.

I can reproduce this very easily: Create a new folder, open that in VSCode, create an empty fsx file and paste this code:

```open System

let x = 42
```

F# output:

```
[Error - 10:16:34] Request textDocument/documentSymbol failed.
  Message: File 'c:\Temp\test\test.fsx' not parsed
  Code: -32603 
[Error - 10:17:37] Request textDocument/hover failed.
  Message: File 'c:\Temp\test\test.fsx' not parsed
  Code: -32603 
[Error - 10:17:39] Request textDocument/hover failed.
  Message: File 'c:\Temp\test\test.fsx' not parsed
  Code: -32603 
[Error - 10:17:39] Request textDocument/hover failed.
  Message: File 'c:\Temp\test\test.fsx' not parsed
  Code: -32603 
```

**Comment by Krzysztof-Cieslak** [comment] 2019-12-18 10:40
@ronaldschlenker, should be working again in `4.4.1`

**Comment by ronaldschlenker** [comment] 2019-12-18 13:23
Wow, thanks @Krzysztof-Cieslak. That was quick. After Christmas, I try to finally set up a running dev environment for Ionide, so that I'm able to contribute some smaller things from time to time. Thanks again for your work. I have open collective donation on my TODO list for this year :)

**Comment by ronaldschlenker** [comment] 2019-12-23 09:00
From my POV, you can close this. It's fixed.

**Closed** 2020-01-17 19:40 UTC
Labels: bug, reproduction needed
