### ISSUE TITLE
[Backer] Suddenly, Ionide stopped showing me compilation errors

### ISSUE THREAD

**Issue by babysnakes** [ionide/ionide-vscode-fsharp#1518] opened 2021-03-24 15:53 UTC
### Describe the bug**

In the last day or two *Ionide* stopped showing me compilation errors in projects. It does show types and it does show errors when I open `fsx` files. Even if I add total junk (e.g. 'as;lkdfja;slkdjf') in the middle of a function, I only get spell check errors, no compilation errors.

### Steps to reproduce
For me it's just opening any `F#` project.

### Expected behaviour

Show compilation/syntax errors 😄 

### Screenshots

![Screenshot 2021-03-24 174429](https://user-images.githubusercontent.com/31975/112340020-d7fd9480-8cc8-11eb-8ae1-e6f991dec672.png)

## Machine info
 - OS: Windows 10 fully updated
 - .NET SDK version:5.0.201
 - Ionide version: v5.4.1

### Additional context
I'm also attaching two log files: the `F#` log and `window` log:
* [fsharp.log](https://github.com/ionide/ionide-vscode-fsharp/files/6198643/fsharp.log)
* [rendererLog.txt](https://github.com/ionide/ionide-vscode-fsharp/files/6198646/rendererLog.txt)

Please let me know if you need any further information.

Thanks in advance

Haim

**Comment by babysnakes** [comment] 2021-03-24 16:12
Started backing you (but I have no idea how to add `backer` label 🙂)

**Comment by cartermp** [comment] 2021-03-24 16:15
The bot is a bad bot and removes the label, so I updated the title

**Comment by baronfel** [comment] 2021-03-24 16:26
@babysnakes can you resubmit a log, but this time with the `FSharp.verboseLogging` flag set to 'true'?

**Comment by babysnakes** [comment] 2021-03-24 16:32
> @babysnakes can you resubmit a log, but this time with the `FSharp.verboseLogging` flag set to 'true'?

Sure, attaching the `F#` log with verbose logging (the window log seems to be the same length as the original - do you need it also?).

[fsharp-verbose.log](https://github.com/ionide/ionide-vscode-fsharp/files/6198944/fsharp-verbose.log)

**Comment by babysnakes** [comment] 2021-03-25 05:32
Update, this is really strange behavior. Today, when trying to make types show again (sometimes they disappear - I reload the window to make them show again) I closed and opened a file. Suddenly, not only the types began to show but show but also errors. Maybe some kind of weird caching thing. I'll continue working and update.

**Comment by nhirschey** [comment] 2021-03-25 12:50
1. This sounds like https://github.com/ionide/ionide-vscode-fsharp/issues/1500. The fix that @babysnakes describes sounds like the workaround that I document at the bottom of my issue. @babysnakes , does this sound right? 
    - If you close the folder while the file is still open, the next time you open the folder/file type checking will not work.
    - But, if you close the file and then close the folder, then the next time you open the folder and file then type checking will work properly. 
2. For the backer label, you need to add your github name to your open collective profile. Additionally the open collective bot seems to be case sensitive, so make sure it is exactly "babysnakes" and not "Babysnakes" in your opencollective profile.

**Comment by babysnakes** [comment] 2021-03-25 13:08
Hi @nhirschey 

1. This sounds right. I closed vscode (or just the folder) and reopened multiple times and it didn't help. Once I closed the file and re-opened it (even without closing and opening the folder) it started working. It now seems to work without a problem for a couple of hours.
2. Do you mean add the github URL in the settings page (that's the only place I saw a reference to github)? I did now. Will the label appear automatically?

Thanks

**Comment by nhirschey** [comment] 2021-03-25 13:13
@babysnakes yeah in settings, where it shows the github URL. But beware capitalization (I recently discovered that's why my issues never got the backer label).

It won't work retrospectively, but it should work on your next issue submission.

**Comment by babysnakes** [comment] 2021-03-25 13:20
@nhirschey thanks, I'll keep the ticket open for a couple of days and see how it goes. 

Also, thanks for the info regarding open collective 🙂.

**Comment by babysnakes** [comment] 2021-03-26 05:15
@nhirschey, it seems that you are right and I didn't reproduce my steps correctly. You **do** have to also close the folder and reopen before it shows compilation errors again.

@baronfel, @nhirschey should I close this ticket in favor in #1500 ?

Thanks.

**Comment by Martin521** [comment] 2021-06-07 09:06
To my observation, this happens
a) for new files that you add to the project
b) for the file that was open (visible) when you last closed VS Code.

**Comment by babysnakes** [comment] 2021-06-07 09:54
@Martin521, I'll try to see if it matches what happens to me.

**Comment by babysnakes** [comment] 2021-06-29 12:44
@Martin521, sorry, it took some time for me to go back to the `F#` project I was working on to test it. Reading your message again, you are surely correct even without testing as both cases are the cases that are not covered by the [work around suggested above](https://github.com/ionide/ionide-vscode-fsharp/issues/1518#issuecomment-806683398) 😄 .

**Comment by Krzysztof-Cieslak** [comment] 2021-11-19 16:24
Duplicate of  #1500

**Closed by Krzysztof-Cieslak** 2021-11-19 16:24 UTC
