### ISSUE TITLE
Info Panel shows incomplete generics signature

### ISSUE THREAD

**Issue by vilinski** [ionide/ionide-vscode-fsharp#1301] opened 2020-02-08 10:55 UTC
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. init a fake script
2. add paket hopac
3. add some code with complex generics, like from here: https://www.demystifyfp.com/fsharp/blog/concurrent-programming-in-fsharp-using-hopac-part-4/
4. Open Info panel on the side
5. Hower over the same function, which is currently displayed in the info panel

**Expected behaviour**
The same signature what is in tooltip looks like? with input ant output type parameters

**Screenshots**

<img width="1131" alt="Bildschirmfoto 2020-02-08 um 11 55 45" src="https://user-images.githubusercontent.com/259479/74083979-4aca9280-4a6a-11ea-9a7e-4e839632b6f7.png">

**Environment (please complete the following information):**
 - OS: MacOS Catalina
 - Ionide version: 4.5.0
 - VSCode version: 1.42
 - dotnet SDK version: 3.1.101
 - mono / .Net Framework version: .NET Core

**Comment by Krzysztof-Cieslak** [comment] 2020-02-14 16:30
Duplicate of https://github.com/ionide/ionide-vscode-fsharp/issues/1252

**Closed by Krzysztof-Cieslak** 2020-02-14 16:30 UTC
Labels: bug
