### ISSUE TITLE
Code formatting doesn't work in projects

### ISSUE THREAD

**Issue by drguildo** [ionide/ionide-vscode-fsharp#1352] opened 2020-04-27 10:54 UTC
Doing `Ctrl+Shift+P` and selecting `Format Document` does nothing when the file I'm editing is part of a project. If the file is a `.fsx` script it does work but then there are other issues such as #1351.

**Environment (please complete the following information):**
 - OS: Windows 10 1803
 - Ionide version: 4.9.0
 - VSCode version: 1.44.2
 - dotnet SDK version: 3.1.201

**Comment by drguildo** [comment] 2020-04-29 19:50
The more I use it the more broken code formatting seems. With "Format On Save" enabled I was just having it insert new lines at the point the cursor was located. 🤦‍♂️

**Comment by nicola-zen** [comment] 2020-05-15 10:27
I am experiencing the same behavior. How can we help in providing a reproduction scenario?

Attached a quick screen grab

![output](https://user-images.githubusercontent.com/19924054/82040757-5cde5180-96a7-11ea-8d8f-018e4733c35a.gif)

**Comment by SorrowAureus** [comment] 2020-06-06 21:42
Hi.

I was hit by the same issue, and my attempt at debugging it indicates that it caused by a lack of module/namespace in the Program.fs-file

I got an error like this:
`Fantomas.FormatConfig+FormatException: Parsing failed with errors: [|/home/user/Projects/FSharp/Demo/Program.fs (2,1)-(3,1) parse error Files in libraries or multiple-file applications must begin with a namespace or module declaration, e.g. 'namespace SomeNamespace.SubNamespace' or 'module SomeNamespace.SomeModule'. Only the last source file of an application may omit such a declaration.|]`
Adding a module to the file fixed it for me. Do note that in my case, Program.fs was in fact the last source file of the application.

**Comment by Krzysztof-Cieslak** [comment] 2020-06-06 21:56
CC: @nojaf any suggestions what may cause it?

**Comment by nojaf** [comment] 2020-06-07 10:25
This does ring a bell when we [parse the code to get the AST](https://github.com/fsprojects/fantomas/blob/e1a11ff868b3a704886c113e6b4aa9767a7c3970/src/Fantomas/CodeFormatterImpl.fs#L60).
If the name of the file is `Program.fs`, it is not considered to be a script file I think and then you get that error.

In the Fantomas CLI tool, we actually renamed the file name to something like `tmp.fsx` when we pass it to the FSharpChecker.
The main reason we don't do this all the time is that I think the internally compiler caching would not work anymore. Maybe we need an exception of `Program.fs` file names.

Does it make sense what I'm saying here @Krzysztof-Cieslak?

**Comment by neptunao** [comment] 2020-12-06 20:09
Have the same issue for `Program.fs` in my project. Does any workaround exist for this?

**Comment by Fubuchi** [comment] 2020-12-23 06:18
Just start to learn F# and be stumped by  this format issue too. Format only work on .fsx file and not .fs

**Comment by v-zubritsky** [comment] 2020-12-25 11:07
I could relate to this partially. Formatting works nice for all files except for the `Program.fs`.

Ionide version is 5.0.3
OS: Windows 10
Dotnet: 5.0.101
Vs code: 1.52.1

Most likely the same error in the F# output log as the one mentioned above

[Error - 14:04:23] Request textDocument/formatting failed.
  Message: Fantomas.FormatConfig+FormatException: Parsing failed with errors: [|d:\dev\bootcamp\src\Program.fs (1,1)-(2,1) parse error Files in libraries or multiple-file applications must begin with a namespace or module declaration, e.g. 'namespace SomeNamespace.SubNamespace' or 'module SomeNamespace.SomeModule'. Only the last source file of an application may omit such a declaration.|]
And options: { SourceFiles =
               [|"d:\dev\bootcamp\src\Main.fs";
                 "d:\dev\bootcamp\src\Program.fs"|]
  ConditionalCompilationDefines = []
  ErrorSeverityOptions = { WarnLevel = 3
                           GlobalWarnAsError = false
                           WarnOff = []
                           WarnOn = []
                           WarnAsError = []
                           WarnAsWarn = [] }
  IsInteractive = false
  LightSyntax = None
  CompilingFsLib = false
  IsExe = false }
   at Fantomas.CodeFormatterImpl.parse@70-2.Invoke(FSharpParseFileResults _arg2)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 404
   at <StartupCode$FSharp-Compiler-Service>.$Service.ParseFile@449-3.Invoke(AsyncActivation`1 ctxt) in F:\workspace\_work\1\s\src\fsharp\service\service.fs:line 449
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in F:\workspace\_work\1\s\src\fsharp\FSharp.Core\async.fs:line 104
  Code: -32603 
  
  Hope this helps! Thanks for the amazing project.

**Comment by nojaf** [comment] 2020-12-25 11:40
Ah, something comes to mind. Let me check in the next couple of days.

**Comment by nojaf** [comment] 2020-12-26 14:52
Ok, I believe I have a fix for this in [4.4.0-alpha-007](https://www.nuget.org/packages/Fantomas/4.4.0-alpha-007).
It worked on my machine 🙈.

You can download the NuGet package, unzip it and copy the `Fantomas.dll` file to your install location of the Ionide extension.
(For me this was at `C:\Users\nojaf\.vscode\extensions\ionide.ionide-fsharp-5.0.3\bin`).

**Comment by Fubuchi** [comment] 2020-12-26 14:58
Confirm worked on my machine without the need of a module declaration in Program.fs

**Comment by v-zubritsky** [comment] 2020-12-28 09:39
@nojaf worked for me as well

**Comment by Krzysztof-Cieslak** [comment] 2020-12-28 21:56
5.1 includes a prerelease version of Fantomas 4.4. so it should work out of the box now.

**Closed by Krzysztof-Cieslak** 2020-12-28 21:56 UTC
Labels: reproduction needed
