### ISSUE TITLE
FSI is readonly

### ISSUE THREAD

**Issue by haf** [ionide/ionide-vscode-fsharp#126] opened 2016-08-06 13:04 UTC
Install both vim mode and ionide and you cannot use FSI.

## Steps to repro

install `vscodevim` in its latest version.

install ionide in its latest version (-fsharp).

Run command "FSI: Start". Click the FSI to make it focus. For me cursor is now a vertical bar. Press a char, like 'b' for example. It's not output.

Custom editor keybindings:

```json
// Place your key bindings in this file to overwrite the defaults
[
  { "key": "ctrl+c", "command": "extension.vim_esc", "when": "editorTextFocus" },
  { "key": "cmd+b",  "command": "fake.buildDefault" },
  { "key": "cmd+r",  "command": "editor.action.rename", "when": "editorTextFocus" },
  { "key": "cmd+d",  "command": "editor.action.goToDeclaration",
                     "when": "editorTextFocus" },
  { "key": "ctrl+cmd+left", "command": "workbench.action.navigateBack" },
  { "key": "ctrl+cmd+right", "command": "workbench.action.navigateForward" }
]
```

### Workaround

None found.

### Expected behaviour

I can type in FSI.

### Versions

 - Latest everything, updated everything before filing the issue

**Comment by cloudRoutine** [comment] 2016-08-07 03:04
@haf  you'll have to provide more detail. Which Vim extension are you referring to? I just installed [this one](https://marketplace.visualstudio.com/items?itemName=vscodevim.vim) and it's been working along with FSI without issue.

![](http://i.imgur.com/xS8cPyP.png)

Perhaps your issue is with the keybindings? If so you can overwrite all of the defaults in your personal settings 

![](http://i.imgur.com/4fbEhqb.png)

**Comment by haf** [comment] 2016-08-07 06:47
Added some details.

**Comment by cloudRoutine** [comment] 2016-08-07 08:03
@haf FSI is readonly, it's always been readonly because @Krzysztof-Cieslak prefers it that way and I haven't taken the time to figure out a good way to implement an interactive version. Before VSCode introduced the integrated terminal there pretty much wasn't any way to have a text input box. 

(Maybe we could have made a custom html preview window and done something like using jquery to read the text in an input box and then send that to FSI in another process and render the responses in a pane, but it would have been a mess to implement :dizzy_face: )

So even though the integrated terminal is an improvement, you can only configure one particular integrated terminal, but you can open multiple instances of it. There's
```
    // Bash on Ubuntu (on Windows)
    "terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\bash.exe",
```
and that's all she wrote :disappointed: 

But we should be able to do something about it fairly soon

[from Expose integrated terminal extension API #9957](https://github.com/Microsoft/vscode/issues/9957)

> The initial extension API will allow:
> * Creating and optionally naming of a terminal instance
> * Sending commands (text sequences + '\n') to these "owned" terminal instances

[They've got more Vim improvements coming up too](https://github.com/Microsoft/vscode/issues/10145)

> * VIM - Continue to work on the API gaps backlog (see #8997) including
>   * :runner: Window/page scroll commands #9609 @sandy081
>   * More API to control folding, navigation with folding #9786 @aeschli
>   * Expose Undo history #8096 @alexandrudima
>   * Access to recently executed action #1431 @alexandrudima
>   * Add reason to selection change event #8093 @jrieken
>   * API for configuration settings #1396 (see below)

**Comment by cloudRoutine** [comment] 2016-08-07 08:43
@haf [If you haven't seen the Vim Extension's Roadmap yet, it's quite thorough](https://github.com/VSCodeVim/Vim/blob/master/ROADMAP.md#roadmap)

**Comment by Krzysztof-Cieslak** [comment] 2016-08-07 10:39
Yes, FSI is currently readonly. Both `by-design` and also because of missing APIs for extensions.

Best I can suggest for now (if you really want typing in FSI) is using integrated terminal and starting Interactive in there.

We can probably revisit this issue in next month - additional APIs for sending commands to terminal is planned by Code team for current iteration.

**Comment by haf** [comment] 2016-08-07 10:54
Sweet. :) No rush for my sake. Looking forward to hearing more about it.

**Comment by haf** [comment] 2016-08-07 10:55
PS; as you've become aware I'm mostly shifting towards Ionide now despite my rough initial steps with it.

**Comment by egamma** [comment] 2016-08-17 14:27
This issue is a duplicate of microsoft/vscode#10451

**Comment by Krzysztof-Cieslak** [comment] 2016-08-17 14:47
@egamma, sorry. I'm bit confused. I don't think it's connected to the issue you've linked.

As I've explained in previous post - FSI Panel right now is read-only by design (we basically use output panel for printing output from F# interactive [which is spawned in background as Node's child process).

We're planning to revisit this implementation when additional API for sending stuff to integrated terminal is available, but it has nothing to do with Vim mode right now :)

**Comment by egamma** [comment] 2016-08-17 16:53
Sorry I've only read the description and not the full discussion.

We have the the issue that we cannot distinguish between editor 'types', so when you install the VIM extension it impacts all editors that show up in VS Code. I thought the FSI panel suffers from this as well. Our problem is that in the Debug Console the entry field for expression is impacted by the VIM extension, but it should not be.

**Comment by zgramana** [comment] 2016-08-18 01:19
FWIW, As of 1.4, running `fsharpi` in the terminal console in combination with `workbench.action.terminal.runSelectedText` gets really close. If that command were to append `;;` when run, it would be reasonably usable.

**Comment by Krzysztof-Cieslak** [comment] 2016-09-25 14:41
Moved F# Interactive to Terminal API in `2.5.0`

**Closed by Krzysztof-Cieslak** 2016-09-25 14:41 UTC
Labels: enhancement, question
