### ISSUE TITLE
No Intellisense on scripts after VSCode update 1.61.1

### ISSUE THREAD

**Issue by bisen2** [ionide/ionide-vscode-fsharp#1604] opened 2021-10-15 12:51 UTC
### Describe the bug
Following a VSCode update to version `1.61.1 c13f1abb110fc756f9b3a6f16670df9cd9d4cf63 x64`, I no longer have intellisense in fsx files. I have tried reloading the window, reinstalling ionide, etc. The F# log gets filled with error messages:
```
[08:44:22.770 ERR] [LSP Server] HandleClientMessage - Error {"Code": -32601, "Message": "Method not found", "Data": null, "$type": "Error"} when handling notification {"Version": "2.0", "Method": "$/cancelRequest", "Params": {"Value": [[[]]], "$type": "Some"}, "$type": "Notification"}
```
and
```
[Error - 8:44:45 AM] Request textDocument/hover failed.
  Message: Cached typecheck results not yet available
  Code: -32603 
```

### Steps to reproduce
- Update VSCode
- Open fsx file

## Machine info
 - OS: Windows
 - .NET SDK version: 6.0.100-rc.2.21505.57
 - Ionide version: 5.7.3

**Comment by baronfel** [comment] 2021-10-15 12:53
Based on the fact that you have .net 6 installed, I'm going to say that this is a duplicate of the pinned issue https://github.com/ionide/ionide-vscode-fsharp/issues/1584

**Closed as completed** 2021-10-15 12:54 UTC
