### ISSUE TITLE
Intellisense broken with message 'Build was not evaluated'

### ISSUE THREAD

**Issue by adam-c-anderson** [ionide/ionide-vscode-fsharp#938] opened 2018-10-15 20:46 UTC
Apologies in advance, I do not have good repro steps for this, and I'm aware that this has historically 
 been a difficult bug to track down. I'm reporting everything I can think of here.

This error has started cropping up for us at design time, Intellisense stops working and the first symbol in each file in an affected project has a red squiggly with this message:

```
Problem reading assembly 'PATH_REDACTED': Build was not evaluated, expected the results to be ready after 'Eval' (GetCheckResultsAndImplementationsForProject, data = ("FinalizeTypeCheck", [|Id 1007; Id 1008; Id 1009; Id 1010; Id 1011|], Id 1013,
 false, None)).
```

All projects in the workspace build. We are targeting netcoreapp2.1, we have F# 4.5 installed, and Ionide version is 3.28.0. There are multiple projects in the workspace, one of them referenced by two other projects, which happened around the same time this problem started, but not sure they're actually related.

If I check out previous commits in our repo, the error message stops appearing in the affected projects, but no intellisense appears, either. Vertical space is made for the CodeLens annotations, but they never appear, even after doing a full `dotnet clean; paket install; dotnet build` for all and restarting Code. My teammate who added these projects says that intellisense worked in these projects up until a certain point but he doesn't know exactly when this started happening. Given that I can get my workspace into a state where neither intellisense nor the error message appears, it feels as though there is extra state lurking somewhere on my machine.

I know last time it had to do with referencing netstandard2.0 dependencies, but we've been referencing such dependencies without issue for some time prior to this problem occurring.

I've tried using `F#: clear cache`; that makes the red squiggles go away, but intellisense still doesn't work.

After clearing the cache, I did a full clean and rebuild, then reloaded Code and opened a file, waited for CodeLens space to appear with nothing in it, then checked the Ionide logs and observed multiple message groups like the following:

```
[08:53:03 DEBUG] REQ (008) -> {recordStubGenerator}, File = "PATH_REDACTED"
Data={"FileName":"PATH_REDACTED","Line":26,"Column":88,"Filter":""}

[08:53:03 DEBUG] RES (008) <- {recordStubGenerator} in 32 ms: Kind={"error"}
Data={"Code":1,"Message":"File 'PATH_REDACTED' not parsed","AdditionalData":{}}

[08:53:03 ERROR] Cannot execute recordStubGenerator, File 'PATH_REDACTED' not parsed 
```

**Comment by Krzysztof-Cieslak** [comment] 2018-10-16 13:16
Choose F# tab on the Activity Bar on the left - this should display solution explorer. Probably some/all projects failed to load. Right click on the project reporting an error and choose Show Project Status.

**Comment by adam-c-anderson** [comment] 2018-10-16 16:18
No, all projects loaded in the Ionide project explorer, and they all build. No problems in the problems pane, either.

**Comment by johlrich** [comment] 2018-10-18 14:01
I'm seeing the same errors within the last few days. Only things that changed on my machine was updating dotnet core sdk from 2.1.402 to 2.1.403 and Visual Studio to 15.8.7 (from like 15.8.3, i think). As a workaround, things currently work again if i change the fsacRuntime to net over netcore. 

The differences I notice in the logs occurs after the workspaceLoad response finishes. The next parse that goes out throws an exception about not being able to launch a process.

<details>
 <summary>runtime: netcore</summary>

```
 [09:15:13 DEBUG] RES (012) <- {parse} in 323 ms: Kind={"info"}
  Data="Request cancelled (exn was System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
    at System.Diagnostics.Process.Start()
    at FsAutoComplete.Utils.runProcess(FSharpFunc`2 log, String workingDir, String exePath, String args) in D:\\Programowanie\\ionide\\paket-files\\github.com\\fsharp\\FsAutoComplete\\src\\FsAutoComplete.Core\\Utils.fs:line 532
    at Dotnet.ProjInfo.Inspect.msbuild[a](MSBuildExePath msbuildExe, FSharpFunc`2 run, String project, FSharpList`1 args)
    at Dotnet.ProjInfo.Inspect.getProjectInfoOldSdk[a,b,c,d](FSharpFunc`2 log, FSharpFunc`2 msbuildExec, FSharpFunc`2 getArgs, FSharpList`1 additionalArgs, a projPath)
    at FsAutoComplete.NETFrameworkInfoProvider.getInfoFromMsbuild[a](FSharpFunc`2 getArgs, FSharpList`1 additionalProps) in D:\\Programowanie\\ionide\\paket-files\\github.com\\fsharp\\FsAutoComplete\\src\\FsAutoComplete.Core\\NETFrameworkInfoProvider.fs:line 46
    at FsAutoComplete.NETFrameworkInfoProvider.getInstalledNETVersions() in D:\\Programowanie\\ionide\\paket-files\\github.com\\fsharp\\FsAutoComplete\\src\\FsAutoComplete.Core\\NETFrameworkInfoProvider.fs:line 90
    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
    at System.Lazy`1.CreateValue()
    at FsAutoComplete.Environment.netReferecesAssembliesTFMLatest() in D:\\Programowanie\\ionide\\paket-files\\github.com\\fsharp\\FsAutoComplete\\src\\FsAutoComplete.Core\\Environment.fs:line 144
    at <StartupCode$FsAutoComplete-Core>.$CompilerServiceInterface.GetProjectOptionsFromScript@497.Invoke(Unit unitVar) in D:\\Programowanie\\ionide\\paket-files\\github.com\\fsharp\\FsAutoComplete\\src\\FsAutoComplete.Core\\CompilerServiceInterface.fs:line 497
    at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2)
    at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction))"`
```

</details>




<details>
 <summary>Both runtime's logs showed the same exe locations:</summary>

```
[09:15:12 DEBUG] RES (001) <- {compilerlocation} in 566 ms: Kind={"compilerlocation"}
Data={"Fsc":"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\FSharp\\fsc.exe","Fsi":"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\IDE\\CommonExtensions\\Microsoft\\FSharp\\fsi.exe","MSBuild":"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\MSBuild\\15.0\\bin\\MsBuild.exe"}
```

</details>

**Comment by johlrich** [comment] 2018-10-22 20:35
Update: After noticing Ionide autoupdated to 3.29.0, I tried netcore again and no longer see the above exception in the log and my projects are loading again.

**Comment by adam-c-anderson** [comment] 2018-10-25 12:38
Tried updating to 3.29.0 myself but still having the same problem. Tried clearing the F# cache again, rebuilding, reloading Code, etc. Verified the runtime is (still) `netcore`.

**Comment by da9l** [comment] 2018-11-12 10:04
I'm able to reproduce this (or at least a very similar problem) on Win 10 with latest build stack as per today. If I've done something wrong, please let me know... 

With a simple hello.fsx file. 
```fsharp
let hello = "hello"
```

When I have   "FSharp.fsacRuntime": "net" I get this in F# Language Service Console (ctrl+shift+U -> drop down)
```
[10:55:43 INFO ] .Net runtime specified
[10:55:44 INFO ] finding FSAC for
	runtime: NET
	mono: mono
	dotnet: C:\Program Files\dotnet\dotnet.exe
[10:55:45 INFO ] listening notification on /notify started
[10:55:45 INFO ] listening notification on /notifyWorkspace started
[10:55:45 INFO ] listening notification on /notifyAnalyzer started
[10:55:45 DEBUG] REQ (001) -> {compilerlocation}
Data=""
[10:55:45 DEBUG] RES (001) <- {compilerlocation} in 329 ms: Kind={"compilerlocation"}
Data={"Fsc":"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\Common7\\IDE\\CommonExtensions\\Microsoft\\FSharp\\fsc.exe","Fsi":"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\Common7\\IDE\\CommonExtensions\\Microsoft\\FSharp\\fsi.exe","MSBuild":"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\MSBuild\\15.0\\bin\\MsBuild.exe"}
[10:55:45 DEBUG] REQ (002) -> {compilerlocation}
Data=""
[10:55:45 DEBUG] RES (002) <- {compilerlocation} in 2 ms: Kind={"compilerlocation"}
Data={"Fsc":"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\Common7\\IDE\\CommonExtensions\\Microsoft\\FSharp\\fsc.exe","Fsi":"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\Common7\\IDE\\CommonExtensions\\Microsoft\\FSharp\\fsi.exe","MSBuild":"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\MSBuild\\15.0\\bin\\MsBuild.exe"}
[10:55:45 DEBUG] REQ (003) -> {compilerlocation}
Data=""
[10:55:45 DEBUG] REQ (004) -> {lint}, File = "c:\Users\se-danhegn-01\repos\codetest3\hello.fsx"
Data={"FileName":"c:\\Users\\se-danhegn-01\\repos\\codetest3\\hello.fsx"}
[10:55:45 DEBUG] REQ (005) -> {unusedOpens}, File = "c:\Users\se-danhegn-01\repos\codetest3\hello.fsx"
Data={"FileName":"c:\\Users\\se-danhegn-01\\repos\\codetest3\\hello.fsx"}
[10:55:45 DEBUG] REQ (006) -> {unusedDeclarations}, File = "c:\Users\se-danhegn-01\repos\codetest3\hello.fsx"
Data={"FileName":"c:\\Users\\se-danhegn-01\\repos\\codetest3\\hello.fsx"}
[10:55:45 DEBUG] REQ (007) -> {simplifiedNames}, File = "c:\Users\se-danhegn-01\repos\codetest3\hello.fsx"
Data={"FileName":"c:\\Users\\se-danhegn-01\\repos\\codetest3\\hello.fsx"}
[10:55:45 DEBUG] REQ (008) -> {workspacePeek}
Data={"Deep":2,"ExcludedDirs":[".git","paket-files",".fable"]}
[10:55:45 DEBUG] RES (007) <- {simplifiedNames} in 107 ms: Kind={"error"}
Data={"Code":1,"Message":"File 'c:\\Users\\se-danhegn-01\\repos\\codetest3\\hello.fsx' not parsed","AdditionalData":{}}
[10:55:45 ERROR] Cannot execute simplifiedNames, File 'c:\Users\se-danhegn-01\repos\codetest3\hello.fsx' not parsed 
[10:55:45 DEBUG] RES (003) <- {compilerlocation} in 112 ms: Kind={"compilerlocation"}
Data={"Fsc":"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\Common7\\IDE\\CommonExtensions\\Microsoft\\FSharp\\fsc.exe","Fsi":"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\Common7\\IDE\\CommonExtensions\\Microsoft\\FSharp\\fsi.exe","MSBuild":"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\MSBuild\\15.0\\bin\\MsBuild.exe"}
[10:55:45 DEBUG] RES (005) <- {unusedOpens} in 110 ms: Kind={"error"}
Data={"Code":1,"Message":"File 'c:\\Users\\se-danhegn-01\\repos\\codetest3\\hello.fsx' not parsed","AdditionalData":{}}
[10:55:45 ERROR] Cannot execute unusedOpens, File 'c:\Users\se-danhegn-01\repos\codetest3\hello.fsx' not parsed 
[10:55:45 DEBUG] RES (006) <- {unusedDeclarations} in 112 ms: Kind={"error"}
Data={"Code":1,"Message":"File 'c:\\Users\\se-danhegn-01\\repos\\codetest3\\hello.fsx' not parsed","AdditionalData":{}}
[10:55:45 ERROR] Cannot execute unusedDeclarations, File 'c:\Users\se-danhegn-01\repos\codetest3\hello.fsx' not parsed 
[10:55:45 DEBUG] RES (004) <- {lint} in 114 ms: Kind={"error"}
Data={"Code":1,"Message":"File 'c:\\Users\\se-danhegn-01\\repos\\codetest3\\hello.fsx' not parsed","AdditionalData":{}}
[10:55:45 ERROR] Cannot execute lint, File 'c:\Users\se-danhegn-01\repos\codetest3\hello.fsx' not parsed 
[10:55:45 ERROR] RES (008) <- {workspacePeek} ERROR in 120 ms: {stack: Error: Request failed with status code 500
	at createError (C:\Users\se-danhegn-01\.vscode\extensions\ionide.ionide-fsharp-3.29.0\fsharp.js:13103:15)
	at settle (C:\Users\se-danhegn-01\.vscode\extensions\ionide.ionide-fsharp-3.29.0\fsharp.js:17033:12)
	at IncomingMessage.handleStreamEnd (C:\Users\se-danhegn-01\.vscode\extensions\ionide.ionide-fsharp-3.29.0\fsharp.js:27857:11)
	at emitNone (events.js:111:20)
	at IncomingMessage.emit (events.js:208:7)
	at endReadableNT (_stream_readable.js:1056:12)
	at _combinedTickCallback (internal/process/next_tick.js:138:11)
	at process._tickCallback (internal/process/next_tick.js:180:9), message: Request failed with status code 500, config: [object Object], request: [object Object], response: [object Object]} Data=undefined
[10:55:45 DEBUG] REQ (009) -> {declarations}, File = "c:\Users\se-danhegn-01\repos\codetest3\hello.fsx"
Data={"FileName":"c:\\Users\\se-danhegn-01\\repos\\codetest3\\hello.fsx","Lines":["let hello = \"hello\""],"Version":0}
[10:55:46 DEBUG] RES (009) <- {declarations} in 449 ms: Kind={"declarations"}
Data=[{"Declaration":{"UniqueName":"Hello_1_of_1","Name":"Hello","Glyph":"Module","GlyphChar":"N","IsTopLevel":true,"Range":{"StartColumn":1,"StartLine":1,"EndColumn":1,"EndLine":2},"BodyRange":{"StartColumn":1,"StartLine":1,"EndColumn":20,"EndLine":1},"File":"c:\\Users\\se-danhegn-01\\repos\\codetest3\\hello.fsx","EnclosingEntity":"M","IsAbstract":false},"Nested":[{"UniqueName":"Hello_1_of_1","Name":"hello","Glyph":"Field","GlyphChar":"F","IsTopLevel":false,"Range":{"StartColumn":5,"StartLine":1,"EndColumn":20,"EndLine":1},"BodyRange":{"StartColumn":5,"StartLine":1,"EndColumn":20,"EndLine":1},"File":"c:\\Users\\se-danhegn-01\\repos\\codetest3\\hello.fsx","EnclosingEntity":"M","IsAbstract":false}]}]
[10:55:50 DEBUG] REQ (010) -> {tooltip}, File = "c:\Users\se-danhegn-01\repos\codetest3\hello.fsx"
Data={"FileName":"c:\\Users\\se-danhegn-01\\repos\\codetest3\\hello.fsx","Line":1,"Column":1,"Filter":""}
[10:55:50 DEBUG] RES (010) <- {tooltip} in 10 ms: Kind={"error"}
Data={"Code":1,"Message":"File 'c:\\Users\\se-danhegn-01\\repos\\codetest3\\hello.fsx' not parsed","AdditionalData":{}}
[10:55:50 ERROR] Cannot execute tooltip, File 'c:\Users\se-danhegn-01\repos\codetest3\hello.fsx' not parsed 
[10:55:51 DEBUG] REQ (011) -> {tooltip}, File = "c:\Users\se-danhegn-01\repos\codetest3\hello.fsx"
Data={"FileName":"c:\\Users\\se-danhegn-01\\repos\\codetest3\\hello.fsx","Line":1,"Column":2,"Filter":""}
[10:55:51 DEBUG] RES (011) <- {tooltip} in 2 ms: Kind={"error"}
Data={"Code":1,"Message":"File 'c:\\Users\\se-danhegn-01\\repos\\codetest3\\hello.fsx' not parsed","AdditionalData":{}}
[10:55:51 ERROR] Cannot execute tooltip, File 'c:\Users\se-danhegn-01\repos\codetest3\hello.fsx' not parsed 
[10:55:51 DEBUG] REQ (012) -> {tooltip}, File = "c:\Users\se-danhegn-01\repos\codetest3\hello.fsx"
Data={"FileName":"c:\\Users\\se-danhegn-01\\repos\\codetest3\\hello.fsx","Line":1,"Column":8,"Filter":""}
[10:55:51 DEBUG] RES (012) <- {tooltip} in 3 ms: Kind={"error"}
Data={"Code":1,"Message":"File 'c:\\Users\\se-danhegn-01\\repos\\codetest3\\hello.fsx' not parsed","AdditionalData":{}}
[10:55:51 ERROR] Cannot execute tooltip, File 'c:\Users\se-danhegn-01\repos\codetest3\hello.fsx' not parsed 
[10:55:56 DEBUG] REQ (013) -> {tooltip}, File = "c:\Users\se-danhegn-01\repos\codetest3\hello.fsx"
Data={"FileName":"c:\\Users\\se-danhegn-01\\repos\\codetest3\\hello.fsx","Line":1,"Column":10,"Filter":""}
[10:55:56 DEBUG] RES (013) <- {tooltip} in 7 ms: Kind={"error"}
Data={"Code":1,"Message":"File 'c:\\Users\\se-danhegn-01\\repos\\codetest3\\hello.fsx' not parsed","AdditionalData":{}}
[10:55:56 ERROR] Cannot execute tooltip, File 'c:\Users\se-danhegn-01\repos\codetest3\hello.fsx' not parsed 
[10:55:56 DEBUG] REQ (014) -> {tooltip}, File = "c:\Users\se-danhegn-01\repos\codetest3\hello.fsx"
Data={"FileName":"c:\\Users\\se-danhegn-01\\repos\\codetest3\\hello.fsx","Line":1,"Column":14,"Filter":""}
[10:55:56 DEBUG] RES (014) <- {tooltip} in 2 ms: Kind={"error"}
Data={"Code":1,"Message":"File 'c:\\Users\\se-danhegn-01\\repos\\codetest3\\hello.fsx' not parsed","AdditionalData":{}}
[10:55:56 ERROR] Cannot execute tooltip, File 'c:\Users\se-danhegn-01\repos\codetest3\hello.fsx' not parsed 
[10:55:57 DEBUG] REQ (015) -> {tooltip}, File = "c:\Users\se-danhegn-01\repos\codetest3\hello.fsx"
Data={"FileName":"c:\\Users\\se-danhegn-01\\repos\\codetest3\\hello.fsx","Line":1,"Column":14,"Filter":""}
[10:55:57 DEBUG] RES (015) <- {tooltip} in 2 ms: Kind={"error"}
Data={"Code":1,"Message":"File 'c:\\Users\\se-danhegn-01\\repos\\codetest3\\hello.fsx' not parsed","AdditionalData":{}}
[10:55:57 ERROR] Cannot execute tooltip, File 'c:\Users\se-danhegn-01\repos\codetest3\hello.fsx' not parsed 
```

With "FSharp.fsacRuntime": "netcore"
I get another error:

```
[11:01:02 INFO ] Netcore runtime specified
[11:01:02 INFO ] finding FSAC for
	runtime: NetcoreFdd
	mono: mono
	dotnet: C:\Program Files\dotnet\dotnet.exe
[11:01:03 INFO ] listening notification on /notify started
[11:01:03 INFO ] listening notification on /notifyWorkspace started
[11:01:03 INFO ] listening notification on /notifyAnalyzer started
[11:01:03 DEBUG] REQ (001) -> {compilerlocation}
Data=""
[11:01:03 DEBUG] REQ (002) -> {lint}, File = "c:\Users\se-danhegn-01\repos\codetest3\hello.fsx"
Data={"FileName":"c:\\Users\\se-danhegn-01\\repos\\codetest3\\hello.fsx"}
[11:01:03 DEBUG] REQ (003) -> {unusedOpens}, File = "c:\Users\se-danhegn-01\repos\codetest3\hello.fsx"
Data={"FileName":"c:\\Users\\se-danhegn-01\\repos\\codetest3\\hello.fsx"}
[11:01:03 DEBUG] REQ (004) -> {unusedDeclarations}, File = "c:\Users\se-danhegn-01\repos\codetest3\hello.fsx"
Data={"FileName":"c:\\Users\\se-danhegn-01\\repos\\codetest3\\hello.fsx"}
[11:01:03 DEBUG] REQ (005) -> {simplifiedNames}, File = "c:\Users\se-danhegn-01\repos\codetest3\hello.fsx"
Data={"FileName":"c:\\Users\\se-danhegn-01\\repos\\codetest3\\hello.fsx"}
[11:01:03 DEBUG] REQ (006) -> {workspacePeek}
Data={"Deep":2,"ExcludedDirs":[".git","paket-files",".fable"]}
[11:01:03 DEBUG] REQ (007) -> {declarations}, File = "c:\Users\se-danhegn-01\repos\codetest3\hello.fsx"
Data={"FileName":"c:\\Users\\se-danhegn-01\\repos\\codetest3\\hello.fsx","Lines":["let hello = \"hello\""],"Version":0}
[11:01:03 DEBUG] RES (004) <- {unusedDeclarations} in 357 ms: Kind={"error"}
Data={"Code":1,"Message":"File 'c:\\Users\\se-danhegn-01\\repos\\codetest3\\hello.fsx' not parsed","AdditionalData":{}}
[11:01:03 ERROR] Cannot execute unusedDeclarations, File 'c:\Users\se-danhegn-01\repos\codetest3\hello.fsx' not parsed 
[11:01:03 DEBUG] RES (002) <- {lint} in 360 ms: Kind={"error"}
Data={"Code":1,"Message":"File 'c:\\Users\\se-danhegn-01\\repos\\codetest3\\hello.fsx' not parsed","AdditionalData":{}}
[11:01:03 ERROR] Cannot execute lint, File 'c:\Users\se-danhegn-01\repos\codetest3\hello.fsx' not parsed 
[11:01:03 DEBUG] RES (003) <- {unusedOpens} in 360 ms: Kind={"error"}
Data={"Code":1,"Message":"File 'c:\\Users\\se-danhegn-01\\repos\\codetest3\\hello.fsx' not parsed","AdditionalData":{}}
[11:01:03 ERROR] Cannot execute unusedOpens, File 'c:\Users\se-danhegn-01\repos\codetest3\hello.fsx' not parsed 
[11:01:03 DEBUG] RES (005) <- {simplifiedNames} in 359 ms: Kind={"error"}
Data={"Code":1,"Message":"File 'c:\\Users\\se-danhegn-01\\repos\\codetest3\\hello.fsx' not parsed","AdditionalData":{}}
[11:01:03 ERROR] Cannot execute simplifiedNames, File 'c:\Users\se-danhegn-01\repos\codetest3\hello.fsx' not parsed 
[11:01:03 DEBUG] RES (001) <- {compilerlocation} in 364 ms: Kind={"compilerlocation"}
Data={"Fsc":"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\Common7\\IDE\\CommonExtensions\\Microsoft\\FSharp\\fsc.exe","Fsi":"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\Common7\\IDE\\CommonExtensions\\Microsoft\\FSharp\\fsi.exe","MSBuild":"C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\MSBuild\\15.0\\bin\\MsBuild.exe"}
[11:01:03 ERROR] RES (006) <- {workspacePeek} ERROR in 482 ms: {stack: Error: Request failed with status code 500
	at createError (C:\Users\se-danhegn-01\.vscode\extensions\ionide.ionide-fsharp-3.29.0\fsharp.js:13103:15)
	at settle (C:\Users\se-danhegn-01\.vscode\extensions\ionide.ionide-fsharp-3.29.0\fsharp.js:17033:12)
	at IncomingMessage.handleStreamEnd (C:\Users\se-danhegn-01\.vscode\extensions\ionide.ionide-fsharp-3.29.0\fsharp.js:27857:11)
	at emitNone (events.js:111:20)
	at IncomingMessage.emit (events.js:208:7)
	at endReadableNT (_stream_readable.js:1056:12)
	at _combinedTickCallback (internal/process/next_tick.js:138:11)
	at process._tickCallback (internal/process/next_tick.js:180:9), message: Request failed with status code 500, config: [object Object], request: [object Object], response: [object Object]} Data=undefined
[11:01:04 DEBUG] RES (007) <- {declarations} in 554 ms: Kind={"declarations"}
Data=[{"Declaration":{"UniqueName":"Hello_1_of_1","Name":"Hello","Glyph":"Module","GlyphChar":"N","IsTopLevel":true,"Range":{"StartColumn":1,"StartLine":1,"EndColumn":1,"EndLine":2},"BodyRange":{"StartColumn":1,"StartLine":1,"EndColumn":20,"EndLine":1},"File":"c:\\Users\\se-danhegn-01\\repos\\codetest3\\hello.fsx","EnclosingEntity":"M","IsAbstract":false},"Nested":[{"UniqueName":"Hello_1_of_1","Name":"hello","Glyph":"Field","GlyphChar":"F","IsTopLevel":false,"Range":{"StartColumn":5,"StartLine":1,"EndColumn":20,"EndLine":1},"BodyRange":{"StartColumn":5,"StartLine":1,"EndColumn":20,"EndLine":1},"File":"c:\\Users\\se-danhegn-01\\repos\\codetest3\\hello.fsx","EnclosingEntity":"M","IsAbstract":false}]}]
```

**Comment by reinux** [comment] 2019-02-12 04:16
I'm having the same issue, ever since I referenced another project. Tinkering with the .fsproj for long enough eventually makes it go away for a few minutes, before it comes back again.

```
Problem reading assembly '<project>\Common.dll': Build was not evaluated, expected the results to be ready after 'Eval' (GetCheckResultsAndImplementationsForProject, data = ("FinalizeTypeCheck", [|Id 1021; Id 1022; Id 1023; Id 1024; Id 1025|], Id 1027,
 false, None)).
```

**Comment by hoetz** [comment] 2019-02-13 07:16
I get this issue almost every time I open a project, all I have to do is open the fsproj file change a blank, save the file and it it works again.

**Comment by Krzysztof-Cieslak** [comment] 2019-03-15 11:29
Duplicate of #924

**Closed by Krzysztof-Cieslak** 2019-03-15 11:29 UTC
Labels: bug, dotnet/sdk projects, reproduction needed
