### ISSUE TITLE
Ionide doesn't work with multi-target project

### ISSUE THREAD

**Issue by dustinmoris** [ionide/ionide-vscode-fsharp#435] opened 2017-05-13 08:16 UTC
When a project has more than one build target then intellisense and all other awesome Ionide features stop working:

```xml
<Project Sdk="FSharp.NET.Sdk;Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net40;netstandard1.6</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Lib.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FSharp.NET.Sdk" Version="1.*" PrivateAssets="All" />
    <PackageReference Include="FSharp.Core" Version="4.*" />
  </ItemGroup>
</Project>
```

**Comment by Krzysztof-Cieslak** [comment] 2017-05-13 10:36
Duplicate of https://github.com/ionide/ionide-vscode-fsharp/issues/416

**Closed by Krzysztof-Cieslak** 2017-05-13 10:36 UTC
