### ISSUE TITLE
ide glitches when using names under "inverted apices": `` ``

### ISSUE THREAD

**Issue by tonyx** [ionide/ionide-vscode-fsharp#1421] opened 2020-09-25 08:10 UTC
**if you have code under `` `` the ide glitches and sometimes you have to restart**

Unit tests sometimes are more readable allowing spaces in their names,
so you may want to use `` `` to allow this, having tests like
    let ``two plus two must be equal to four``() =
but something may go wrong when you try to do it

**To Reproduce**
in a project using a unit test library like NUnit
create a test like:

    [<Test>]
    let ``two plus two must be equal to four``() =
       Assert.AreEqual(4,2+3)
            
**Expected behaviour**
everything should be fine, and you should be able to continue 
working. But Vs code sometimes stop working
and you have to restart Vs code.

**Environment (please complete the following information):**
 - OS: Windows 10 pro
 - Ionide version 4.17
 - VSCode version: 1.49.1
 - dotnet SDK version: 3.1.100
 - mono / .Net Framework version:  4.8.03752

**Additional context**
That was true also for previous versions of Ionide under Mac os X using Mono.

**Comment by MangelMaxime** [comment] 2020-09-25 08:30
Probably related to https://github.com/ionide/ionide-vscode-fsharp/issues/1073

**Comment by Krzysztof-Cieslak** [comment] 2020-09-25 14:36
Duplicate of #1073

**Closed by Krzysztof-Cieslak** 2020-09-25 14:36 UTC
