### ISSUE TITLE
Scrolling within F# file causes freeze

### ISSUE THREAD

**Issue by cynic** [ionide/ionide-vscode-fsharp#1507] opened 2021-02-28 20:20 UTC
### Describe the bug**
Scrolling within an F# file causes VS Code to freeze and become unresponsive while CPU usage spikes.  After some time (seconds or minutes, seems to depend on total size of codebase?), interactivity returns.

### Steps to reproduce
1. Open an F# file that is long enough (mine is around 200 lines).
2. Hold down the down-arrow to scroll down.  Hold down the up arrow to scroll up.
3. Within 4-8 seconds, the interface will freeze completely while CPU usage spikes.

### Link to sample reproduction
https://github.com/cynic/Oware.git
Use file "UnitTest1.fs".

### Expected behaviour
Scrolling in the file should work.  Interface should not freeze.

## Machine info
 - OS: Windows
 - .NET SDK version: 5.0.101
 - Ionide version: 5.3.2

### Additional context
Debug log reports this message, repeated tens of times:
[2021-02-28 22:11:19.398] [exthost] [error] [Ionide.Ionide-fsharp] provider FAILED
[2021-02-28 22:11:19.398] [exthost] [error] Error: No symbol information found
	at c:\Users\cinyc\.vscode\extensions\ionide.ionide-fsharp-5.3.2\fsharp.js:2:160568
	at c:\Users\cinyc\.vscode\extensions\ionide.ionide-fsharp-5.3.2\fsharp.js:2:160862
	at Immediate.<anonymous> (c:\Users\cinyc\.vscode\extensions\ionide.ionide-fsharp-5.3.2\fsharp.js:2:161225)
	at processImmediate (internal/timers.js:456:21)

**Comment by ImaginaryDevelopment** [comment] 2021-03-03 14:45
This has happened to me intermittently when using Vim to scroll up or down, I thought it was a vim thing. I'm not saying it wouldn't happen using the arrow keys in my case, just noting that my scrolling uses vim keys.

**Comment by cynic** [comment] 2021-03-04 04:13
Just noticed that when I'm editing a 200+ line standalone .fsx file—even one with #r "nuget:" references—the problem does _not_ occur.  So my current guess is that it is somehow related to having a "project" within which the .fs file resides, or to something specific related to test projects.

**Comment by da9l** [comment] 2021-03-25 11:36
I've seen this problem occur whenever there are functions named with double backticks.
```
let ``When house 2 is used, seeds go to the other houses``
```
In files without them it works. When I put the cursor in the name and start editing it VSCode hang.

In the example file provided all the test functions are named like this. The only workaround I've found is to not use ` ``Double back tick`` ` functions.
Really annoying.
#backer

**Comment by Krzysztof-Cieslak** [comment] 2021-03-25 13:53
Duplicate of #1073

**Closed by Krzysztof-Cieslak** 2021-03-25 13:53 UTC
