### ISSUE TITLE
No error highlighting

### ISSUE THREAD

**Issue by wihedro** [ionide/ionide-vscode-fsharp#1225] opened 2019-09-29 21:55 UTC
Error highlighting is complete gone. Intellisense, tooltips, LineLens and ect. works fine.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a .fsx file
2. Error highlighting does not work

**Expected behaviour**
Red line under errors in code.

**Screenshots**
<img width="340" alt="Screenshot 2019-09-29 at 23 46 38" src="https://user-images.githubusercontent.com/8903435/65840032-025cd480-e314-11e9-9504-22cf1835585e.png">

**Environment (please complete the following information):**
 - OS: Mac OS 10.14.6
 - Ionide version: 4.1.0
 - VSCode version: 1.38.1
 - dotnet SDK version: 3.0.100
 - mono: 6.4.0.198

**Comment by Krzysztof-Cieslak** [comment] 2019-10-08 16:45
Duplicate of #1220

**Closed by Krzysztof-Cieslak** 2019-10-08 16:45 UTC
