### ISSUE TITLE
Version 5.7.2 does not work

### ISSUE THREAD

**Issue by bartoszluka** [ionide/ionide-vscode-fsharp#1577] opened 2021-09-10 09:13 UTC
### Describe the bug**
Opening an F# file (.fs, .fsx) does not start a language server or any other ionide features. Running "F#: Get Ionide logs" from command palette returns an error.

"Command 'F#: Get Ionide logs' resulted in an error (command 'fsharp.diagnostics.getIonideLogs' not found)"

### Steps to reproduce
1. Update extension to version 5.7.2
2. Open any F# file
3. No syntax highlighting is present (except basic 'let' keywords)
	
### Expected behaviour
Language server should start as it was working in the version 5.7.1

### Screenshots
Get Ionide logs command:
![image](https://user-images.githubusercontent.com/72729880/132829538-7c9d2333-4918-4687-9deb-c69b20485da5.png)

version 5.7.1:
![image](https://user-images.githubusercontent.com/72729880/132829980-2a73dc07-5421-4746-bce7-4335ee27179f.png)

version 5.7.2:
![image](https://user-images.githubusercontent.com/72729880/132830086-b86864a1-dc06-46b8-b982-94745df6077c.png)

# Machine info
 - OS: Windows 10 (20H2, build: 19042.1165)
 - .NET SDK version: 5.0.400
 - Ionide version: 5.7.2

### Additional context
Rolling back to 5.7.1 fixes everything.

**Comment by Krzysztof-Cieslak** [comment] 2021-09-10 12:11
Duplicate of #1576

**Closed by Krzysztof-Cieslak** 2021-09-10 12:11 UTC
