### ISSUE TITLE
Characters typed are reordered

### ISSUE THREAD

**Issue by rojepp** [ionide/ionide-vscode-fsharp#927] opened 2018-10-08 19:58 UTC
When you type F# code reasonably fast, the order of characters get mangled. It looks to me like error checking is kicking in and moving the cursor somehow. Happens all the time lately, but I've only seen it with F# code. This is me typing 'copyFiltered' correctly:

![mangled](https://user-images.githubusercontent.com/445888/46630621-09a83280-cb45-11e8-9dd6-aeb3ba6f5e97.gif)

**Comment by Krzysztof-Cieslak** [comment] 2018-10-08 22:39
I don’t think it’s caused by Ionide, TBF it looks like a bug in VSCode (either it’s just bug in editor part or extension slowing something too much [and that shouldn’t happen])

**Comment by Krzysztof-Cieslak** [comment] 2018-10-08 22:40
Can you please create an issue on Code’s repo and ping me there?

**Comment by Krzysztof-Cieslak** [comment] 2018-10-11 22:36
I’m closing it since I’m 100% sure that an extensions shouldn’t impact typing experience in any way - if they do it’s a bug in VSCode

**Closed by Krzysztof-Cieslak** 2018-10-11 22:36 UTC

**Comment by rojepp** [comment] 2018-10-12 05:56
You’re right, I’ve since seen it it C# code too, just been too busy. Sorry for wasting your time.

**Comment by rojepp** [comment] 2018-10-12 10:06
https://github.com/Microsoft/vscode/issues/60762
