### ISSUE TITLE
fsi.sendSelection and fsi.sendLine add ^? to the prompt preventing the next line executing. 

### ISSUE THREAD

**Issue by npmurphy** [ionide/ionide-vscode-fsharp#365] opened 2017-02-17 15:14 UTC
On Mono 4.8 beta on OSx and Linux, using fsi.sendSelection prints several "^?" to the F# interactive prompt after running a command.  
Unless the ^?'s are manually deleted, the next command will fail. 

Run `let x = 1.0`
```
> let x = 1.0
- ;;

val x : float = 1.0

> ^?^?
``` 
Then run `let y = 2.0`
```
>^?^?let y = 2.0

/home/user/scratch.fsx(8,1): error FS0010: Unexpected character '' in interaction
- ;;
> ^?^?
```

Possibly related: when a new F#i session is started, the command is written through the welcome text and more garbled control characters appear. 
```
val x : float = 1.0F# 4.1
Freely distributed under the Apache 2.0 Open Source License
> ^?^?212;3R^?^?let y = 2.0
```

**Comment by Krzysztof-Cieslak** [comment] 2017-02-17 15:16
Duplicate of https://github.com/ionide/ionide-vscode-fsharp/issues/352

**Closed by Krzysztof-Cieslak** 2017-02-17 15:16 UTC
