### ISSUE TITLE
Using fsacruntime with netcore setting causes errors in UI when using non .Net standard type providers

### ISSUE THREAD

**Issue by bruinbrown** [ionide/ionide-vscode-fsharp#992] opened 2019-01-18 10:49 UTC
I have a project with a non .Net core type provider which uses the fsproj file change supplied by Don to enable it to work in .Net core projects. This was developed with the fsacruntime set to net. With the runtime set to net there are no problems with Ionide.

I then opened another project and Ionide encouraged me to switch over to fsacruntime=netcore which I did.

I reopened the original .Net core project with a non .Net core type provider. This build fine on the command line but in Ionide I get errors on any types provided by the type provider. I've attached a screenshot below which shows the type provider issues.

![image](https://user-images.githubusercontent.com/1132003/51382412-b021ad80-1b0e-11e9-9554-d1d8f02acf3b.png)

**Comment by Krzysztof-Cieslak** [comment] 2019-03-15 10:59
Duplicate of #1026

**Closed by Krzysztof-Cieslak** 2019-03-15 10:59 UTC
Labels: reproduction needed
