### ISSUE TITLE
Cannot read property 'Data'

### ISSUE THREAD

**Issue by vilinski** [ionide/ionide-vscode-fsharp#299] opened 2016-12-05 18:02 UTC
Hi, 

since last update my Ionide is broken. Works only in downgrade to older (2.11.*) versions. The part of my logs:

> [Extension Host] [IONIDE-FSAC] RES (004) <- {declarations} ERROR in 28 ms: {SyntaxError: Unexpected end of JSON input}, Data=%O
> 
> shell.ts:440 Cannot read property 'Data' of null: TypeError: Cannot read property 'Data' of null
>     at C:\Users\asvili\.vscode\extensions\Ionide.Ionide-fsharp-2.12.0\Components\CodeLens.js:130:60
>     at process._tickCallback (internal/process/next_tick.js:103:7)
> 
> [Extension Host] rejected promise not handled within 1 second
> shell.ts:440 Cannot read property 'Data' of null: TypeError: Cannot read property 'Data' of null
>     at C:\Users\asvili\.vscode\extensions\Ionide.Ionide-fsharp-2.12.0\Core\Project.js:144:14
>     at C:\Users\asvili\.vscode\extensions\Ionide.Ionide-fsharp-2.12.0\fable_external\Helpers-729269674.js:63:13
>     at process._tickCallback (internal/process/next_tick.js:103:7)e.onUnexpectedError @ shell.ts:440
> 
> shell.ts:440 Cannot read property 'Data' of null: TypeError: Cannot read property 'Data' of null
>     at C:\Users\asvili\.vscode\extensions\Ionide.Ionide-fsharp-2.12.0\Core\Project.js:144:14
>     at C:\Users\asvili\.vscode\extensions\Ionide.Ionide-fsharp-2.12.0\fable_external\Helpers-729269674.js:63:13
>     at process._tickCallback (internal/process/next_tick.js:103:7)e.onUnexpectedError @ shell.ts:440

Last stable VSCode behind dorp proxy on windows 7 
Is there something known about or is here any workaround?

**Comment by CloudStu** [comment] 2016-12-06 01:44
I'm seeing the same error in the console output. This manifests in the editor window as broken references (I'm getting errors in my open statements). I'm using Fable, and the errors only affect vscode. The Fable compiler is quite happy to build (meaning the references aren't really broken).

In addition, I see a couple of errors in the FSAC output.
````
[02:27:59 ERROR] FSAC stderr: 
Process is terminated due to StackOverflowException.

(ommitted info messages)

[02:28:07 ERROR] RES (015) <- {completion} ERROR in 69 ms: {"SyntaxError: Unexpected token u in JSON at position 0"}, Data=undefined
````
This only seems to occur when looking at .fs files, backed by a .fsproj. I also have an .fsx that works fine (successfully using #r for the same references as those broken in the .fsproj).

I do not have this issue on a separate machine. One notable difference between the two is that my broken machine has VS2017 RC installed, whereas the working machine has VS2015.

Let me know if I can provide further details.

**Comment by CloudStu** [comment] 2016-12-06 01:47
#291 Potentially a duplicate.

**Comment by vilinski** [comment] 2016-12-06 10:28
Yes it seems to be a duplicate.

- I have tried to install VS2017RC and then ditched it. Seems it has left some traces. Would like to know how to diagnose and remove them.
- And this is a solution with two f# projects stuff.fsproj and stuff.test.fsproj - so one of them with dot in the file name.

I have updated to 2.12.1 with the same result
it is still something strange with unexpected end of Json input on each file open or editing:

> [Extension Host] [IONIDE-FSAC] REQ (005) -> {project}, File = "\~\src\stuff\stuff.fsproj"
> extensionHost.ts:255 [Extension Host] [IONIDE-FSAC] REQ (006) -> {lint}, File = "\~\src\stuff\File.fs"
> extensionHost.ts:255 [Extension Host] [IONIDE-FSAC] RES (005) <- {project} ERROR in 39 ms: {SyntaxError: Unexpected end of JSON input}, Data=%O
> extensionHost.ts:255 [Extension Host] [IONIDE-FSAC] RES (006) <- {lint} ERROR in 39 ms: {SyntaxError: Unexpected end of JSON input}, Data=%O
> extensionHost.ts:255 [Extension Host] [IONIDE-FSAC] REQ (007) -> {parse}, File = "~\src\suff\File.fs"
> extensionHost.ts:255 [Extension Host] [IONIDE-FSAC] RES (007) <- {parse} ERROR in 29 ms: {SyntaxError: Unexpected end of JSON input}, Data=%O
> extensionHost.ts:255 [Extension Host] [IONIDE-FSAC] REQ (008) -> {declarations}, File = "\~\src\stuff\File.fs"
> extensionHost.ts:255 [Extension Host] [IONIDE-FSAC] RES (008) <- {declarations} ERROR in 33 ms: {SyntaxError: Unexpected end of JSON input}, Data=%O
> shell.ts:440 Cannot read property 'Data' of null: TypeError: Cannot read property 'Data' of null
>     at C:\Users\asvili\.vscode\extensions\Ionide.Ionide-fsharp-2.12.1\Components\CodeLens.js:130:60
>     at process._tickCallback (internal/process/next_tick.js:103:7)e.onUnexpectedError @ shell.ts:440(anonymous function) @ shell.ts:353e.onUnexpectedError @ errors.ts:68r @ errors.ts:83v @ winjs.base.raw.js:1209enter @ winjs.base.raw.js:901_run @ winjs.base.raw.js:1068_error @ winjs.base.raw.js:1041v @ winjs.base.raw.js:1209enter @ winjs.base.raw.js:901_run @ winjs.base.raw.js:1068_error @ winjs.base.raw.js:1041(anonymous function) @ async.ts:358done @ winjs.base.raw.js:1378v @ winjs.base.raw.js:1224enter @ winjs.base.raw.js:901_run @ winjs.base.raw.js:1068_error @ winjs.base.raw.js:1041e.resolveErr @ ipcRemoteCom.ts:110f @ ipcRemoteCom.ts:198_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
> extensionHost.ts:255 [Extension Host] rejected promise not handled within 1 second
> shell.ts:440 Cannot read property 'Data' of null: TypeError: Cannot read property 'Data' of null
>     at C:\Users\asvili\.vscode\extensions\Ionide.Ionide-fsharp-2.12.1\Core\Project.js:144:14
>     at C:\Users\asvili\.vscode\extensions\Ionide.Ionide-fsharp-2.12.1\fable_external\Helpers-729269674.js:63:13
>     at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by Krzysztof-Cieslak** [comment] 2016-12-09 16:34
`FSAC stderr: Process is terminated due to StackOverflowException` and VS2017 suggest it's duplicate of #291

**Closed by Krzysztof-Cieslak** 2016-12-09 16:34 UTC

**Comment by jkone27** [comment] 2021-12-06 09:48
got this issue again today, what shall i do to fix it?
