### ISSUE TITLE
Warnings / Errors persist after files are closed / moved / deleted

### ISSUE THREAD

**Issue by moonPtr** [ionide/ionide-vscode-fsharp#798] opened 2018-04-27 13:38 UTC
Annoying
![code_2018-04-27_15-37-51](https://user-images.githubusercontent.com/32428601/39365294-ff96b04a-4a30-11e8-9ce8-134ce52cbf26.png)
![code_2018-04-27_15-38-00](https://user-images.githubusercontent.com/32428601/39365297-006bf93a-4a31-11e8-8859-7e4c3f4fa941.png)

**Comment by Krzysztof-Cieslak** [comment] 2018-04-27 14:48
Duplicate of https://github.com/ionide/ionide-vscode-fsharp/issues/730

**Closed by Krzysztof-Cieslak** 2018-04-27 14:48 UTC
