### ISSUE TITLE
Intellisense not working

### ISSUE THREAD

**Issue by chriskuech** [ionide/ionide-vscode-fsharp#1568] opened 2021-08-17 03:34 UTC
### Describe the bug**
The extension does not seem to work at all.  There is no error highlighting or completion recommendations.

### Steps to reproduce
Open an F# project in VS Code on macOS.

### Link to sample reproduction
N/A

### Expected behaviour
Syntax highlighting is aware of dependencies, errors are red underlined, autocompletions work etc

### Screenshots

![image](https://user-images.githubusercontent.com/3680671/129659185-afc3ce10-2fa7-4253-b578-c8314cfefe85.png)
![image](https://user-images.githubusercontent.com/3680671/129659218-e3ed3aa8-1c2d-42df-915c-f4078296e914.png)

## Machine info
 - OS: Mac
 - .NET SDK version: 5.0.400
 - Ionide version: `latest`

### Additional context
Projects work fine in Visual Studio for Mac, just not VS Code.

**Comment by klettier** [comment] 2021-08-21 10:00
Same here the extension is not working anymore, here is the VSCode log

```
console.ts:137 [Extension Host] (node:14176) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `Code --trace-deprecation ...` to show where the warning was created)
S @ console.ts:137
console.ts:137 [Extension Host] DOTNET PATH: C:\Program Files\dotnet\dotnet.exe
console.ts:137 [Extension Host] FSAC (NETCORE): error while invoking: Command failed: C:\Program Files\dotnet\dotnet.exe --version'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
console.ts:137 [Extension Host] FSAC (NETCORE): 'c:\Users\FSharp\.vscode\extensions\ionide.ionide-fsharp-5.7.1/bin/fsautocomplete.dll'
notificationsAlerts.ts:40 The F# server crashed 5 times in the last 3 minutes. The server will not be restarted.
onDidChangeNotification @ notificationsAlerts.ts:40
console.ts:137 [Extension Host] [LineLens] Activating
console.ts:137 [Extension Host] [PipelineHints] Activating
mainThreadExtensionService.ts:63 [[object Object]]Cannot read property 'indexOf' of undefined
$onExtensionRuntimeError @ mainThreadExtensionService.ts:63
mainThreadExtensionService.ts:64 TypeError: Cannot read property 'indexOf' of undefined
	at c:\Users\FSharp\.vscode\extensions\ionide.ionide-fsharp-5.7.1\fsharp.js:2:424162
	at c:\Users\FSharp\.vscode\extensions\ionide.ionide-fsharp-5.7.1\fsharp.js:1:14869
	at e.next (c:\Users\FSharp\.vscode\extensions\ionide.ionide-fsharp-5.7.1\fsharp.js:1:10479)
	at e.value (c:\Users\FSharp\.vscode\extensions\ionide.ionide-fsharp-5.7.1\fsharp.js:1:9939)
	at Object.next (c:\Users\FSharp\.vscode\extensions\ionide.ionide-fsharp-5.7.1\fsharp.js:1:25590)
	at Function.from (<anonymous>)
	at k (c:\Users\FSharp\.vscode\extensions\ionide.ionide-fsharp-5.7.1\fsharp.js:1:36306)
	at ReadFileContext.callback (c:\Users\FSharp\.vscode\extensions\ionide.ionide-fsharp-5.7.1\fsharp.js:2:424074)
	at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:273:13)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:64
mainThreadExtensionService.ts:63 [[object Object]]Cannot read property 'indexOf' of undefined
$onExtensionRuntimeError @ mainThreadExtensionService.ts:63
mainThreadExtensionService.ts:64 TypeError: Cannot read property 'indexOf' of undefined
	at c:\Users\FSharp\.vscode\extensions\ionide.ionide-fsharp-5.7.1\fsharp.js:2:424162
	at c:\Users\FSharp\.vscode\extensions\ionide.ionide-fsharp-5.7.1\fsharp.js:1:14869
	at e.next (c:\Users\FSharp\.vscode\extensions\ionide.ionide-fsharp-5.7.1\fsharp.js:1:10479)
	at e.value (c:\Users\FSharp\.vscode\extensions\ionide.ionide-fsharp-5.7.1\fsharp.js:1:9939)
	at Object.next (c:\Users\FSharp\.vscode\extensions\ionide.ionide-fsharp-5.7.1\fsharp.js:1:25590)
	at Function.from (<anonymous>)
	at k (c:\Users\FSharp\.vscode\extensions\ionide.ionide-fsharp-5.7.1\fsharp.js:1:36306)
	at ReadFileContext.callback (c:\Users\FSharp\.vscode\extensions\ionide.ionide-fsharp-5.7.1\fsharp.js:2:424074)
	at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:273:13)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:64
mainThreadExtensionService.ts:63 [[object Object]]Cannot read property 'indexOf' of undefined
$onExtensionRuntimeError @ mainThreadExtensionService.ts:63
mainThreadExtensionService.ts:64 TypeError: Cannot read property 'indexOf' of undefined
	at c:\Users\FSharp\.vscode\extensions\ionide.ionide-fsharp-5.7.1\fsharp.js:2:424162
	at c:\Users\FSharp\.vscode\extensions\ionide.ionide-fsharp-5.7.1\fsharp.js:1:14869
	at e.next (c:\Users\FSharp\.vscode\extensions\ionide.ionide-fsharp-5.7.1\fsharp.js:1:10479)
	at e.value (c:\Users\FSharp\.vscode\extensions\ionide.ionide-fsharp-5.7.1\fsharp.js:1:9939)
	at Object.next (c:\Users\FSharp\.vscode\extensions\ionide.ionide-fsharp-5.7.1\fsharp.js:1:25590)
	at Function.from (<anonymous>)
	at k (c:\Users\FSharp\.vscode\extensions\ionide.ionide-fsharp-5.7.1\fsharp.js:1:36306)
	at ReadFileContext.callback (c:\Users\FSharp\.vscode\extensions\ionide.ionide-fsharp-5.7.1\fsharp.js:2:424074)
	at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:273:13)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:64
localProcessExtensionHost.ts:272 Extension Host
localProcessExtensionHost.ts:273 [LineLens] Config Changed event[LineLens] Installing[LineLens] Installed[PipelineHints] Config Changed event[PipelineHints] Installing[PipelineHints] Installed[GitIgnore] gitignore path: c:\Users\FSharp\Documents\code\fsharp\temp\hacker\.gitignore[GitIgnore] Error accessing gitignore file [Error: ENOENT: no such file or directory, open 'c:\Users\FSharp\Documents\code\fsharp\temp\hacker\.gitignore'	at Object.openSync (fs.js:476:3)	at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1846)	at Object.readFileSync (fs.js:377:35)	at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8872)	at Du (c:\Users\FSharp\.vscode\extensions\ionide.ionide-fsharp-5.7.1\fsharp.js:2:506180)	at c:\Users\FSharp\.vscode\extensions\ionide.ionide-fsharp-5.7.1\fsharp.js:2:506395	at Object.then (c:\Users\FSharp\.vscode\extensions\ionide.ionide-fsharp-5.7.1\fsharp.js:1:58506)] {  errno: -4058,  syscall: 'open',  code: 'ENOENT',  path: 'c:\\Users\\FSharp\\Documents\\code\\fsharp\\temp\\hacker\\.gitignore'}

```

**Comment by graydon** [comment] 2021-09-15 20:52
Seeing this also -- extension is no longer working at all. Seems to have started in past few weeks.

**Comment by baronfel** [comment] 2021-09-15 20:54
@graydon any additional info you can provide with regards to machine state? OS/.Net SDK Version, etc?  And/or a particular repro where you're seeing it?

**Comment by graydon** [comment] 2021-09-15 20:56
dotnet --version says 5.0.400, OS is ubuntu 20.04 LTS.

using ionide v5.7.3 remotely from win10 vscode client:

Version: 1.60.1 (user setup)
Commit: 83bd43bc519d15e50c4272c6cf5c1479df196a4d
Date: 2021-09-10T17:07:10.714Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by baronfel** [comment] 2021-09-15 20:58
Thank you. Can you set `FSharp.verboseLogging` to `true` in your settings.json, reload, and provide the contents of the `F#` output pane to help give us pointers in the direction of where the issue lies?

**Comment by graydon** [comment] 2021-09-15 23:56
Hm, in the process of trying to enable it (uninstall, reinstall, set flag, restart) it has started working again, partially. I will continue to monitor and post back a log if I see it fail again.

**Comment by baronfel** [comment] 2021-09-16 00:00
Thanks! In case there was a misunderstanding, when I said reload in my previous comment I meant use the reload window command from the command palette, which restarts all of the extensions you have loaded with any configuration changes you've made without actually closing the application and losing your opened directory context. I use this as a short way of forcing settings that require a restart to take effect. You shouldn't have to do a full uninstall reinstall cycle.

**Comment by pkese** [comment] 2021-09-21 14:09
This is what I got when Ionide failed to load (see attached file below)

That's using remote-ssh session. Sometimes it loads, sometimes it doesn't.

When this happens I:
- close vscode on local machine, 
- ssh to remote machine
- kill all remaining vscode proceccess:
```
> ps -ef | grep code
peter      81611   81568  0 15:15 ?        00:00:00 sh /home/peter/.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/server.sh --start-server --host=127.0.0.1 --enable-remote-auto-shutdown --port=0 --connection-secret /home/peter/.vscode-server/.83bd43bc519d15e50c4272c6cf5c1479df196a4d.token
peter      81618   81611  0 15:15 ?        00:00:02 /home/peter/.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/node /home/peter/.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/out/vs/server/main.js --start-server --host=127.0.0.1 --enable-remote-auto-shutdown --port=0 --connection-secret /home/peter/.vscode-server/.83bd43bc519d15e50c4272c6cf5c1479df196a4d.token
peter      81650   81618  0 15:15 ?        00:00:00 /home/peter/.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/node /home/peter/.vscode-server/bin/83bd43bc519d15e50c4272c6cf5c1479df196a4d/out/bootstrap-fork --type=ptyHost

> kill 81611 81618 81650
```
... and that makes it (at leasts I think) more likely to work again. If feels really random, whether it works or not.

[vscode-app-1632232990106.log](https://github.com/ionide/ionide-vscode-fsharp/files/7203696/vscode-app-1632232990106.log)

**Comment by pkese** [comment] 2021-09-21 14:23
Ok ... it's not about killing stale processes (that doesn't help).

What I found out is that if I:
- disable Ionide,
- reload vscode (to get Ionide disabled)
- and then re-enable Ionide,
then Ionide loads from inside the process without need to reload and then everything seems to work fine.

Then after a reload, I get back to non-functional Ionide.

Attached is a log, of vscode session when Ionide is Enabled and gets successfuly loaded (as opposed to above when it doesn't).

[vscode-app-1632234182335.log](https://github.com/ionide/ionide-vscode-fsharp/files/7203829/vscode-app-1632234182335.log)

**Comment by baronfel** [comment] 2021-09-21 14:40
@pkese can you try setting the [FSharp.dotnetRoot](https://ionide.io/Editors/Code/options.html#fsharpdotnetroot) setting in your settings.json file? this tells ionide which directory to look for `dotnet`/`dotnet.exe` in. If this value is set we use it, otherwise we use `where`/`which` (depending on platform) to look in your shell for the `dotnet` binary to use.

**Comment by pkese** [comment] 2021-09-21 14:50
@baronfel that seems to fix it (I tried reloading it several times and it works including remote ssh session).

It's interesting that if I set it through the vscode config, then vscode sets it as `FSharp.dotNetRoot` (notice capital 'N' in dotNet) in `settings.json` and nothing happens. But if I manually set `FSharp.dotnetRoot` then it works.

**Comment by baronfel** [comment] 2021-09-21 14:52
that's likely a typo/mismatch between the place where the setting is _defined_ in the extension's [package.json](https://github.com/ionide/ionide-vscode-fsharp/blob/master/release/package.json#L1460), and the place where the setting is [consumed in the actual code](https://github.com/ionide/ionide-vscode-fsharp/blob/master/src/Core/Environment.fs#L42). unfortunately it's not a declarative/linked system and there's no linting that I'm aware of to ensure consistency there. We'll get that fixed up right now though.

**Comment by baronfel** [comment] 2021-09-22 14:42
This is a good spot, it looks like the library we're using doesn't automatically wrap fully-qualified commands which contain spaces.  I'll see if we can do a quick release with this fix (I'd expect that it's hitting quite a few windows folks, since the default paths include spaces).

**Comment by baronfel** [comment] 2021-09-22 14:59
Well now I'm quite confused, because my windows machine doesn't exhibit the space-error that @klettier's logs showed. @klettier can you confirm if this is an issue for you on the latest version, or any other environmental details?

**Comment by klettier** [comment] 2021-09-22 20:48
hi, with version `5.7.3` the issue is fixed 👍

**Comment by baronfel** [comment] 2021-09-22 21:10
Glad to hear it! I was expecting it would have, since this sort of command handling was part of the reason for the changes released in 5.7.3 :)

**Comment by TheFoolishPupil** [comment] 2021-09-23 18:48
I'm facing similar issues. I have my entire Extension Host crash when opening an fsharp project in vscode. Everything was working about a week ago last I opened the project.

dotnet: 5.0.400
MacOS
Ionide-fsharp: 5.7.3
<img width="860" alt="Screenshot 2021-09-23 at 20 47 51" src="https://user-images.githubusercontent.com/43202406/134566024-444c4bc8-927b-4880-989a-5f11c4692ea9.png">

**Comment by baronfel** [comment] 2021-09-23 18:58
hey, nice! there's a stack trace with line numbers! it looks like there may be a bug in the fsi watcher stuff that we can dig into.

**Comment by TheFoolishPupil** [comment] 2021-09-23 19:03
haha thanks @baronfel, turns out there was some issue with an extension I had installed in the mean time. 'Regex Workbench
 - stephen-riley', uninstalling that and everything is working again.

**Comment by queil** [comment] 2021-09-29 19:48
Hey guys, I've found this issue and facing the same although none of the workarounds proposed solve the problem. My log:
```
console.ts:137 [Extension Host] (node:25308) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.fsharp.
Old grammar file: file:///c%3A/Users/kris/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/fsharp/syntaxes/fsharp.tmLanguage.json.
New grammar file: vscode-remote://wsl%2Bubuntu-20.04/home/kris/.vscode-server/extensions/ionide.ionide-fsharp-5.7.3/syntaxes/fsharp.json
console.ts:137 [Extension Host] DOTNET PATH: /usr/bin/dotnet
console.ts:137 [Extension Host] FSAC (NETCORE): '/home/kris/.vscode-server/extensions/ionide.ionide-fsharp-5.7.3/bin/fsautocomplete.dll'
console.ts:137 [Extension Host] [LineLens] Activating
console.ts:137 [Extension Host] [PipelineHints] Activating
mainThreadExtensionService.ts:63 [[object Object]]Cannot read property 'indexOf' of undefined
mainThreadExtensionService.ts:64 TypeError: Cannot read property 'indexOf' of undefined
	at vscode-file://vscode…p-5.7.3/fsharp.js:2
	at vscode-file://vscode…p-5.7.3/fsharp.js:1
	at e.next (vscode-file://vscode…p-5.7.3/fsharp.js:1)
	at e.value (vscode-file://vscode…p-5.7.3/fsharp.js:1)
	at Object.next (vscode-file://vscode…p-5.7.3/fsharp.js:1)
	at Function.from (<anonymous>)
	at k (vscode-file://vscode…p-5.7.3/fsharp.js:1)
	at ReadFileContext.<anonymous> (vscode-file://vscode…p-5.7.3/fsharp.js:2)
	at ReadFileContext.callback (vscode-file://vscode…/graceful-fs.js:123)
	at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:273)
mainThreadExtensionService.ts:63 [[object Object]]Cannot read property 'indexOf' of undefined
mainThreadExtensionService.ts:64 TypeError: Cannot read property 'indexOf' of undefined
	at vscode-file://vscode…p-5.7.3/fsharp.js:2
	at vscode-file://vscode…p-5.7.3/fsharp.js:1
	at e.next (vscode-file://vscode…p-5.7.3/fsharp.js:1)
	at e.value (vscode-file://vscode…p-5.7.3/fsharp.js:1)
	at Object.next (vscode-file://vscode…p-5.7.3/fsharp.js:1)
	at Function.from (<anonymous>)
	at k (vscode-file://vscode…p-5.7.3/fsharp.js:1)
	at ReadFileContext.<anonymous> (vscode-file://vscode…p-5.7.3/fsharp.js:2)
	at ReadFileContext.callback (vscode-file://vscode…/graceful-fs.js:123)
	at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:273)
mainThreadExtensionService.ts:63 [[object Object]]Cannot read property 'indexOf' of undefined
mainThreadExtensionService.ts:64 TypeError: Cannot read property 'indexOf' of undefined
	at vscode-file://vscode…p-5.7.3/fsharp.js:2
	at vscode-file://vscode…p-5.7.3/fsharp.js:1
	at e.next (vscode-file://vscode…p-5.7.3/fsharp.js:1)
	at e.value (vscode-file://vscode…p-5.7.3/fsharp.js:1)
	at Object.next (vscode-file://vscode…p-5.7.3/fsharp.js:1)
	at Function.from (<anonymous>)
	at k (vscode-file://vscode…p-5.7.3/fsharp.js:1)
	at ReadFileContext.<anonymous> (vscode-file://vscode…p-5.7.3/fsharp.js:2)
	at ReadFileContext.callback (vscode-file://vscode…/graceful-fs.js:123)
	at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:273)
﻿
​```

**Comment by baronfel** [comment] 2021-09-29 19:50
@queil it looks like your dotnet path is to `/usr/bin/dotnet`, this is a symlink to a binary, correct? Try the suggestion above to set `FSharp.dotnetRoot` to the `/usr/share/dotnet` directory and see if that fixes you up.

**Comment by queil** [comment] 2021-09-29 19:53
@baronfel Tried that now and unfortunately it doesn't seem to fix the issue:

```
[Extension Host] (node:7656) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)
TMScopeRegistry.ts:45 Overwriting grammar scope name to file mapping for scope source.fsharp.
Old grammar file: file:///c%3A/Users/kris/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/fsharp/syntaxes/fsharp.tmLanguage.json.
New grammar file: vscode-remote://wsl%2Bubuntu-20.04/home/kris/.vscode-server/extensions/ionide.ionide-fsharp-5.7.3/syntaxes/fsharp.json
console.ts:137 [Extension Host] DOTNET PATH: /usr/share/dotnet/dotnet
console.ts:137 [Extension Host] FSAC (NETCORE): '/home/kris/.vscode-server/extensions/ionide.ionide-fsharp-5.7.3/bin/fsautocomplete.dll'
console.ts:137 [Extension Host] [LineLens] Activating
console.ts:137 [Extension Host] [PipelineHints] Activating
mainThreadExtensionService.ts:63 [[object Object]]Cannot read property 'indexOf' of undefined
mainThreadExtensionService.ts:64 TypeError: Cannot read property 'indexOf' of undefined
	at vscode-file://vscode…p-5.7.3/fsharp.js:2
	at vscode-file://vscode…p-5.7.3/fsharp.js:1
	at e.next (vscode-file://vscode…p-5.7.3/fsharp.js:1)
	at e.value (vscode-file://vscode…p-5.7.3/fsharp.js:1)
	at Object.next (vscode-file://vscode…p-5.7.3/fsharp.js:1)
	at Function.from (<anonymous>)
	at k (vscode-file://vscode…p-5.7.3/fsharp.js:1)
	at ReadFileContext.<anonymous> (vscode-file://vscode…p-5.7.3/fsharp.js:2)
	at ReadFileContext.callback (vscode-file://vscode…/graceful-fs.js:123)
	at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:273)
mainThreadExtensionService.ts:63 [[object Object]]Cannot read property 'indexOf' of undefined
mainThreadExtensionService.ts:64 TypeError: Cannot read property 'indexOf' of undefined
	at vscode-file://vscode…p-5.7.3/fsharp.js:2
	at vscode-file://vscode…p-5.7.3/fsharp.js:1
	at e.next (vscode-file://vscode…p-5.7.3/fsharp.js:1)
	at e.value (vscode-file://vscode…p-5.7.3/fsharp.js:1)
	at Object.next (vscode-file://vscode…p-5.7.3/fsharp.js:1)
	at Function.from (<anonymous>)
	at k (vscode-file://vscode…p-5.7.3/fsharp.js:1)
	at ReadFileContext.<anonymous> (vscode-file://vscode…p-5.7.3/fsharp.js:2)
	at ReadFileContext.callback (vscode-file://vscode…/graceful-fs.js:123)
	at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:273)
mainThreadExtensionService.ts:63 [[object Object]]Cannot read property 'indexOf' of undefined
mainThreadExtensionService.ts:64 TypeError: Cannot read property 'indexOf' of undefined
	at vscode-file://vscode…p-5.7.3/fsharp.js:2
	at vscode-file://vscode…p-5.7.3/fsharp.js:1
	at e.next (vscode-file://vscode…p-5.7.3/fsharp.js:1)
	at e.value (vscode-file://vscode…p-5.7.3/fsharp.js:1)
	at Object.next (vscode-file://vscode…p-5.7.3/fsharp.js:1)
	at Function.from (<anonymous>)
	at k (vscode-file://vscode…p-5.7.3/fsharp.js:1)
	at ReadFileContext.<anonymous> (vscode-file://vscode…p-5.7.3/fsharp.js:2)
	at ReadFileContext.callback (vscode-file://vscode…/graceful-fs.js:123)
	at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:273)
﻿
​
```

**Comment by queil** [comment] 2021-09-29 20:10
@baronfel I am sorry. The extension does actually work now, despite throwing all the same errors in Dev Tools.

**Comment by jackmott** [comment] 2021-11-07 21:33
I ran into this bug today on Linux (Pop OS)  installed dotnet 5, installed vscode, installed ionide extension. Did all of this last night, and it was working.  Rebooted, started vscode from the popos app menu, and F# projects wouldn't load.  Set the dotNetroot, and that fixed it.

**Comment by Krzysztof-Cieslak** [comment] 2021-11-19 15:37
Since setting `FSharp.dotNetRoot` seems to be solving most of the problems, I'm closing this one. 
If you continue to have any problems please create a separate issue and provide details for your specific case.

**Closed by Krzysztof-Cieslak** 2021-11-19 15:37 UTC
