### ISSUE TITLE
ionide doesn't work after latest update

### ISSUE THREAD

**Issue by coolya** [ionide/ionide-vscode-fsharp#511] opened 2017-08-26 22:33 UTC
Af I updates to the latest version (2.3.40 on mac OS) of ionide it completely stopped working. 

It's a mixed project with one fable netcore project and one mono framework 4.6.1 fsproj. 

The logs show no real reasons: 
```
[00:29:07 DEBUG] REQ (001) -> {project}, File = "~/frontend/birdvoices.fsproj"
Data={"FileName":"/Users/kdummann/source/rubecula/frontend/frontend/birdvoices.fsproj"}
[00:29:08 DEBUG] REQ (002) -> {project}, File = "~/importer/importer.fsproj"
Data={"FileName":"/Users/kdummann/source/rubecula/frontend/importer/importer.fsproj"}
[00:29:08 DEBUG] REQ (003) -> {declarations}, File = "~/importer/importer.fs"
Data={"FileName":"/Users/kdummann/source/rubecula/frontend/importer/importer.fs","Version":1}
[00:29:08 ERROR] RES (002) <- {project} ERROR in 164 ms: Error: Request failed with status code 500 Data=undefined
[00:29:08 ERROR] RES (001) <- {project} ERROR in 572 ms: Error: Request failed with status code 500 Data=undefined
[00:29:08 DEBUG] RES (003) <- {declarations} in 109 ms: Kind={"error"}
Data={"Code":1,"Message":"File '/Users/kdummann/source/rubecula/frontend/importer/importer.fs' not parsed","AdditionalData":{}}
[00:29:08 ERROR] Cannot execute declarations, File '/Users/kdummann/source/rubecula/frontend/importer/importer.fs' not parsed 
[00:29:08 DEBUG] REQ (004) -> {tooltip}, File = "~/importer/importer.fs"
Data={"FileName":"/Users/kdummann/source/rubecula/frontend/importer/importer.fs","Line":136,"Column":1,"Filter":""}
[00:29:08 DEBUG] RES (004) <- {tooltip} in 14 ms: Kind={"error"}
Data={"Code":1,"Message":"File '/Users/kdummann/source/rubecula/frontend/importer/importer.fs' not parsed","AdditionalData":{}}
[00:29:08 ERROR] Cannot execute tooltip, File '/Users/kdummann/source/rubecula/frontend/importer/importer.fs' not parsed 
[00:29:12 DEBUG] REQ (005) -> {project}, File = "~/importer/importer.fsproj"
Data={"FileName":"/Users/kdummann/source/rubecula/frontend/importer/importer.fsproj"}
[00:29:12 ERROR] RES (005) <- {project} ERROR in 11 ms: Error: Request failed with status code 500 Data=undefined
[00:29:28 DEBUG] REQ (006) -> {project}, File = "~/importer/importer.fsproj"
Data={"FileName":"/Users/kdummann/source/rubecula/frontend/importer/importer.fsproj"}
[00:29:28 ERROR] RES (006) <- {project} ERROR in 8 ms: Error: Request failed with status code 500 Data=undefined
[00:29:28 DEBUG] REQ (007) -> {declarations}, File = "~/importer/Arguments.fs"
Data={"FileName":"/Users/kdummann/source/rubecula/frontend/importer/Arguments.fs","Version":1}
[00:29:28 DEBUG] RES (007) <- {declarations} in 8 ms: Kind={"error"}
Data={"Code":1,"Message":"File '/Users/kdummann/source/rubecula/frontend/importer/Arguments.fs' not parsed","AdditionalData":{}}
[00:29:28 ERROR] Cannot execute declarations, File '/Users/kdummann/source/rubecula/frontend/importer/Arguments.fs' not parsed 
[00:29:41 DEBUG] REQ (008) -> {project}, File = "~/frontend/birdvoices.fsproj"
Data={"FileName":"/Users/kdummann/source/rubecula/frontend/frontend/birdvoices.fsproj"}
[00:29:41 ERROR] RES (008) <- {project} ERROR in 5 ms: Error: Request failed with status code 500 Data=undefined
[00:29:41 DEBUG] REQ (009) -> {declarations}, File = "~/frontend/src/App.fs"
Data={"FileName":"/Users/kdummann/source/rubecula/frontend/frontend/src/App.fs","Version":1}
[00:29:41 DEBUG] RES (009) <- {declarations} in 6 ms: Kind={"error"}
Data={"Code":1,"Message":"File '/Users/kdummann/source/rubecula/frontend/frontend/src/App.fs' not parsed","AdditionalData":{}}
[00:29:41 ERROR] Cannot execute declarations, File '/Users/kdummann/source/rubecula/frontend/frontend/src/App.fs' not parsed 
[00:29:42 DEBUG] REQ (010) -> {tooltip}, File = "~/frontend/src/App.fs"
Data={"FileName":"/Users/kdummann/source/rubecula/frontend/frontend/src/App.fs","Line":246,"Column":26,"Filter":""}
[00:29:42 DEBUG] RES (010) <- {tooltip} in 3 ms: Kind={"error"}
Data={"Code":1,"Message":"File '/Users/kdummann/source/rubecula/frontend/frontend/src/App.fs' not parsed","AdditionalData":{}}
[00:29:42 ERROR] Cannot execute tooltip, File '/Users/kdummann/source/rubecula/frontend/frontend/src/App.fs' not parsed 
[00:29:53 DEBUG] REQ (011) -> {project}, File = "~/frontend/birdvoices.fsproj"
Data={"FileName":"/Users/kdummann/source/rubecula/frontend/frontend/birdvoices.fsproj"}
[00:29:53 ERROR] RES (011) <- {project} ERROR in 6 ms: Error: Request failed with status code 500 Data=undefined
[00:30:07 DEBUG] REQ (012) -> {declarations}, File = "~/frontend/src/App.fs"
Data={"FileName":"/Users/kdummann/source/rubecula/frontend/frontend/src/App.fs","Version":1}
[00:30:07 DEBUG] RES (012) <- {declarations} in 4 ms: Kind={"error"}
Data={"Code":1,"Message":"File '/Users/kdummann/source/rubecula/frontend/frontend/src/App.fs' not parsed","AdditionalData":{}}
[00:30:07 ERROR] Cannot execute declarations, File '/Users/kdummann/source/rubecula/frontend/frontend/src/App.fs' not parsed 
[00:31:02 DEBUG] REQ (013) -> {project}, File = "~/frontend/birdvoices.fsproj"
Data={"FileName":"/Users/kdummann/source/rubecula/frontend/frontend/birdvoices.fsproj"}
[00:31:02 ERROR] RES (013) <- {project} ERROR in 8 ms: Error: Request failed with status code 500 Data=undefined
[00:31:12 DEBUG] REQ (014) -> {tooltip}, File = "~/frontend/src/App.fs"
Data={"FileName":"/Users/kdummann/source/rubecula/frontend/frontend/src/App.fs","Line":276,"Column":39,"Filter":""}
[00:31:12 DEBUG] RES (014) <- {tooltip} in 3 ms: Kind={"error"}
Data={"Code":1,"Message":"File '/Users/kdummann/source/rubecula/frontend/frontend/src/App.fs' not parsed","AdditionalData":{}}
[00:31:12 ERROR] Cannot execute tooltip, File '/Users/kdummann/source/rubecula/frontend/frontend/src/App.fs' not parsed 
``

**Comment by Krzysztof-Cieslak** [comment] 2017-08-26 22:38
Try running `Clear Cache` command

**Comment by Krzysztof-Cieslak** [comment] 2017-08-27 06:37
Also, people on Slack reports that `dotnet restore --no-cache ` should also help

**Comment by coolya** [comment] 2017-08-27 07:03
While that fixed the problem for the fable dotnetcore fsproj, the "normal" dotnet framework project is still not working correctly. 

In the project explorer there are no files shown for it:

<img width="247" alt="screenshot 2017-08-27 08 57 43" src="https://user-images.githubusercontent.com/407216/29747801-e6555a68-8b05-11e7-92e7-1af39f1f9156.png">

If I open a file from that project it's not able to find any referenced assemblies.

When ionide tries to load the project I get this error message:

```
[09:00:52 DEBUG] REQ (001) -> {project}, File = "~/importer.fsproj"
Data={"FileName":"/Users/kdummann/source/rubecula/frontend/importer/importer.fsproj"}
[09:00:53 DEBUG] RES (001) <- {project} in 809 ms: Kind={"project"}
Data={"Project":"/Users/kdummann/source/rubecula/frontend/importer/importer.fsproj","Files":[],"Output":"null","References":["/Library/Frameworks/Mono.framework/Versions/5.2.0/lib/mono/4.5/FSharp.Core.dll"],"Logs":{"/Users/kdummann/source/rubecula/frontend/importer/importer.fsproj":"Microsoft.Build.Exceptions.InvalidProjectFileException: /Users/kdummann/source/rubecula/frontend/importer/importer.fsproj: Object reference not set to an instance of an object\n  at Microsoft.FSharp.Compiler.SourceCodeServices.ProjectCrackerTool.ProjectCrackerTool+FSharpProjectFileInfo..ctor (System.String fsprojFileName, Microsoft.FSharp.Core.FSharpOption`1[T] properties, Microsoft.FSharp.Core.FSharpOption`1[T] enableLogging) [0x00129] in <599ca64506d737baa745038345a69c59>:0 \n  at Microsoft.FSharp.Compiler.SourceCodeServices.ProjectCrackerTool.ProjectCrackerTool.getOptions@387 (System.Boolean enableLogging, Microsoft.FSharp.Collections.FSharpList`1[T] properties, System.String file) [0x0000f] in <599ca64506d737baa745038345a69c59>:0 \n  at Microsoft.FSharp.Compiler.SourceCodeServices.ProjectCrackerTool.ProjectCrackerTool.getOptions (System.String file, System.Boolean enableLogging, Microsoft.FSharp.Collections.FSharpList`1[T] properties) [0x00005] in <599ca64506d737baa745038345a69c59>:0 \n  at Microsoft.FSharp.Compiler.SourceCodeServices.ProjectCrackerTool.ProjectCrackerTool.crackOpen (System.String[] argv) [0x000cc] in <599ca64506d737baa745038345a69c59>:0 "},"OutputType":"exe","Info":{"SdkType":"verbose","Data":{}},"AdditionalInfo":{}}
```

The project works fine in Rider.

**Comment by Krzysztof-Cieslak** [comment] 2017-08-27 08:24
It looks like a problem with ProjectCracker, please create minimal reproduction and report issue in FCS repo - https://github.com/fsharp/FSharp.Compiler.Service

Also, personally I'd recommend moving to SDK based project file even if you're targeting full framework.

**Closed by Krzysztof-Cieslak** 2017-08-27 08:24 UTC
