### ISSUE TITLE
#r nuget references require a reload

### ISSUE THREAD

**Issue by isaacabraham** [ionide/ionide-vscode-fsharp#1852] opened 2023-03-14 23:12 UTC
### Describe the bug
Doing any `#r "nuget:<package>"` reference requires you to reload Ionide for the reference to kick in.

### Steps to reproduce
1. Create an empty script
2. `#r "nuget:FsToolkit.ErrorHandling"`
3. `open FsToolkit.ErrorHandling`

You should get intellisense etc., but the editor does not show anything.

4. Reload Ionide.
5. Everything works.

### Expected behaviour
I would expect Step 3 above to work immediately.

## Machine info
 - OS: Windows 11
 - .NET SDK version: 7.0.101
 - Ionide version: 7.5.1

**Comment by TheAngryByrd** [comment] 2023-03-14 23:33
Can you make sure to try with Adaptive Lsp Server on? <img width="572" alt="image" src="https://user-images.githubusercontent.com/1490044/225164892-4f89fc02-5deb-45fe-ba64-2237b9b6f719.png">

**Comment by TheAngryByrd** [comment] 2023-04-26 14:25
Closing since I can't reproduce with the adaptive LSP server enabled

**Closed by TheAngryByrd** 2023-04-26 14:25 UTC

**Comment by isaacabraham** [comment] 2023-05-09 11:14
Confirm this is fixed in latest Ionide which has Adaptive LSP on :-) Thank you.
