### ISSUE TITLE
Send to FSI on Mac adds random characters into F# interactive

### ISSUE THREAD

**Issue by evelinag** [ionide/ionide-vscode-fsharp#370] opened 2017-02-22 09:11 UTC
When sending any code to F# interactive through Alt+Enter, the code gets evaluated normally, but random characters are added into the terminal on a new line. 

For example, evaluating `let x = 1` outputs the following into the terminal:
```
> let x = 1
-
- ;;

val x : int = 1

> ^?^?212;3R^?^?^?^?^?^?
```
When I want to evaluate a next line, I have to either manually delete the `^?^?212;3R^?^?^?^?^?^?` or I get the following error:
```
/Users/evelina/test.fsx(8,1): error FS0010: Unexpected character '' in inter
action
```
If I change the FSI to the legacy FSI, everything works fine. I managed to replicate the same error on another Mac as well.

VS Code version: 1.9.1
Ionide version: 2.23.1

I'm not sure if this is a Ionide or VS Code bug.

Thank you.

**Comment by Krzysztof-Cieslak** [comment] 2017-02-22 09:15
Duplicate of https://github.com/ionide/ionide-vscode-fsharp/issues/352

Setting `"terminal.integrated.flowControl": false` fix it.

**Closed by Krzysztof-Cieslak** 2017-02-22 09:15 UTC

**Comment by evelinag** [comment] 2017-02-22 09:19
Thank you!
