### ISSUE TITLE
.NET core FS project : send projetct references to FSI failure

### ISSUE THREAD

**Issue by devcrafting** [ionide/ionide-vscode-fsharp#528] opened 2017-09-08 08:03 UTC
I got this project : https://github.com/lyontechhub/icalToGoogleCalendar
It is a F# dotnet core project.
I am using Ionide Fsharp 2.34.4.
When I try to send project references to FSI, it fails with:

```
Possible overload : 'X509Certificate2(fileName: string, password: string, keyStorageFlags: X509KeyStorageFlags) : unit'. Type constraint incompatibility. Type
System.Security.Cryptography.X509Certificates.X509KeyStorageFlags (System.Security.Cryptography.X509Certificates, Version=4.2.0.0, Cult
ure=neutral, PublicKeyToken=b03f5f7f11d50a3a)
is not compatible with type
System.Security.Cryptography.X509Certificates.X509KeyStorageFlags (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561
934e089)
```
(Nb: exception message translated from french)
I would say that FSI seems to struggle with dotnet core version of System.Security.Cryptography.X509Certificates and .net framework one...but not sure do really understand what's happening under the hood.

Thanks.

**Comment by Krzysztof-Cieslak** [comment] 2017-09-08 08:16
There's no .Net Core version of FSI and I doubt that passing .Net Core dlls to normal FSI is supported scenario.

Cc: @enricosada @dsyme

**Comment by devcrafting** [comment] 2017-09-08 08:27
To use the FSI, I created a FSX file with all references I needed, and I just referenced net45/net46 (some netstandard also) assemblies (it was a bit fastidious ;)).
I can't say which version is used by the F# project (using Fake) and which version is sent by the ionide plugin to FSI, but perhaps Ionide should try to send netXX version instead of netcore assemblies? Just a suggestion, but perhaps impossible...

**Comment by devcrafting** [comment] 2017-09-08 12:37
It works great with TargetFramework net461 in the fsproj.

Note, in the provided GitHub example, I got this error when I send to FSI the whole icalToGoogleCalendar.fs file and I run "main" function (don't forget to use netcoreapp2.0 to reproduce).

**Comment by enricosada** [comment] 2017-09-09 09:48
@devcrafting the only thing to do in this scenario is send reference to fsi only if target framework is .net framework (so .net full)

Is not possibile to evaluate the fsproj for a custom framework, because these are specified in `<TargetFramework` property

This can be done in ionide enabling/disabling the command, or showing an error message if not correct

now fsac return the target framework of the loaded fsproj, but this new api is not yet used in ionide.
i am upgrading it with #480 

an example of new api, the new info about project (in https://github.com/enricosada/ionide-vscode-fsharp/blob/57fbcf821c97ebaac64bbec0df4ce0db41b878a5/src/Core/DTO.fs#L152-L167 )

```
    type ProjectResponseInfo =
      | DotnetSdk of ProjectResponseInfoDotnetSdk
      | Verbose
      | ProjectJson
    and ProjectResponseInfoDotnetSdk = {
      IsTestProject: bool
      Configuration: string
      IsPackable: bool
      TargetFramework: string
      TargetFrameworkIdentifier: string
      TargetFrameworkVersion: string
      RestoreSuccess: bool
      TargetFrameworks: string list
      RunCmd: RunCmd option
      IsPublishable: bool option }
    and [<RequireQualifiedAccess>] RunCmd = { Command: string; Arguments: string }
```

this mean FSAC return data like:

```json
        "TargetFramework": "net461",
        "TargetFrameworkIdentifier": ".NETFramework",
        "TargetFrameworkVersion": "v4.6.1",
```

The fix will be to check if `TargetFrameworkIdentifier` is `.NETFramework`.

**Comment by Krzysztof-Cieslak** [comment] 2017-12-22 14:25
Duplicate of #671  - closing this one since the other issue has some additional information pointing out to places where changes should be done.

**Closed by Krzysztof-Cieslak** 2017-12-22 14:25 UTC
Labels: bug, up for grabs

**Comment by devcrafting** [comment] 2017-12-23 07:29
Note I tried it yesterday and it worked from a netcoreapp2.0, with ionide 3.15.1
