### ISSUE TITLE
.paket/paket.bootstrapper.exe is removed after some seconds of project create

### ISSUE THREAD

**Issue by kkpoon** [ionide/ionide-vscode-fsharp#498] opened 2017-08-16 12:51 UTC
## Environment
ionide-fsharp version 2.32.2
vscode 1.15.0 mac

## Problem
`.paket/paket.bootstrapper.exe` is being removed in project creation process

## Steps
```
mkdir hello-fsharp
cd hello-fsharp
code .
```

Cmd Shift P -> F# New Project
![image](https://user-images.githubusercontent.com/191992/29363857-19ad8222-82c4-11e7-910c-597158b7c63b.png)

Project Directory => [Empty] Current Directory
Project Name => HelloFsharp

Project Created
![screen shot 2017-08-16 at 20 29 06](https://user-images.githubusercontent.com/191992/29363922-52707132-82c4-11e7-9e52-997c5aaeb596.png)

After waiting some seconds without doing any action, more project files added
![screen shot 2017-08-16 at 20 29 20](https://user-images.githubusercontent.com/191992/29363940-68c8e2f2-82c4-11e7-9e22-eebb30496e7b.png)

More seconds afterward, `.paket/paket.bootstrapper.exe` is removed
![screen shot 2017-08-16 at 20 29 33](https://user-images.githubusercontent.com/191992/29363955-7e9ab772-82c4-11e7-8e85-61c53a4e9d29.png)

And then, some more files are created, e.g. build.sh, which execute `.paket/paket.bootstrapper.exe`
![screen shot 2017-08-16 at 20 30 54](https://user-images.githubusercontent.com/191992/29363964-8ad6c0a8-82c4-11e7-8385-d375f6f39f1d.png)

**Comment by Krzysztof-Cieslak** [comment] 2017-08-17 21:47
I believe this is reproduction of https://github.com/fsprojects/Paket/issues/2620

**Comment by Krzysztof-Cieslak** [comment] 2017-08-17 22:56
Closing here since it's upstream issue and it's tracked in appropriate repository

**Closed by Krzysztof-Cieslak** 2017-08-17 22:56 UTC
