### ISSUE TITLE
Intellisense and CodeLens have been gone after v3.29 update [LINUX/UBUNTU]

### ISSUE THREAD

**Issue by memoricab** [ionide/ionide-vscode-fsharp#949] opened 2018-10-20 23:58 UTC
After the update, firstly fsi.exe was missing so I configured it manually in settings.json. 
But  intellisense-underlining syntax errors-   and code lens not working. 

Auto-complete works fine though.

UPDATE DEBUG INFO:

> [16:21:02 INFO ] .Net runtime specified
> [16:21:02 INFO ] finding FSAC for
> 	runtime: NET
> 	mono: mono
> 	dotnet: null

OS Distro: 
> NAME="Ubuntu"
> VERSION="18.04.1 LTS (Bionic Beaver)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 18.04.1 LTS"
> VERSION_ID="18.04"
> VERSION_CODENAME=bionic
> UBUNTU_CODENAME=bionic

VSCode :
> Version: 1.28.2
> Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
> Date: 2018-10-17T00:20:56.183Z
> Electron: 2.0.9
> Chrome: 61.0.3163.100
> Node.js: 8.9.3
> V8: 6.1.534.41
> Architecture: x64
> 

Ionide Settings :
![settings](https://user-images.githubusercontent.com/7073672/47261649-855a9580-d4dc-11e8-8257-5995ec26468d.png)

**Comment by MangelMaxime** [comment] 2018-10-21 01:17
Hum synthax highligh should still works. Can you please try uninstall and re-install ionide extension ?

**Comment by memoricab** [comment] 2018-10-21 13:44
Not a solution but in order to use those features I set-up ionide extension v3.27.0. 

Now CodeLens and intellisense work fine.

**Comment by Paludan** [comment] 2018-10-25 11:48
I have the same issue.

**Comment by Rhywun** [comment] 2018-10-28 15:43
Same here - following appears in the log upon startup:

```
[11:38:57 ERROR] RES (008) <- {workspaceLoad} ERROR in 945 ms: {stack: Error: Request failed with status code 500
	at createError (/Users/me/.vscode/extensions/ionide.ionide-fsharp-3.29.0/fsharp.js:13103:15)
	at settle (/Users/me/.vscode/extensions/ionide.ionide-fsharp-3.29.0/fsharp.js:17033:12)
	at IncomingMessage.handleStreamEnd (/Users/me/.vscode/extensions/ionide.ionide-fsharp-3.29.0/fsharp.js:27857:11)
	at emitNone (events.js:111:20)
	at IncomingMessage.emit (events.js:208:7)
	at endReadableNT (_stream_readable.js:1056:12)
	at _combinedTickCallback (internal/process/next_tick.js:138:11)
	at process._tickCallback (internal/process/next_tick.js:180:9), message: Request failed with status code 500, config: [object Object], request: [object Object], response: [object Object]} Data=undefined
```

**Comment by lsmullenbrock** [comment] 2018-11-02 02:09
Has there been any progress on this?

**Comment by Bob-McCrory** [comment] 2018-11-02 18:18
This problem cuts across platforms: I have the same issue in Windows 10

**Comment by Paludan** [comment] 2018-11-02 20:13
> This problem cuts across platforms: I have the same issue in Windows 10

God damn I still had it working on my Arch machine, but now it stopped working there too >_>

**Comment by benfjohnson** [comment] 2018-11-03 19:30
Also seeing this same issue on Solus Linux

**Comment by da9l** [comment] 2018-11-10 21:55
Not working for me either in Windows 10.

I create a simple file: hello.fs
let hello = "hello"

I have 
Ionide-Fsharp: 3.29.0
VSCode:1.28.2
VS Community 2017:15.8.9
VS Build tools 2017:15.8.9
Dotnet Core CLI:2.1.403

I tried to downgrade ionide to 3.27.0 and 3.25.4 but it didn't help.

```
console.ts:136 [Extension Host] [IONIDE-FSAC] Cannot execute recordStubGenerator, File 'c:\Users\danie\projects\SuaveRestApi\hello.fs' not parsed 
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:438
(anonymous) @ extensionHost.ts:246
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
console.ts:136 [Extension Host] [IONIDE-FSAC] Cannot execute signature, File 'c:\Users\danie\projects\SuaveRestApi\hello.fs' not parsed 
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:438
(anonymous) @ extensionHost.ts:246
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
console.ts:136 [Extension Host] [IONIDE-FSAC] Cannot execute tooltip, File 'c:\Users\danie\projects\SuaveRestApi\hello.fs' not parsed 
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:438
(anonymous) @ extensionHost.ts:246
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
console.ts:136 [Extension Host] [IONIDE-FSAC] Cannot execute symboluse, File 'c:\Users\danie\projects\SuaveRestApi\hello.fs' not parsed 
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:438
(anonymous) @ extensionHost.ts:246
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
console.ts:136 [Extension Host] [IONIDE-FSAC] Cannot execute signature, File 'c:\Users\danie\projects\SuaveRestApi\hello.fs' not parsed 
t.log @ console.ts:136
t._logExtensionHostMessage @ extensionHost.ts:438
(anonymous) @ extensionHost.ts:246
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
console.ts:136 [Extension Host] [IONIDE-FSAC] Cannot execute recordStubGenerator, File 'c:\Users\danie\projects\SuaveRestApi\hello.fs' not parsed 
```

**Comment by marco-m** [comment] 2018-11-25 11:51
Same for me (no codelens, no intellisense) on 
- macOS 10.14.1
- vscode 1.29.1
- ionide 3.30.0
- mono 5.16

**Comment by Paludan** [comment] 2018-11-26 20:04
> Same for me (no codelens, no intellisense) on
> 
> * macOS 10.14.1
> * vscode 1.29.1
> * ionide 3.30.0
> * mono 5.16

I have been able to get it working on my MacBook using macOS Monjave. I use the following settings
`{
    "FSharp.fsiFilePath": "/Library/Frameworks/Mono.framework/Versions/Current/Commands/fsharpi",
    "FSharp.monoPath": "/Library/Frameworks/Mono.framework/Versions/Current/Commands/mono",
    "FSharp.msbuildLocation": "/Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild",
    "FSharp.fsacRuntime": "netcore"
}`

**Comment by marco-m** [comment] 2018-11-26 20:36
@Paludan that was it! thanks! To summarize for other pool souls googling, this is valid only for macOS:
1. install mono
2. install dot net core (yes, both!)
3. use the settings proposed by @paludan above. Dot net core is used by `"FSharp.fsacRuntime": "netcore"`.
If I don't install dot net core and so use `"FSharp.fsacRuntime": "net"`, I don't get codelens nor intellisense.

**Comment by Paludan** [comment] 2018-11-26 20:41
> @Paludan that was it! thanks! To summarize for other pool souls googling, this is valid only for macOS:
> 
> 1. install mono
> 2. install dot net core (yes, both!)
> 3. use the settings proposed by @Paludan above. Dot net core is used by `"FSharp.fsacRuntime": "netcore"`.
>    If I don't install dot net core and so use `"FSharp.fsacRuntime": "net"`, I don't get codelens nor intellisense.

Yeah I looked at the console output, and saw the dotnet: null message. This prompted me so think "Uh well I don't have it installed", and so I installed it and set the FSAC runtime to use netcore. Voila!

**Comment by Rhywun** [comment] 2018-11-26 20:55
I can confirm that adding the suggested lines to the settings file results in Intellisense working again on macOS. Thanks, @Paludan

**Comment by memoricab** [comment] 2018-11-26 23:08
I followed above instructions. Everything[Ionide and Fsi] works fine now. Thank you.

Steps that I followed [OS: Ubuntu 18.04 bionic; Ionide Version: 3.30 ]

1. Download .NET core from [here](https://www.microsoft.com/net/download/linux-package-manager/ubuntu18-04/sdk-current)
2. Configured settings.json as below.
`{ "FSharp.fsiFilePath": "/usr/lib/mono/fsharp/fsi.exe",
     "FSharp.monoPath": "/usr/bin/mono", 
     "FSharp.msbuildLocation": "/usr/lib/mono/msbuild", 
     "FSharp.fsacRuntime": "netcore" }`

I hope you guys get working ionide as well. :)

**Comment by Paludan** [comment] 2018-11-27 07:04
Looks like my solution works for Linux as well then! I suppose this can be marked as solved.

**Comment by Krzysztof-Cieslak** [comment] 2018-11-27 09:42
TBF, I'm not super happy about that, and I'm not really sure why some of those are required... but well, I'm glad that you've found solutions. Sorry for all the troubles.

**Closed by Krzysztof-Cieslak** 2018-11-27 09:42 UTC
Labels: reproduction needed, workaround

**Comment by lsmullenbrock** [comment] 2018-12-07 03:15
Still having trouble on Windows. F# Language Service outputs a lot of "[22:13:54 ERROR] Cannot execute tooltip, File 'c:\Users\file.fs' not parsed" when scrolling over functions, etc.
