### ISSUE TITLE
Ctrl+Space shows documentation tooltip for wrong function

### ISSUE THREAD

**Issue by hickford** [ionide/ionide-vscode-fsharp#806] opened 2018-05-12 13:30 UTC
Hi. Can anyone else reproduce this bug? With the code below, try pressing Ctrl+Space after `Seq.map`. You will see a tooltip with documentation for the Seq.map function. Then, try pressing Ctrl+Space after `List.map`. Expected: You will see a tooltip with documentation for List.map. What actually happens: You see a tooltip with documentation for Seq.map , ie. the wrong function!

    let x = Seq.map
    let y = List.map

If you just hover on the functions, you see the right documentation

![image](https://user-images.githubusercontent.com/105314/39957784-5868558c-55f0-11e8-99b1-1e95b9d924ce.png)

**Comment by inosik** [comment] 2018-05-14 07:48
What's even stranger, this happens with the `Option` module as well:

![Seq.map instead of Option.map](https://user-images.githubusercontent.com/11393003/39984569-f10e79b2-575b-11e8-8ffb-7fa742d4c44a.png)

**Comment by inosik** [comment] 2018-05-14 08:02
To reproduce this:

1. Add these modules:
    ``` fsharp
    module M =
      let f = ()

    module M2 =
      let f x y = ()
    ```

1. Access `M.f` in the editor

1. Access `M2.f` in the editor

    _Tooltip for `M.f` is shown, instead of `M2.f`._

Note that only <kbd>Ctrl</kbd>+<kbd>Space</kbd> is affected, hovering over a member shows the correct tooltip.

**Comment by inosik** [comment] 2018-05-14 08:46
The request on <kbd>Ctrl</kbd>+<kbd>Space</kbd> for `Seq.collect` looks like this:

``` text
[10:22:19 DEBUG] REQ (15132) -> {helptext}, Symbol = "collect"
Data={"Symbol":"collect"}
[10:22:19 DEBUG] RES (15132) <- {helptext} in 4 ms: Kind={"helptext"}
Data={"Name":"collect","Overloads":[[{"Signature":"val collect : mapping:(char -> string) -> str:string -> string","Comment":""}]],"AdditionalEdit":null}
``` 

1. `Symbol = "collect"` is not enough information to get the correct function
2. FSAC caches the result and the cache isn't invalidated again

    _Whichever `collect` gets cached first, is returned for every other `collect`._

**Comment by Krzysztof-Cieslak** [comment] 2018-05-14 14:51
It's something wrong with FSAC tooltips caching, I belive

**Comment by Krzysztof-Cieslak** [comment] 2018-05-25 15:37
Fixed in `3.20.7`

**Closed by Krzysztof-Cieslak** 2018-05-25 15:37 UTC
Labels: bug, language services

**Comment by hickford** [comment] 2018-05-25 20:59
Brilliant, thanks very much!
