### ISSUE TITLE
Request for simple Refactoring tools

### ISSUE THREAD

**Issue by muhammadHuzaifaSalman** [ionide/ionide-vscode-fsharp#1277] opened 2019-12-24 23:19 UTC
I wanted a simple feature like extracting a piece of code into a method / module to be implemented in the VSCode ionide extension. Something similar to what is shown here: https://code.visualstudio.com/docs/editor/refactoring.

**Comment by Krzysztof-Cieslak** [comment] 2019-12-28 10:42
Duplicate of #172

**Closed by Krzysztof-Cieslak** 2019-12-28 10:42 UTC
