### ISSUE TITLE
AutoComplete popping up in comments

### ISSUE THREAD

**Issue by ovatsus** [ionide/ionide-vscode-fsharp#571] opened 2017-10-05 14:03 UTC
I'm on Ionide-fsharp 3.3.4 and VSCode 1.16.1

Was writing a small help section in comments on a fsx file to explain how to setup to users new to F#, and I autocomplete popped up:

![image](https://user-images.githubusercontent.com/738761/31231286-52118af0-a9de-11e7-8b2c-1ac8c9c7c093.png)

**Comment by enricosada** [comment] 2017-10-05 14:55
Closing, dupe of https://github.com/ionide/ionide-vscode-fsharp/issues/74

**Closed by enricosada** 2017-10-05 14:55 UTC
