### ISSUE TITLE
Ionide 4.0 doesn't run on system install

### ISSUE THREAD

**Issue by matthid** [ionide/ionide-vscode-fsharp#1138] opened 2019-06-16 17:49 UTC
```
System.UnauthorizedAccessException: Access to the path 'C:\Program Files\Microsoft VS Code\.ionide' is denied.
 at System.IO.FileSystem.CreateDirectory(String fullPath)
 at System.IO.Directory.CreateDirectory(String path)
 at SymbolCache.PersistenCacheImpl.initializeCache(String dir) in C:\proj\ionide-vscode-fsharp\paket-files\github.com\fsharp\FsAutoComplete\src\FsAutoComplete.Core\SymbolCache.fs:line 77
 at FsAutoComplete.Commands.StartBackgroundService(String workspaceDir) in C:\proj\ionide-vscode-fsharp\paket-files\github.com\fsharp\FsAutoComplete\src\FsAutoComplete.Core\Commands.fs:line 1097
 at FsAutoComplete.Lsp.Initialize@255.Invoke(Unit unitVar) in C:\proj\ionide-vscode-fsharp\paket-files\github.com\fsharp\FsAutoComplete\src\FsAutoComplete\FsAutoComplete.Lsp.fs:line 258
 at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2)
 at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFun...
```

![image](https://user-images.githubusercontent.com/1866463/59566512-922a8b80-9061-11e9-8dc2-32b02154ea13.png)

I guess the reason is that I'm using a "system" install of code:

![image](https://user-images.githubusercontent.com/1866463/59566526-d158dc80-9061-11e9-984e-e06f02cca963.png)

**Comment by Krzysztof-Cieslak** [comment] 2019-06-17 15:58
I'm not sure if this has anything to do with system install - we shouldn't use installation path of VSCode anyway. 

I'll investigate.

**Comment by Krzysztof-Cieslak** [comment] 2019-06-18 10:07
It's caused by opening F# file (i.e activating plugin) without opening folder

![image](https://user-images.githubusercontent.com/5427083/59673458-a71e3080-91c1-11e9-9404-5c90cab325bc.png)

**Comment by matthid** [comment] 2019-06-18 10:18
Nice find, I consider this scenario completely valid for FAKE scripting. For scenarios where you use Rider or VS and Ionide just for the build script ;)
Or the scenario where you just want to edit a single automation script (no folder or project or anything)

**Comment by Krzysztof-Cieslak** [comment] 2019-06-18 10:37
Fixed by https://github.com/fsharp/FsAutoComplete/commit/8366988d5a1798fdf4a6e78653c2e4364f4e40b5

**Comment by Krzysztof-Cieslak** [comment] 2019-06-18 10:38
Tho, I still believe the suggested way of using Ionide should be opening the folder - even if you just want to edit single script file

**Closed by Krzysztof-Cieslak** 2019-06-18 10:37 UTC
Labels: bug

**Comment by matthid** [comment] 2019-06-18 10:39
Ok but I guess we can agree on that it should still work, and PRs improving that would be accepted?

**Comment by Krzysztof-Cieslak** [comment] 2019-06-18 10:47
Oh, it works with the fix I've done in FSAC - it only won't start background service.... which is not a huge problem in case of single file (there are no other files processed in the background anyway)

**Comment by matthid** [comment] 2019-06-18 10:50
Note that a single file can be a "project" in the case of `fsx`: it can `#load` other files. Not sure if that is relevant (as I don't yet understand everything)
