### ISSUE TITLE
Array bracket autocomplete adds an additional close-square-bracket 

### ISSUE THREAD

**Issue by misterspeedy** [ionide/ionide-vscode-fsharp#1384] opened 2020-06-15 09:43 UTC
**Describe the bug**
Bracket autocomplete adds an additional close-square-bracket when using array brackets `[||]`.

**To Reproduce**
1. Start to bind an array, e.g.

`let myArray = `

2. Type 

`[|`

3. Observe that autocompletion has changed the code to

`let myArray = [||]]`

(Note additional `]`)

**Expected behaviour**

Completed code should read

`let myArray = [||]`

**Environment:**
 - OS: Windows_NT x64 10.0.18362
 - Ionide version: 4.12.1
 - VSCode version:

Version: 1.45.1 (system setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0

 - dotnet SDK version:
.NET Core SDK (reflecting any global.json):
 Version:   3.1.200
 Commit:    c5123d973b

 - mono / .Net Framework version:
3.1.2

**Additional context**

I'm assuming this is an Ionide issue rather than a VS Code issue, but forgive me if not!

**Comment by Krzysztof-Cieslak** [comment] 2020-06-15 10:59
Duplicate of #1091

**Closed by Krzysztof-Cieslak** 2020-06-15 10:59 UTC
