### ISSUE TITLE
On FAKE Solution F# Language Service crashes

### ISSUE THREAD

**Issue by matthid** [ionide/ionide-vscode-fsharp#608] opened 2017-10-22 09:21 UTC
Sorry, pressed "Enter" too fast.

When opening Fake-netcore.sln in FAKE I eventually get:
```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Could not find file 'c:\proj\FAKE\src\app\Fake.Core.Target\String.fs'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding)
   at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
   at <StartupCode$FsAutoComplete-Core>.$Commands.clo@31-19.Invoke(String file)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at Microsoft.FSharp.Collections.ArrayModule.Parallel.Iterate[T](FSharpFunc`2 action, T[] array)
   at <StartupCode$FsAutoComplete-Core>.$Commands.clo@29-18.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@851.Invoke(AsyncParams`1 args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.FSharp.Control.CancellationTokenOps.Start@1268-1.Invoke(ExceptionDispatchInfo edi)
   at <StartupCode$FSharp-Core>.$Control.loop@430-52(Trampoline this, FSharpFunc`2 action)
   at Microsoft.FSharp.Control.Trampoline.ExecuteAction(FSharpFunc`2 firstAction)
   at <StartupCode$FSharp-Core>.$Control.-ctor@516-1.Invoke(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

Now that the server is gone all requests yield:

```
[11:20:46 ERROR] RES (025) <- {tooltip} ERROR in 1002 ms: {stack: Error: connect ECONNREFUSED 127.0.0.1:8249
	at Object.exports._errnoException (util.js:1050:11)
	at exports._exceptionWithHostPort (util.js:1073:20)
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14), message: connect ECONNREFUSED 127.0.0.1:8249, code: ECONNREFUSED, errno: ECONNREFUSED, syscall: connect, address: 127.0.0.1, port: 8249, config: [object Object], request: [object Object], response: undefined} Data=undefined
```

**Comment by matthid** [comment] 2017-10-22 09:28
What's interesting is that the language server seems to confuse projects, becase:

Yes the given path doesn't exist, but the correct path is 
 - `c:\proj\FAKE\src\app\Fake.Core.Target\String.fs` <- wrong
 - `c:\proj\FAKE\src\app\Fake.Core.String\String.fs` <- correct

Note that `Fake.Core.Target` references `Fake.Core.String`

**Comment by enricosada** [comment] 2017-10-22 11:09
yes, missing files crash fsac atm ( ref https://github.com/fsharp/FsAutoComplete/issues/235 )

Closing as dupe of https://github.com/ionide/ionide-vscode-fsharp/issues/606

**Comment by matthid** [comment] 2017-10-22 11:10
@enricosada There is no file missing as far as I can tell?

**Comment by enricosada** [comment] 2017-10-22 11:12
I'll check, sry @matthid i assumed `Yes the given path doesn't exist` as error

**Comment by matthid** [comment] 2017-10-22 11:12
It is calculating the wrong path for some reason I don't know why.

**Comment by matthid** [comment] 2017-10-22 11:14
In theory it could be a duplicate, it definitely leads to the same effect. We just need to ask ourself if it is OK that it tries to access this particular path in this particular situation (maybe it is for some design/technical reason).

**Comment by Krzysztof-Cieslak** [comment] 2017-10-22 22:45
Fix to the crash is released in `3.8.2`

To the "why it gives the wrong path", I have no idea... maybe try clearing cache

**Comment by matthid** [comment] 2017-10-22 22:52
The file was never in the other path AFAIK. So even if it is a caching issue it never should have been written to the cache like this.

**Comment by Krzysztof-Cieslak** [comment] 2017-12-22 14:09
The FAKE solution seems works OK for me on latest Ionide. It's bit slow due to the number of projects but that's why we've added `FSharp.minimizeBackgroundParsing`.

**Closed by Krzysztof-Cieslak** 2017-12-22 14:09 UTC
Labels: bug, dotnet/sdk, language services (FSAC / FCS / Project Cracker)
