### ISSUE TITLE
Dot-notation breaks highlightning

### ISSUE THREAD

**Issue by jl0pd** [ionide/ionide-vscode-fsharp#1430] opened 2020-10-19 16:45 UTC
**Describe the bug**
If you place dot inside of line all further highlighting to the end of line will break and text become white

**To Reproduce**
Steps to reproduce the behaviour:
1. Download repo: https://github.com/jl0pd/IonideHighlightBug
1. Open in VSCode

There is 2 parts in every example. First is right colorization, but splitted into different lines and second as one-liner with white text

**Expected behaviour**
Colorization should not break. Both examples should be colored same way
```fsharp
Seq.map id [1 .. 0]
Seq.map 
    id 
    [1 .. 0]
```

**Screenshots**
![image](https://user-images.githubusercontent.com/36221916/96477108-4a70d100-1260-11eb-9a6e-34a6406c0322.png)

Also there is case when you can **completely** break colorization
![image](https://user-images.githubusercontent.com/36221916/96480751-d8e75180-1264-11eb-9d35-97ce9be91af8.png)

**Environment (please complete the following information):**
 - OS: Windows 10 1909
 - Ionide version: 4.17.0
 - VSCode version: 1.50.1
 - dotnet SDK version: 3.1.403
 - mono / .Net Framework version: .Net Framework 4.8
On Linux Mint 20 in VirtualBox with same Ionide/VSCode versions everything is ok

**Comment by Krzysztof-Cieslak** [comment] 2020-12-14 16:23
It seems to be working fine for me:
![image](https://user-images.githubusercontent.com/5427083/102106545-00a40180-3e31-11eb-9229-cb0e490c1a5c.png)

**Comment by Krzysztof-Cieslak** [comment] 2020-12-14 16:47
> Also there is case when you can completely break colorization

This is duplicate of #1424

**Comment by sunahe** [comment] 2020-12-14 19:29
Too bad this is closed. It's still an issue. Having a dot breaks colorization, unless the invocation is parenthesized:
![image](https://user-images.githubusercontent.com/11211938/102125568-2db0de00-3e4a-11eb-9c24-a554d42f7a29.png)

Interestingly, the issue does not reproduce in "Dark (Visual Studio)" theme that has no semantic colorization:
![image](https://user-images.githubusercontent.com/11211938/102126088-ea0aa400-3e4a-11eb-99e3-842154b1d3f8.png)

**Comment by Krzysztof-Cieslak** [comment] 2022-07-18 22:31
I can't reproduce it on latest Ionide:
<img width="424" alt="image" src="https://user-images.githubusercontent.com/5427083/179628271-7dce91f8-f588-4eae-b90f-c49aea17f345.png">

**Closed by Krzysztof-Cieslak** 2022-07-18 22:31 UTC
Labels: bug
