### ISSUE TITLE
.NET Core projects should not require mono installed

### ISSUE THREAD

**Issue by enricosada** [ionide/ionide-vscode-fsharp#277] opened 2016-11-15 16:11 UTC
Scenario:

- .net core sdk preview3 installed
- an fsproj (msbuild15 based) with only `netstandard` or `netcoreapp` target framework
- => mono is not required
- => `dotnet` is used instead to run the ionide backend

That enable to have a basic f# experience  with a minimal install (netcoresdk + vscode), both are not machine wide.
Basic f# experience because no type providers until netstandard2.0 but this work will make it possibile to use it in future just upgrading target framework.

## TODO

- This require all ionide backend dependencies to be .net core lib or console app.
- Development deps of ionide can be the same.
- The msbuild (`dotnet msbuild`), fsc and usual visualfsharp are already inside sdk, so that's ok
- It's easy to check if dotnet is installed (`dotnet --version`) and fsproj version (it's msbuild 15).
- It's possibile the sdk extensibility (sdk tools)

/cc @Krzysztof-Cieslak for feedback, and @7sharp9 because already tried to do that

**Comment by kontomondo** [comment] 2016-11-26 18:21
@Krzysztof-Cieslak I can take on this if you guide me roughly through what would need to be done. Apart from what @enricosada  listed, a few steps listed below, I expect there to be a lot more to change though? 
1) Create a new Process.isPosix () function, change some instances where paths are involved from Process.isMono () to Process.isPosix ()
2) Add a new configuration property "FSharp.dotnetExecutablePath" or something to that effect, or should we just look for one in $PATH ?
3) In LanguageService.fs use that if defined to spawn/start the program
4) "This requires all ionide backend dependencies to be either a .net core lib or console apps." - I presume that this would be the hardest part? What would it involve?

**Comment by enricosada** [comment] 2016-11-26 22:03
Amazing @kontomondo , ping me too if you need something netcore related (on #dotnetcore channel on fsharp.org slack too).

I dont think it's much more, the backend is the FSAC api server, if that's netcore then is ok i think, the rest is javascript so no changes.  
As i said, that's just for users, development of ionide will continue to required mono/.net

> 2. Add a new configuration property "FSharp.dotnetExecutablePath" or something to that effect, or should we just look for one in $PATH ?

The one in `PATH` is ok, and better atm (it's prefererred way to have it in `PATH`)

>4.  "This requires all ionide backend dependencies to be either a .net core lib or console apps." - I presume that this would be the hardest part? What would it involve?

Primary target is `FsAutoComplete` (`.Suave` too) as `netcoreapp1.0` app, others like forge can be done separately.
The FCS and Suave are already ok i think, so all deps of FSAC are ok afaik
If you need something for migration to netcore, pls ping me

**Comment by 7sharp9** [comment] 2016-11-26 22:16
There's a branch of fsauto that used to work but it required manually
building fcs

**Comment by Krzysztof-Cieslak** [comment] 2017-08-27 20:56
Duplicate of #78

**Closed by Krzysztof-Cieslak** 2017-08-27 20:56 UTC
Labels: backburner - requires additional upstream functionality, feature request, up for grabs
