### ISSUE TITLE
Ionide fails to load mixed c#/f# project.

### ISSUE THREAD

**Issue by da9l** [ionide/ionide-vscode-fsharp#1299] opened 2020-02-05 16:56 UTC
**Describe the bug**
When loading mixed project Ionide fails.
see sample project:https://github.com/da9l/minimalFailingMixedSln4Ionide

**To Reproduce**
Steps to reproduce the behaviour:
1. clone project above
2. `code .`
3. wait

**Expected behaviour**
It should work

**Environment (please complete the following information):**
 - OS: 
 - Ionide version: 4.5.0
 - VSCode version: 1.41.1
 - dotnet SDK version: 3.1.100
 - mono / .Net Framework version:

P.S.
I'm a backer via open collective
D.S.

**Comment by Krzysztof-Cieslak** [comment] 2020-02-05 17:44
Duplicate of #1187

**Closed by Krzysztof-Cieslak** 2020-02-05 17:44 UTC
