### ISSUE TITLE
onDidChangeTextDocument handler has incorrect parameter type

### ISSUE THREAD

**Issue by fsoikin** [ionide/ionide-vscode-fsharp#468] opened 2017-07-14 20:20 UTC
When [`Linter.activate` attaches a handler to `workspace.onDidChangeTextDocument`](https://github.com/ionide/ionide-vscode-fsharp/blob/master/src/Components/Linter.fs#L84), the handler function [`handler`](https://github.com/ionide/ionide-vscode-fsharp/blob/master/src/Components/Linter.fs#L45) has the parameter of type `string`, whereas the event itself pushes data of type `TextDocumentChangeEvent`. 

This causes an exception later on, `handler` -> `lintDocument` -> `LinterService.lint` -> `logOutgoingRequest` -> `relativePathForDisplay` -> `String.replace` due to the argument not being a string.

I am not 100% how this manifests to the user, but I would _guess_ that it probably causes the linter to update slower, or even stop completely.

**Comment by Krzysztof-Cieslak** [comment] 2017-07-14 21:02
Actually the problem is bit different - `workspace.onDidChangeTextDocument` is not needed at all. It was used in the past, but nowadays the Linter is triggered by successful parsing of the file (this way we always have up-to-date lints) and is controlled with `refresh` event. 

Thanks for pointing it out, fixed by bb8bcb9c0bac42a6900a1767f5b52c92f5705943

**Closed by Krzysztof-Cieslak** 2017-07-14 21:02 UTC

**Comment by fsoikin** [comment] 2017-07-14 21:08
Is there any reason for the untyped `$` operator (other than lack of time to properly type everything)?

**Comment by Krzysztof-Cieslak** [comment] 2017-07-14 21:12
I guess it's lack of time and not complete typings back when this part of the Ionide was created. I think that with current typings calling `.Invoke` on events gives typed way to add event handler

**Comment by fsoikin** [comment] 2017-07-14 21:14
Would it be cool if I send PRs with correct typings as I come across these places?

**Comment by Krzysztof-Cieslak** [comment] 2017-07-14 21:32
Sure, go ahead. The code is bit hacky in few places due to some historical reasons ( super early adaption of Fable + coping some code from old FunScript version) so any improvements are welcomed :)
