### ISSUE TITLE
Intellisense: the value, namespace, type or module 'fsi' is not defined

### ISSUE THREAD

**Issue by simra** [ionide/ionide-vscode-fsharp#590] opened 2017-10-09 16:29 UTC
This is mainly a cosmetic issue: for some reason Intellisense can't find the fsi module, so references to things like fsi.CommandLineArgs get red squiggles.
I have fsi in my path, and I can open a fsi terminal in vscode.
F# is installed via VS 2017.
```
c:\>where fsi
C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0\fsi.exe

```

**Comment by Krzysztof-Cieslak** [comment] 2017-10-09 16:48
TIL about `FSI` module... I have no idea how to fix it. Maybe @dsyme?

**Comment by enricosada** [comment] 2017-10-09 17:18
seems a regression in FSAC, see this bug https://github.com/fsharp/FsAutoComplete/issues/227 with same issue but on mono.

@simra what version of VS 2017 do you have installed?

**Comment by enricosada** [comment] 2017-10-10 14:37
Seems FSAC resolve the `FSharp.Compiler.Interactive.Service` from GAC.
But VS2017 doesnt put it anymore in GAC?

In my machine on windows:

```
    "-r:C:\Windows\Microsoft.NET\assembly\GAC_MSIL\FSharp.Compiler.Interactive.Settings\v4.0_4.4.0.0__b03f5f7f11d50a3a\FSharp.Compiler.Interactive.Settings.dll"|];
```

@simra you have only VS2017 installed? what version? can you check if GAC contains `FSharp.Compiler.Interactive.Settings` assembly?

**Comment by dsyme** [comment] 2017-10-10 20:29
@enricosada If it's just for type checking/editing purposes then it may make sense to ship a copy of this alongside FsAutoComplete.exe, or in a known location as part of the install.

**Comment by simra** [comment] 2017-10-10 21:02
@enricosada: correct, I have only VS2017, and in fact this problem started when I rebuilt the machine a few weeks ago and installed VS 2017 but not 2015.  There are no FSharp.* folders or dlls of any kind in C:\Windows\Microsoft.NET\assembly\GAC_MSIL.
Don's suggestion is probably good, or picking up the DLL from the same folder as fsi.exe. I see FSharp.Compiler.Interactive.Settings.dll in C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0.

**Comment by simra** [comment] 2017-10-10 21:04
@enricosada I forgot to answer your question: VS 2017 v15.3.5.

**Comment by enricosada** [comment] 2017-10-11 16:18
@simra thanks a lot for the info, was useful to confirm the bug.
thx @dsyme !

Is same bug as https://github.com/fsharp/FsAutoComplete/issues/227 , so closing this because is tracked there.

**Closed by enricosada** 2017-10-11 16:18 UTC
Labels: bug, language services (FSAC / FCS / Project Cracker)
