### ISSUE TITLE
Queue Class not recognisable

### ISSUE THREAD

**Issue by yjzhu1** [ionide/ionide-vscode-fsharp#377] opened 2017-02-26 22:54 UTC
So I am working on an assignment in F# for a class, and I came across this issue. When I tried running the program through the interpreter and through a .fsx file before I upgraded to 2.23.5, this message would pop up, but running it through `fsharpi` in the terminal worked...

![screen shot 2017-02-26 at 17 48 20](https://cloud.githubusercontent.com/assets/12618851/23344519/f2d21090-fc4b-11e6-91f5-9dd0be820044.png)

After upgrading to 2.23.5, the error message saying that Queue was undefined disappeared and the program ran, but the Queue class had this red line underneath with the following message...

![screen shot 2017-02-28 at 19 34 33](https://cloud.githubusercontent.com/assets/12618851/23440883/fd42b410-fdec-11e6-882d-985fae5402f0.png)

**Comment by lilred** [comment] 2017-02-28 02:34
I'm going to try to take a crack at this once #380 is resolved.

**Comment by alexboii** [comment] 2017-02-28 02:35
Can confirm the reproduction of this error on Fedora 25, ionide 2.35.5, vsc version 1.9.1 

![here](https://i.imgur.com/7FjnOfJ.png)

**Comment by Krzysztof-Cieslak** [comment] 2017-03-01 15:21
`.fs` files should have `.fsproj` file to which they belong. For standalone files use `.fsx` files.

**Comment by lilred** [comment] 2017-03-01 17:46
This works in both Community and on the command-line. Are we sure that this is intended behavior?

Maybe leave it open but mark it as up for grabs?

**Comment by Krzysztof-Cieslak** [comment] 2017-03-01 17:51
If anything, this is probably "issue" (i'm not even sure if it's issue) in FsharpCompilerService.

**Comment by lilred** [comment] 2017-03-01 17:53
I'm going to work on this today, will report back iff I make any progress.

**Comment by yjzhu1** [comment] 2017-03-31 13:35
Does version 2.25.4+ resolve this?

**Comment by Krzysztof-Cieslak** [comment] 2017-03-31 14:17
No idea, the workaround I've proposed is still valid. Renaming file to `.fsx` should be enough.

**Comment by Krzysztof-Cieslak** [comment] 2017-03-31 15:55
Should be fixed in `2.25.7`

**Closed by Krzysztof-Cieslak** 2017-03-31 15:55 UTC
Labels: language services (FSAC / FCS / Project Cracker), up for grabs
