### ISSUE TITLE
Rename file not working at all

### ISSUE THREAD

**Issue by MikaelUmaN** [ionide/ionide-vscode-fsharp#1181] opened 2019-07-15 11:05 UTC
Issue Type: <b>Bug</b>

- dotnet new classlib
- In Vs Code,  Open Folder
- Select Library.fs and attempt Rename

Expected: File is renamed

Actual: Seemingly nothing happens.

If you then rename manually and change project files intellisense just stops working at all.

dotnet sdk: 2.2.301
Latest vs code, latest ionide extension

Here is the output from Forge which seems to be the culprit:
"C:\Users\mikae\.vscode\extensions\ionide.ionide-fsharp-4.0.6\bin_forge\Forge.dll rename file -n c:\Users\mikae\dev\FsCsv\src\FsCsv\Library.fs -r c:\Users\mikae\dev\FsCsv\src\FsCsv\Write.fs -p c:\Users\mikae\dev\FsCsv\src\FsCsv\FsCsv.fsproj --no-prompt
Cannot Rename File - invalid name"

But Write.fs should not be invalid.

Extension version: 4.0.6
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (9.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Krzysztof-Cieslak** [comment] 2019-07-15 12:00
Duplicate of #1173

**Closed by Krzysztof-Cieslak** 2019-07-15 12:00 UTC
