### ISSUE TITLE
Couldn't reference to MathNet.Numerics in F# interactive

### ISSUE THREAD

**Issue by chanjunweimy** [ionide/ionide-vscode-fsharp#539] opened 2017-09-15 07:22 UTC
![image](https://user-images.githubusercontent.com/7464833/30470996-95a82432-9a29-11e7-850e-a7fa051945b9.png)

As shown in the screenshot, even if I have referenced System.Numerics and I have send all the references from the project, I still couldn't reference it :(

May I know how I could fix this issue? Thanks.

Target Framework: .net461

**Comment by enricosada** [comment] 2017-09-15 16:59
@chanjunweimy could you try to reference each assembly in order?
first system.numerics, after `matnet.numerics`
and after that, evaluate the code?

Better also if you can upload the fsproj (source files doesnt matter), and add the exact steps you do, so is  possibile to repro it.

**Comment by chanjunweimy** [comment] 2017-09-18 03:14
Dear @enricosada , 

Thanks to your prompt reply, I have tried your suggestion, which is referencing each assembly in order, but unfortunately it still couldn't work.

The fsproj file:
```` xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net461</TargetFramework>
    <Platforms>AnyCPU;x64;x86</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include=... />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MathNet.Numerics" Version="3.20.0" />
    <PackageReference Include="MathNet.Numerics.FSharp" Version="3.20.0" />
  </ItemGroup>
</Project>
````

Exact Steps:
1. Open a fs file which uses "Matrix" reference from MathNet.Numerics
2. Run FSI Start
3. Send References from project
4. open MathNet.Numerics.LinearAlgebra;
5. Run a function that uses "Matrix"

Expected: Showing something related to the Matrix
Actual: Failed as it requires reference from MathNet.Numerics

Regards,
Jun Wei

**Comment by chanjunweimy** [comment] 2017-09-18 03:40
Dear @enricosada , 

I have created a project which can reproduce the issue at https://github.com/chanjunweimy/fsi-issue

Thanks for your help.

Regards,
Jun Wei

**Comment by enricosada** [comment] 2017-09-18 10:16
thx a lot @chanjunweimy  for amazing repro, i'll check

**Comment by enricosada** [comment] 2017-09-18 13:51
Ok i can repro, thx a lot @chanjunweimy for detailed repro, awesome!

The issue is with reference order. for fsi, the `MathNet.Numerics.dll` should be sent before `MathNet.Numerics.FSharp.dll`. 

the order generated by ionide command is the same of the one used by compiler, but fsi is more strict.

I can repro doing the same step in `fsi` directly, without ionide, this is anyway an issue with loading for `#r` of fsi (sending both `#r` at once has same issue), so adding that as upstream bug for now.
TODO open a bug in https://github.com/Microsoft/visualfsharp/issues about it.

@chanjunweimy  as workaround:

- do command `FSI: Generate script file with references from project`, this will generate a file. in a new editor, will all reference of project as `#r` instructions
- send as selection to fsi the `#r   ... MathNet.Numerics.dll`
- after that send as selection the `#r ..  MathNet.Numerics.FSharp.dll`
- the other reference are not needed, because are already included by fsi

after that, evaluating 

```fsharp
> open MathNet.Numerics.LinearAlgebra;
-
- let MatrixToRowSeqSeq matrix1 =
-     Matrix.toRowArrays matrix1
-     |> Array.map Array.toSeq
-     |> Array.toSeq

- ;;
val MatrixToRowSeqSeq :
  matrix1:MathNet.Numerics.LinearAlgebra.Matrix<'a> -> seq<seq<'a>>
    when 'a : (new : unit -> 'a) and 'a : struct and
         'a :> System.IEquatable<'a> and 'a :> System.IFormattable and
         'a :> System.ValueType
```


@Krzysztof-Cieslak as future enhancement:
- adding a `send the reference to fsi` from `F# project explorer` reference node, can help avoid the need to generate the reference script.
- adding a `send reference list to fsi` as treeview command in the `Reference` node

**Comment by enricosada** [comment] 2017-09-18 14:08
added https://github.com/Microsoft/visualfsharp/issues/3600 to track fsi issue in vf# repo

**Comment by chanjunweimy** [comment] 2017-09-19 01:44
@enricosada Thanks a lot for your help and reply! Unfortunately the workaround still doesn't work for me, I have done the following:
1. Generate script file
2. Navigate to Issue.fs
3. Copy both MathNet.Numerics and MathNet.Numerics.FSharp (After reordered)
4. Send References from project
2. Referenced MathNet.Numerics.dll
3. Referenced MathNet.Numerics.FSharp.dll
4. Execute 
````
> open MathNet.Numerics.LinearAlgebra;
-
- let MatrixToRowSeqSeq matrix1 =
-     Matrix.toRowArrays matrix1
-     |> Array.map Array.toSeq
-     |> Array.toSeq
````

Expected:
````
val MatrixToRowSeqSeq :
  matrix1:MathNet.Numerics.LinearAlgebra.Matrix<'a> -> seq<seq<'a>>
    when 'a : (new : unit -> 'a) and 'a : struct and
         'a :> System.IEquatable<'a> and 'a :> System.IFormattable and
         'a :> System.ValueType
````

Actual:
````
error FS0074: The type referenced through 'MathNet.Numerics.LinearAlgebra.Matrix`1; is defined in an assembly that is not referenced....
````

Screenshot:
![image](https://user-images.githubusercontent.com/7464833/30572215-ea07c01c-9d1e-11e7-8cc4-2f31764fd432.png)

Thank you.

Regards,
Jun Wei

**Comment by chanjunweimy** [comment] 2017-10-05 07:34
@enricosada Thanks a lot for your help! After investigating, I realized that my antivirus actually blocked some ionide files, causing some issues. After adding the extension into the exception list, the workaround worked fine. Thanks a lot!

**Comment by enricosada** [comment] 2017-10-05 09:00
@chanjunweimy awesome!

Closing this, the bug in fsi is tracked in https://github.com/Microsoft/visualfsharp/issues/3600 , is not something ionide related.

**Closed by enricosada** 2017-10-05 09:00 UTC
Labels: backburner - requires additional upstream functionality, bug, language services (FSAC / FCS / Project Cracker)
