### ISSUE TITLE
#load relative path does not work for first trial only

### ISSUE THREAD

**Issue by dgrimmin** [ionide/ionide-vscode-fsharp#1605] opened 2021-10-22 07:55 UTC
### Describe the bug**
Selection of a "#load ./test.fsx" statement followed by alt+enter opens fsi, but errors with:

stdin(1,1): error FS0078: Unable to find the file './test.fsx' in any 
of <rootdir>

second alt+enter works fine. **test.fsx is located in a subdirectory of rootdir.**

## Machine info
 - OS: Windows
 - .NET SDK version: 5.0.201
 - Ionide version: 5.7.3
 - VScode (1.62 insiders)

### Additional context
It seems to me that on opening fsi information about __SOURCE_DIRECTORY__ is not yet available. Second alt+enter that is clearly the case.

(I am a backer)

**Comment by nhirschey** [comment] 2021-10-30 10:31
Hi @dgrimmin, this is a known issue that ionide currently does not properly send the first line of a script with alt+enter correctly. See the comment here: https://github.com/ionide/ionide-vscode-fsharp/issues/1562#issuecomment-894546776

It appears that the main developer has a fix in process, but in the meantime you can follow the suggestions in the comment that I linked to. If you start each session by sending a blank line with alt+enter, thereafter it should work as expected.

**Comment by nhirschey** [comment] 2021-10-30 10:35
Also, for the backer label on issues you need to add your github name to your open collective profile. The open collective bot seems to be case sensitive https://github.com/opencollective/opencollective/issues/4006, so make sure it is exactly "dgrimmin" in your opencollective profile.

**Comment by dgrimmin** [comment] 2021-11-01 08:50
Thank you!

**Comment by Krzysztof-Cieslak** [comment] 2021-11-19 15:09
I'll close this one as duplicate of #1562

**Closed by Krzysztof-Cieslak** 2021-11-19 15:09 UTC
