### ISSUE TITLE
Building Project Scaffold asks for input in the read-only Output window

### ISSUE THREAD

**Issue by piaste** [ionide/ionide-vscode-fsharp#323] opened 2016-12-30 20:05 UTC
When I use the default build command (ctrl-F5) for the first time after using the `F#: New Project (Project Scaffold)` feature, the various calls to `Console.ReadLine()` that ProjectScaffold uses are sent to the _output_ window, which in VSCode is read-only. As a result, the initialisation script cannot be completed and the project cannot be built.

Screenshot:

![code_2016-12-30_20-43-25](https://cloud.githubusercontent.com/assets/12280683/21571541/b3425564-ced0-11e6-97ef-d1af2954c9e4.png)

Bypassing the problem is easy - just edit the `init.fsx` script and replace the `prompt` calls with your choices - but this is one of the first features that a new user will try, so it should be smoother sailing.

A proper fix would be to either replace or redirect those calls to an input-enabled console, such as the FSI window or the integrated terminal.

**Comment by Krzysztof-Cieslak** [comment] 2017-01-05 20:38
I don't think there is anything we can do about it. Readonly panel for FAKE is working for 99% cases.  And we don't have reasonable way of detecting if build will ask for input or not. 

Closing as `by design`

**Closed by Krzysztof-Cieslak** 2017-01-05 20:38 UTC
