### ISSUE TITLE
Eternal hang on format document

### ISSUE THREAD

**Issue by briandunn** [ionide/ionide-vscode-fsharp#1606] opened 2021-10-28 23:04 UTC
### Describe the bug**
Calling the formatter either hangs forever or shows "No Fantomas install was found." Either "Install locally" or "Install globally" buttons do nothing. `fantomas` *is* in my `$PATH` and works via cli.

### Steps to reproduce
1. open an fsharp file
2. format the file (save, or choose Format Document from the context menu)

### Expected behaviour

The code is formatted by fantomas

### Screenshots

![image](https://user-images.githubusercontent.com/93310/139347405-9bd05dd9-8543-4342-924d-0a08068aa76e.png)

## Machine info
 - OS: Mac
 - .NET SDK version: 6.0.100-rc.2.21505.57
 - ionide-fsharp version: 5.8.1

### Additional context
Can't find anything in the logs that is obviously relevant.

**Comment by briandunn** [comment] 2021-10-29 19:47
> Hello Brian, thanks for reaching out. Having Fantomas on your $Path isn't necessarily going to cut it. You need a [compatible version of Fantomas](https://github.com/fsprojects/fantomas/blob/4.6/docs/Daemon%20mode.md#end-user-impact) installed as local or global cli tool.
> 
> What do you get when you execute `fantomas --version`? And what do you get when you see `dotnet tool list -g`?

`➜ fantomas --version
Fantomas v4.5.4
➜ dotnet tool list -g
Package Id          Version      Commands             
------------------------------------------------------
fake-cli            5.20.4       fake                 
fantomas-tool       4.5.4        fantomas             
fsautocomplete      0.47.2       dotnet-fsautocomplete`

**Comment by seanamos** [comment] 2021-10-30 23:53
Similar problem.

Running `Format Document` results in VSCode showing a loading bar at the top of the editor forever, the window remains responsive though. The loading bar is only fixed by reloading the window.

I have `fantomas-tool 4.5.5` installed as a _local_ dotnet tool.

**Comment by nojaf** [comment] 2021-10-31 06:42
Hi, you need 4.6 as mentioned in the docs.

> dotnet tool install --local fantomas-tool --version 4.6.0-alpha-005

Could you please try installing this exact version?

**Comment by seanamos** [comment] 2021-10-31 11:54
After installing `4.6.0-alpha-005`, I get the same problem.

**Comment by nojaf** [comment] 2021-10-31 15:53
What operating system are you on?

**Comment by nojaf** [comment] 2021-10-31 15:56
Also, is everybody on Ionide extension `5.8.1`?

**Comment by seanamos** [comment] 2021-10-31 17:36
I am on Linux (Pop!_OS) Ubuntu `20.04`, using Ionide-fsharp `5.8.1`.

**Comment by nojaf** [comment] 2021-11-02 15:20
Someone just confirmed to me that on Ubuntu 21.10 (the Xubuntu flavour), it works as expected.
Would anyone be willing to debug FsAutocomplete perhaps? This could give us some more insights into what is happening on the LSP side. I can provide some steps if anyone is interested.

**Comment by recfab** [comment] 2021-11-02 22:20
I'm running into the same problem.

fantomas is installed as a tool, globally and locally, but not directly on the PATH

## Environment information

Ionide.Ionide-fsharp vscode exteion version: 5.8.1

```shell
$  uname -a                                                                                                                                             ─╯
Darwin WS-126272a 19.6.0 Darwin Kernel Version 19.6.0: Thu Sep 16 20:58:47 PDT 2021; root:xnu-6153.141.40.1~1/RELEASE_X86_64 x86_64

$ fantomas --version                                                                                                                                   ─╯
zsh: command not found: fantomas

$ dotnet fantomas --version
Fantomas v4.6.0-alpha-005+e4a18aa21c5ca96053c720770e55cfd6f185b64

$ dotnet tool list
Package Id         Version              Commands      Manifest                                                       
---------------------------------------------------------------------------------------------------------------------
fantomas-tool      4.6.0-alpha-005      fantomas      /Users/nameny/code/personal/yggdrasil/.config/dotnet-tools.json

$ dotnet tool list -g
Package Id         Version              Commands
------------------------------------------------
fantomas-tool      4.6.0-alpha-004      fantomas
```

## Testing script

I saved your testing script as `ionide-vscode-fsharp-issue-1606.fsx` and ran it against a file called Asciidoc.fsx

Here is the output when it does not need formatting:

```shell
$ dotnet fsi scripts/ionide-vscode-fsharp-issue-1606.fsx
{ Code = 2
  FilePath = "/Users/nameny/code/personal/yggdrasil/scripts/Asciidoc.fsx"
  Content = None }
```

and when it does:

```shell
$ dotnet fsi scripts/ionide-vscode-fsharp-issue-1606.fsx           
dotnet fsi scripts/ionide-vscode-fsharp-issue-1606.fsx
{ Code = 3
  FilePath = "/Users/nameny/code/personal/yggdrasil/scripts/Asciidoc.fsx"
  Content =
   Some
     "Parsing failed with errors: [|/Users/nameny/code/personal/yggdrasil/scripts/Asciidoc.fsx (6,3)-(6,4) parse error Unexpected symbol '|' in implementation file|]
And options: { SourceFiles = [|"/Users/nameny/code/personal/yggdrasil/scripts/Asciidoc.fsx"|]
  ConditionalCompilationDefines = []
  ErrorSeverityOptions = { WarnLevel = 3
                           GlobalWarnAsError = false
                           WarnOff = []
                           WarnOn = []
                           WarnAsError = []
                           WarnAsWarn = [] }
  LangVersionText = "default"
  IsInteractive = false
  LightSyntax = None
  CompilingFsLib = false
  IsExe = true }" } 
```

Running fantomas directly seems to work fine, on the same file

```shell
$ dotnet fantomas scripts/ionide-vscode-fsharp-issue-1606.fsx                                                                                         
Processing scripts/ionide-vscode-fsharp-issue-1606.fsx
scripts/ionide-vscode-fsharp-issue-1606.fsx has been written.
```

**Comment by nojaf** [comment] 2021-11-03 07:16
Hello @recfab, thank you for this elaborate report. Could you share the contents of `Asciidoc.fsx`?
I'd like to find out why you got `Code = 3` for what code.

When you used `dotnet fantomas scripts/ionide-vscode-fsharp-issue-1606.fsx` the last time, that would be using the global version right (alpha 4)?
Does the error also occur when you navigate to the  `/Users/nameny/code/personal/yggdrasil` folder and format using the command line over there?

**Comment by recfab** [comment] 2021-11-03 18:14
> When you used `dotnet fantomas scripts/ionide-vscode-fsharp-issue-1606.fsx` the last time, that would be using the global version right (alpha 4)? Does the error also occur when you navigate to the `/Users/nameny/code/personal/yggdrasil` folder and format using the command line over there?

The flip actually: I ran it from within my repo, but ran it against the wrong file. 

If I run it on the correct file, I get the same Code 3 response as the script, but that's because I'm an F# newb and messed up the syntax. After fixing the syntax so that it compiles, it works as expected. Given that, I'm not sure this is useful, but for completeness sake:

```shell
~ $ dotnet tool list -g
Package Id         Version      Commands
----------------------------------------
fantomas-tool      4.5.6        fantomas

~ $ dotnet fantomas ~/code/personal/yggdrasil/scripts/Asciidoc.fsx
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-fantomas does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
```

Today I learned: you can only use global tools as `dotnet <command>` if the executable is named `dotnet-<command>`. I can run it directly though

 ```shell
~ $ which fantomas
/Users/nameny/.dotnet/tools/fantomas

~ $ fantomas ~/code/personal/yggdrasil/scripts/Asciidoc.fsx
Processing /Users/nameny/code/personal/yggdrasil/scripts/Asciidoc.fsx
/Users/nameny/code/personal/yggdrasil/scripts/Asciidoc.fsx has been written.
```

And as a local tool:

```shell
~ $ cd ~/code/personal/yggdrasil

~/code/personal/yggdrasil $ dotnet tool list
Package Id         Version              Commands      Manifest
---------------------------------------------------------------------------------------------------------------------
fantomas-tool      4.6.0-alpha-005      fantomas      /Users/nameny/code/personal/yggdrasil/.config/dotnet-tools.json

~/code/personal/yggdrasil $ dotnet fantomas ./scripts/Asciidoc.fsx
Processing ./scripts/Asciidoc.fsx
./scripts/Asciidoc.fsx has been written.
```

Asciidoc.fsx contains a single sum type:

```fsharp
// The spec and corresponding TCK are not ready yet
// This file is partially based on the MR here:
// https://gitlab.eclipse.org/eclipse/asciidoc-lang/asciidoc-lang/-/merge_requests/6

type Node =
  | Preamble | Paragraph | Section | Verse
  | STEM | Sidebar | Quote | Open
  | Example | Listing | Literal | Admonition
  | Image | Video | Audio | Pass
  | AttributeReference | AttributeDefinition
  | Strong | Emphasis | Monospace | Subscript
  | Superscript | SingleQuotation | DoubleQuotation
  | Str | Anchor | OrderedList | UnorderedList | DescriptionList
  | InlineImage | InlineBreak | InlineButton | InlineMenu
  | InlineMacro | Table
```

**Comment by nojaf** [comment] 2021-11-03 19:17
Thanks, if you open `/Users/nameny/code/personal/yggdrasil` in vscode I would expect formatting to work there.
Other scenarios might not work as your global version `4.5.6` is not compatible with the latest changes in Ionide.

**Comment by recfab** [comment] 2021-11-03 20:47
I updated the global tool to the correct version and made sure it was on the path (as `fantomas`) and it seems to work for me now. I had tried some other steps to create a repro, but I cannot get it to hang.

(In trying to reproduce this, I quit and restarted vscode repeatedly, toggling the `FSharp.showProjectExplorerIn` setting, and trying with and without fantomas on my PATH. About half the time, Ionide just didn't activate at all, but when that happens it doesn't hang, it just doesn't do anything, so I don't think it's related.)

**Comment by seanamos** [comment] 2021-11-04 10:55
Installing the tool globally didn't fix the problem for me:

```
~ 
➜ dotnet tool install -g fantomas-tool --version 4.6.0-alpha-006 
You can invoke the tool using the following command: fantomas
Tool 'fantomas-tool' (version '4.6.0-alpha-006') was successfully installed.

~ took 13s 
➜ fantomas
Input path is missing...
```
![Peek 2021-11-04 12-53](https://user-images.githubusercontent.com/10598927/140301850-2dc32945-c358-4dec-a6cb-320513bc0918.gif)

**Comment by nojaf** [comment] 2021-11-04 11:12
Could you check if there is a Fantomas process started (after you invoked the Format Document command)?
No idea, what command you need on your OS but in PowerShell this looks like:

> Get-Process -Name "fantomas"  | Format-Table Id, Name, CommandLine

```
   Id Name     CommandLine
   -- ----     -----------
27040 fantomas "fantomas" fantomas --daemon
```

If this process is present, formatting should work. If the process is not there, that might explain the hang in vscode.

Also, just to double-check, what does `fantomas --version` prompt? Should be `4.6.0-alpha-006`.

**Comment by seanamos** [comment] 2021-11-04 16:07
Running `ps -aux | grep fantomas` after running `Format Document` does not list a fantomas process.

While typing this though, bizarrely, it started to work after reloading VSCode multiple times.

```
➜ ps -aux | grep fantomas
seanamos  181682  6.1  0.4 4228632 76896 ?       Sl   17:59   0:01 dotnet fantomas --daemon
seanamos  181704  5.3  0.5 3238604 91992 ?       Sl   17:59   0:01 /usr/share/dotnet/dotnet /home/seanamos/.nuget/packages/fantomas-tool/4.6.0-alpha-005/tools/netcoreapp3.1/any/fantomas-tool.dll --daemon
```

I then killed the fantomas daemon process and reloaded VSCode and I cannot get it to work again. I tried about 20 times and the fantomas daemon process doesn't start.

**Comment by nojaf** [comment] 2021-11-04 16:28
Killing the process manually is something that Ionide will not recover from and should never be done.
I'm not sure what the impact of reloading VSCode is but I would expect things to only start working once you've exited and restarted the program.
I still can't tell much more, only that some of the behaviour of this entire thread can be explained by the process not being there.

**Comment by samritchie** [comment] 2021-11-05 03:24
I can confirm no fantomas process is running for me after I select "Format Document".

**Comment by nojaf** [comment] 2021-11-05 07:55
@samritchie I believe you've installed the local tool right?
Then the process will be `dotnet` with arguments `fantomas --daemon`.
Out of curiosity, can you start this process manually? Run inside the workspace, `dotnet fantomas --daemon`.
This should start the process but show no output. Could you verify that at least that works?
Oh and run `dotnet fantomas --version` as well for me please.

**Comment by samritchie** [comment] 2021-11-05 08:13
Yes, that’s correct, local tool. `dotnet fantomas --daemon` starts, checking processes from another shell shows `/usr/local/share/dotnet/dotnet /Users/sam/.nuget/packages/fantomas-tool/4.6.0-alpha-006/tools/netcoreapp3.1/any/fantomas-tool.dll --daemon`

`dotnet fantomas --version` returns `Fantomas v4.6.0-alpha-006+c90333468261671f2f0e8e065009160b74a41662`

**Comment by samritchie** [comment] 2021-11-08 00:04
Found this issue - https://github.com/fsharp/FsAutoComplete/issues/845 - problem is the ".NET Core Test Explorer" extension; I disabled the extension & format document magically started working...

**Comment by briandunn** [comment] 2021-11-08 15:23
> Found this issue - [fsharp/FsAutoComplete#845](https://github.com/fsharp/FsAutoComplete/issues/845) - problem is the ".NET Core Test Explorer" extension; I disabled the extension & format document magically started working...

Brilliant @samritchie worked for me too thanks!

**Comment by s6o** [comment] 2021-11-09 21:14
I did not have ".NET Core Test Explorer" installed, but was facing the same error message https://github.com/ionide/ionide-vscode-fsharp/issues/1606#issue-1039020462 after having updated to .NET 6 and ionide-fsharp 5.9.0

Upgrading fantomas-tool fixed it:
`dotnet tool update -g fantomas-tool --version 4.6.0-alpha-007 `

**Comment by seanamos** [comment] 2021-11-11 15:37
I can confirm disabling ".NET Core Test Explorer"  seems to fix formatting for me (I tested multiple times to make sure it wasn't a fluke). Enabling it again causes the eternal loading scenario again and the fantomas --daemon process failing to start.

**Comment by Choc13** [comment] 2021-11-12 15:49
FWIW, I could only get formatting working in VSCode again once I installed the latest version (4.6.0-alpha-007) as a *local* tool. When it was installed globally I was still seeing the formatter hang in VSCode, even with all other extensions disabled except for Ionide and after reinstalling fantomas and rebooting my machine.

**Comment by nojaf** [comment] 2021-11-19 10:53
@Choc13 what does your global version of Fantomas give you when you do `fantomas --version`?
Perhaps an incompatible version is still listed on your PATH somehow.

**Comment by Choc13** [comment] 2021-11-19 11:05
@nojaf I had `4.6.0-alpha-006` installed when I reported this IIRC. I had since removed the global tool, but fantomas / ionide had prompted me to install this again yesterday when working on some fsx script, so I clicked the install globally option to see if that would work again. That seems to have installed `v4.6.0-alpha-004+db3dc672e5ca5d8becefc0559e0c76bcd8d44e19` globally. I then tested a clean project that didn't have the tool installed locally and the formatting hung forever again. I then tried updating the global tool to latest `v4.6.0-alpha-007+b8509dd595f943be409d9bba0a57d9103bdb2d2a` and it still hangs. If I then uninstall the global tool, reload VS Code and run the formatter it detects there is no fantomas installed and prompts me to add it. If I then choose to install locally it populates the tool manifest file with version `4.6.0-alpha-004` and formatting starts working fine again.

**Comment by nojaf** [comment] 2021-11-19 11:09
Hmm, thank you for the details. What OS are you on?

**Comment by Choc13** [comment] 2021-11-19 11:14
macOS 12.0.1. Also dotnet SDK version is 6.0.100, but I only installed that a few days ago, so I believe this was happening when I was also working from 5.0.300

**Comment by nojaf** [comment] 2021-11-30 08:50
Hi all, we are still working on this issue and I've gained some insight during a call yesterday where I could witness the problem firsthand.

That being said, could somebody try and download the latest version of [Fantomas.Client](https://www.nuget.org/packages/Fantomas.Client/0.4.1) and drop the `Fantomas.Client.dll` in the bin folder of your ionide install (For me on Windows this is `C:\Users\fverdonck\.vscode\extensions\ionide.ionide-fsharp-5.10.1\bin`).

Close vscode, reopen and try to format. At the very least a better error message should be shown in the logs.

Thanks in advance.

**Comment by nojaf** [comment] 2021-12-03 22:16
@briandunn and others, the last version of Ionide has the recent improvements. Is this working out for anyone?

**Comment by seanamos** [comment] 2021-12-03 23:03
@nojaf At least for me, it appears Format Document is working consistently now.

**Comment by jahast** [comment] 2021-12-04 19:39
Had this issue with `v4.6.0-alpha-007` installed. Wouldn't work whether I installed it globally or locally (no ".NET Core Test Explorer"). Upgrading it to `4.6.0-alpha-010` seemed to fix it 👍 

- OS: Mac
- .NET SDK version: 6.0.100
- ionide-fsharp version: 5.10.2

**Comment by nojaf** [comment] 2021-12-04 20:16
Alpha-10 is most likely not the reason it started working. More likely the latest Ionide made it work. Nonetheless, happy to hear more people are having some success.

**Comment by seanamos** [comment] 2021-12-10 14:11
Unfortunately, I have to take back my previous statement about it working consistently for me.
I don't know what exactly changed (a few reboots?), but I'm again running into the issue that if I have the .NET Test Explorer extension enabled, attempting to use `Format Document` results in an eternal loading bar.

**Comment by sonicbhoc** [comment] 2021-12-14 20:21
I am having the same issue as people above. Disabling .NET Test Explorer makes format document work again.

Ionide version 5.10.2
.NET Core Test Explorer 0.7.7
VSCode version 1.63.1
OS: Windows 10 19042

**Comment by nojaf** [comment] 2021-12-16 07:51
I'm able to reproduce this, however, I cannot see any F# logs when both extensions are loaded:
![image](https://user-images.githubusercontent.com/2621499/146330005-32834cf8-4ceb-40e7-944d-bb3024814a07.png)

Is this the same for you?

**Comment by seanamos** [comment] 2021-12-16 13:38
I am able to get logs with both extensions enabled if I enable the F# extension verbose logging option.

Unfortunately there isn't any useful information in the logs.
This is the only log entry that gets created when running `Format Document`:
```
[15:33:44.697 INF] [LSP] TextDocumentFormatting Request: {"TextDocument": {"Uri": "file:///xxx.fs", "$type": "TextDocumentIdentifier"}, "Options": {"TabSize": 4, "InsertSpaces": true, "AdditionalData": {}, "$type": "FormattingOptions"}, "$type": "DocumentFormattingParams"}
```

Loading bar continues indefinitely.

**Comment by nojaf** [comment] 2021-12-18 09:33
Ok, I was able to debug this one and saw what went wrong.
The issue with `.NET Test Explorer` has been addressed and fixed in the latest version of Fantomas.Client.

Could somebody try and download the latest version of [Fantomas.Client](https://www.nuget.org/packages/Fantomas.Client/0.5.1) and drop the Fantomas.Client.dll in the bin folder of your ionide install (For me on Windows this is C:\Users\fverdonck\.vscode\extensions\ionide.ionide-fsharp-5.10.1\bin).

Close vscode, reopen and try to format.
Thanks

**Comment by seanamos** [comment] 2021-12-18 09:46
Just tested with the new `Fantomas.Client` and it seems to work for me!

Side (unrelated) note. Errors launching the Fantomas daemon don't seem to be reported to the user outside of the logs:
```
[Error - 11:42:43 AM] Request textDocument/formatting failed.
  Message: Formatting failed!
{ Code = 11
  FilePath = "xxx.fs"
  Content =
   Some
     "Fantomas.Client tried to run `dotnet fantomas --daemon` but failed with "Daemon std error: Run "dotnet tool restore" to make the "fantomas" command available.
.
JsonRpc exception:One or more errors occurred. (The JSON-RPC connection with the remote party was lost before the request could complete.)"" }
  Code: -32603 
```

I had the F# logs open so it was easy to spot and rectify. Without the tool restored, it did fail fast and the loading bar did stop correctly.
With the tool restored, everything worked as expected.

**Comment by nojaf** [comment] 2021-12-18 09:57
Thanks for testing this, a fix is on the way in https://github.com/fsharp/FsAutoComplete/pull/873.

I'm aware of this edge case where if the tools are not restored, `Fantomas.Client` can find a compatible version but not start it.
I'll need to think about if we want to deal with this or not.

**Comment by seanamos** [comment] 2021-12-18 11:50
This might just be coincidence, but after adding the new `Fantomas.Client.dll`, I am unable to replicate https://github.com/ionide/ionide-vscode-fsharp/issues/1594 anymore.

I've tried reloading/rebooting many times and Ionide now loads every time. Previously I would have to reload many times to get Ionide to start.

**Comment by nojaf** [comment] 2021-12-18 12:20
That bug was reported before the first Fantomas.Client release and before the .NET 6 changes, so I wouldn't correlate this just yet.

**Comment by peheje** [comment] 2022-01-08 21:14
I have also struggled for this for a while now.

I can see nojaf are working on this with a recent released 4.6.0-beta-001 a few hours ago. Can confirm that this version fixes the issue for me, had to uninstall the old version first:

```
dotnet tool uninstall --global fantomas-tool 
dotnet tool install --global fantomas-tool --version 4.6.0-beta-001
```

I then followed the installation notes to add dotnet tools to my path, and source current session. I  am using zsh on Mac.

```
export PATH="$PATH:/Users/phj/.dotnet/tools"
zsh -l
```

Thanks!

Is the plan to use this new version in the installation of the Ionide-fsharp vscode extension by default?

**Comment by baronfel** [comment] 2022-01-08 21:17
yeah, the version suggested/installed is just a string in the source code, so we can update it basically at will.

**Comment by askpt** [comment] 2022-01-21 11:27
> Ok, I was able to debug this one and saw what went wrong. The issue with `.NET Test Explorer` has been addressed and fixed in the latest version of Fantomas.Client.
> 
> Could somebody try and download the latest version of [Fantomas.Client](https://www.nuget.org/packages/Fantomas.Client/0.5.1) and drop the Fantomas.Client.dll in the bin folder of your ionide install (For me on Windows this is C:\Users\fverdonck.vscode\extensions\ionide.ionide-fsharp-5.10.1\bin).
> 
> Close vscode, reopen and try to format. Thanks

This sorted my issue! With the `.NET Test explorer` extension and the formatter. Thanks a lot!

**Comment by nojaf** [comment] 2022-01-21 11:57
Hey @briandunn, do you still have the issue now?
I was hoping we could close this issue and perhaps follow up on another issue if other people still experience problems.

**Comment by realvictorprm** [comment] 2022-02-03 22:49
> 

that fixed it for me too

**Comment by baronfel** [comment] 2022-04-04 19:37
Closing as Fantomas and the test extension play nicely now.

**Closed by baronfel** 2022-04-04 19:37 UTC
Labels: Fantomas

**Comment by Ericarthurc** [comment] 2022-05-25 21:39
Had this same issue, and nothing was working. But I also couldn't manually install any version of fantomas. 
This resoolved my issue:
`dotnet nuget list` is this is empty then run `dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org`
