### ISSUE TITLE
Intellisense not working for packages with Ionide in VSCode

### ISSUE THREAD

**Issue by jimmyp** [ionide/ionide-vscode-fsharp#421] opened 2017-04-26 22:13 UTC
I am just beginning with FSharp and am trying to work in VSCode on my mac. I've followed all the install instructions here https://github.com/dotnet/netcorecli-fsc/wiki/.NET-Core-SDK-1.0.1

However Inoide can't seem to pick up any of the packages I've added. Here is an example:

[![Screenshot of error][1]][1]

  [1]: https://i.stack.imgur.com/a2nzK.png

As you can see the plugin is running ok as I get type info but it won't pick up the package. Hovering on the red squiggly shows the error `The namespace of module 'FsUnit' is not defined`

I'm running dotnetcore 1.0.3 and inoide-fsharp 2.25.10

**Comment by zakaluka** [comment] 2017-04-30 22:48
I am experiencing the same issue, and was able to reproduce it with a new project.  Here is what I did:

1. Open VS Code, ensure all extensions are updated (Ionide-fsharp, Ionide-FAKE, Ionide-Paket are the main ones).
1. Open an empty folder.
1. Hit Ctrl+Shift+P
1. Select "F#: New Project"
1. Select "expecto"
1. Leave Project directory blank (doesn't really matter)
1. Enter a name for the project (I used Temp)
1. Allow all updates to finish
1. Open Temp.fsproj
1. Change "TargetFrameworkVersion" to 4.6.1 (what Expecto is built against)
1. Open Tests.fs

At this point, I see that all Expecto references (the 'open', attributes, etc.) are underlined in red and mousing them shows some variation of "The namespace or module 'Expecto' is not defined."

However, if you run build.cmd, the project builds successfully.

Here are 3 images showing this behavior.

Update to Temp.fsproj: http://imgur.com/OBpLfYK

Build succeeded: http://imgur.com/BJu2tPL

Tests.fs can't recognize the library: http://imgur.com/M601yeA

**Comment by czifro** [comment] 2017-05-02 00:34
I followed all 11 steps and cannot reproduce it. I also recreated a project according to @jimmyp 's pic and could not reproduce. Here are the specs I'm using:

```
OS => macOS Sierra 10.12.3
DotNet CLI => 1.0.3
Mono => 4.6.1 (arch: amd64)
VSCode => 1.11.2
Ionide-fsharp => 2.25.10
Ionide-FAKE => 1.2.3
Ionide-Paket => 1.6.3
```

(If there are later versions of the ionide packages, they have not appeared for me yet.)

I also tried closing and opening vscode and could not reproduce. I am a bit confused why I cannot reproduce.

**Comment by jimmyp** [comment] 2017-05-02 06:55
My steps would be slightly different as a dotnet core project they would be:

1. Open VS Code
2. Open an empty folder
3. Open the Terminal (ctrl-`)
4. `dotnet new classlib -lang f#`
5. `dotnet add package FsUnit`
6. Add the following code to `Library.fs`
```namespace vscode_ionide_issue

open FsUnit

module Say =
    let hello name =
        printfn "Hello %s" name```

Result:
FsUnit has a red squiggly

Expected Result:
FsUnit should not have a red quiggly

**Comment by jimmyp** [comment] 2017-05-02 06:57
My repro steps will be slightly different as I'm using dotnet core. I'll add them shortly.

**Comment by czifro** [comment] 2017-05-02 23:01
@jimmyp I am using dotnet core version 1.0.3.

**Comment by zakaluka** [comment] 2017-05-04 00:33
@czifro I only have one machine, so difficult to do.  I will try to get my hands on another machine and see if I can reproduce there.

**Comment by czifro** [comment] 2017-05-04 02:24
The only thing that sticks out is the F# path. According to [this line](https://github.com/ionide/FsAutoComplete/blob/master/src/FsAutoComplete.Core/Environment.fs#L69), 4.1 is not supported. It could also be what is wrong with #414. Could you try installing F# 4.0? I don't have a Windows machine to test this hypothesis.

/cc @Krzysztof-Cieslak

**Comment by zakaluka** [comment] 2017-05-04 22:13
@czifro I installed F# 4.0 RTM and removed the following line from my Ionide user settings:

```
"FSharp.toolsDirPath": "C:\\Program Files (x86)\\Microsoft SDKs\\F#\\4.1\\Framework\\v4.0"
```

I still get the same error, but I also saw something interesting on the `F# Language Service (server)` output:

```
Process is terminated due to StackOverflowException.
```

I did not get this same error message when my toolsDirPath was set to 4.1.  I changed the log output to "DEBUG" to see if it would provide any more information, but it did not.

If there is a way to get more information about that, please let me know so I can see if that is the root cause of the problem.

**Comment by zakaluka** [comment] 2017-05-07 04:42
Ok, I was able to solve the problem, and here's how I did it.

1. Uninstalled VS 2017 Community Edition, including all SDKs, etc. (not sure if this was required or not).
1. Downloaded and installed .NET Core SDK for Windows x64 from [https://www.microsoft.com/net/download/core](https://www.microsoft.com/net/download/core).
1. Downloaded and installed F# 4.0 RTM from [https://www.microsoft.com/en-us/download/details.aspx?id=48179](https://www.microsoft.com/en-us/download/details.aspx?id=48179).
1. Downloaded and installed MSBuild Tools 2015 from [https://www.microsoft.com/en-us/download/details.aspx?id=48159](https://www.microsoft.com/en-us/download/details.aspx?id=48159).

The key issue I had was that I was receiving an error about Build 14.0 not being available, and the last package solved that.

Installing all this basically gave me .NET Standard 1.x (4?, 5?, ... not sure).  The important thing is that it solved my problem.  

However, my original code was against .NET 4.6.1 and there were certain functions that the .NET Standard did not contain (or contained with different signatures).  I didn't bother trying to install the .NET SDK again.  Instead, the problems were few enough and simple enough that I just rewrote those parts of the code.

Hope this helps someone dealing with this problem (at least on Win 7).

**Comment by jimmyp** [comment] 2017-05-07 06:48
I haven't been able to reliably reproduce this today when I've tried. Thanks for your time, happy to close this and I'll open another issue if I can nail it down.

**Closed** 2017-05-07 10:53 UTC
