### ISSUE TITLE
Certain chars inside double-backtick identifiers cause VSCode to freeze

### ISSUE THREAD

**Issue by belcher-rok** [ionide/ionide-vscode-fsharp#1644] opened 2021-11-24 23:40 UTC
### Describe the bug

VSCode will freeze when certain characters are used inside a double-backtick identifier.

Specifically, all non-word, non-space characters (`[^\s\w]`) appear to cause the behavior. The dot (`.`) and quote (`'`) chars are noticeably worse than others.

The length of the freeze depends on where the character is inserted within the identifier -- the deeper into the identifier, the longer the pause. it seems to be exponential.

Such identifiers are very common in unit tests, e.g.,
```F#
let ``when some long winded condition, it should blah``() = ...
```

### Steps to reproduce

1. Open VS Code with Ionide-fsharp extension enabled
2. Create a new file (`Ctrl+N`)
3. Change the language to `F#`
4. Paste the following code:
   ```F#
   // Insert a dot (.) before here and it responds okay (slight delay):
   //                         V
   let ``A 123456789 123456789 123456789`` () = ()
   
   // Insert a dot here and it freezes for 4-10 seconds:
   //                             V
   let ``B 123456789 123456789 123456789`` () = ()
   
   // Insert a dot here and it freezes for 30-60 seconds:
   //                               V
   let ``C 123456789 123456789 123456789`` () = ()
   
   // Insert a dot here and it will not return:
   //                                   V
   let ``D 123456789 123456789 123456789`` () = ()
   
   // Note: Inserting a comma in these locations has no noticeable delay:
   //                                VVV       VVV
   let ``E 123456789 123456789 123456789 123456789`` () = ()
   ```
5. Insert a dot (`.`) at the locations below by the `V` pointers. Observe how the freeze gets progressive worse.

### Link to sample reproduction

[Gist](https://gist.github.com/belcher-rok/9bf90b022f22bbe26b849859ea84aceb) of above example.

### Expected behavior

There should be no noticeable delay.

## Machine info
 - OS: Windows_NT x64 10.0.19042
 - .NET SDK version: 3.1,415, 5.0,402, 6.0.100
 - Ionide version: 5.10.1
 - VSCode: 1.62.3 (system setup)

### Additional context
- I was able to reproduce with all extensions disabled, except for ionide-fsharp.
- I have been living with this issue for about a year.

**Comment by baronfel** [comment] 2021-11-24 23:47
Thanks for reporting. We think this is because of a regex exhaustion failure that is causes by one of the rules in the text mate grammar that's used by ionide to provide basic syntax highlighting: https://github.com/ionide/ionide-fsgrammar

As of yet we're not sure which rule or combination of rules causes this failure, though.

**Comment by Krzysztof-Cieslak** [comment] 2021-11-25 12:28
Duplicate of https://github.com/ionide/ionide-vscode-fsharp/issues/1073, can you please repost your findings there? Thanks.

**Closed by Krzysztof-Cieslak** 2021-11-25 12:28 UTC

**Comment by MangelMaxime** [comment] 2021-11-25 13:09
@baronfel Last time I checked, the problem was not from the grammar but from another part of Ionide. Unfortunatly, I wasn't able to narrow it down.

See: https://github.com/ionide/ionide-vscode-fsharp/issues/1073#issuecomment-584067710

I disabled the grammar from Ionide and was still having the problem.
