### ISSUE TITLE
Format on save hangs and never saves file. 

### ISSUE THREAD

**Issue by parkeradam** [ionide/ionide-vscode-fsharp#1628] opened 2021-11-12 16:21 UTC
### Describe the bug
Unable to format document as it just hangs. Tried both format on Save and Format docuemnt from command pallete

### Steps to reproduce
1) Create a folder with an .fsx file inside. 
2) Type some code
3) Save with "Format on Save" Active. Simpley Hangs

### Link to sample reproduction
No Sample

### Expected behaviour
I expect the document to format and save. 

### Screenshots
<img width="1440" alt="Screenshot 2021-11-12 at 15 31 55" src="https://user-images.githubusercontent.com/30392071/141497924-aecbe348-e5a2-4274-b983-69ce1404891f.png">

## Machine info
 - OS: Mac OS Big Sur 11.6
 - .NET SDK version: 6.0.100
 - Ionide version: 5.9.0
 - Fantomas Version : 4.6.0-alpha-007 (installed as gloabl tool as writing scripts, not projects)

### Additional context
I have found the issue listed at https://github.com/ionide/ionide-vscode-fsharp/issues/1606
I have tried the steps in there and fantomas standalone works (see screenshot terminal) and i get a fantomas process running. 
<img width="324" alt="Screenshot 2021-11-12 at 16 14 37" src="https://user-images.githubusercontent.com/30392071/141498639-d0957c43-8b97-4522-939d-bd33589e9735.png">

**Comment by Krzysztof-Cieslak** [comment] 2021-11-12 19:15
Duplicate of #1606

**Closed by Krzysztof-Cieslak** 2021-11-12 19:15 UTC
